// Portfolio Planner — Sample Stock Data
import { nanoid } from 'nanoid';
import type { Stock } from './types';
import { DEFAULT_PROJECTIONS } from './types';

export { DEFAULT_PROJECTIONS };

export const SAMPLE_STOCKS: Stock[] = [
  {
    id: nanoid(),
    ticker: 'AAPL',
    name: 'Apple Inc.',
    industry: 'Technology',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 227,
      currentMarketCap: 3500000,
      currentRevenue: 391000,
      currentNetIncome: 94000,
      currentEPS: 6.11,
      currentPE: 37,
      currentPS: 9,
      currentFCF: 108000,
      valuationMethod: 'pe',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 391000, revenueGrowthRate: 4, netIncomeCurrentYear: 94000, netIncomeGrowthRate: 4, peMultiple: 25, psMultiple: 7, epsCurrentYear: 6.11, epsGrowthRate: 4, grossMargin: 45, fcfCurrentYear: 108000, fcfGrowthRate: 4, fcfMultiple: 25, sharesOutstanding: 15400 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 391000, revenueGrowthRate: 8, netIncomeCurrentYear: 94000, netIncomeGrowthRate: 10, peMultiple: 32, psMultiple: 9, epsCurrentYear: 6.11, epsGrowthRate: 10, grossMargin: 46, fcfCurrentYear: 108000, fcfGrowthRate: 10, fcfMultiple: 30, sharesOutstanding: 15400 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 391000, revenueGrowthRate: 14, netIncomeCurrentYear: 94000, netIncomeGrowthRate: 18, peMultiple: 40, psMultiple: 12, epsCurrentYear: 6.11, epsGrowthRate: 18, grossMargin: 48, fcfCurrentYear: 108000, fcfGrowthRate: 18, fcfMultiple: 40, sharesOutstanding: 15400 },
    },
  },
  {
    id: nanoid(),
    ticker: 'MSFT',
    name: 'Microsoft Corp.',
    industry: 'Technology',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 415,
      currentMarketCap: 3080000,
      currentRevenue: 245000,
      currentNetIncome: 88000,
      currentEPS: 11.80,
      currentPE: 35,
      currentPS: 12.5,
      currentFCF: 75000,
      valuationMethod: 'pe',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 245000, revenueGrowthRate: 10, netIncomeCurrentYear: 88000, netIncomeGrowthRate: 10, peMultiple: 28, psMultiple: 10, epsCurrentYear: 11.80, epsGrowthRate: 10, grossMargin: 69, fcfCurrentYear: 75000, fcfGrowthRate: 10, fcfMultiple: 28, sharesOutstanding: 7430 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 245000, revenueGrowthRate: 16, netIncomeCurrentYear: 88000, netIncomeGrowthRate: 18, peMultiple: 35, psMultiple: 13, epsCurrentYear: 11.80, epsGrowthRate: 18, grossMargin: 71, fcfCurrentYear: 75000, fcfGrowthRate: 18, fcfMultiple: 35, sharesOutstanding: 7430 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 245000, revenueGrowthRate: 22, netIncomeCurrentYear: 88000, netIncomeGrowthRate: 25, peMultiple: 45, psMultiple: 16, epsCurrentYear: 11.80, epsGrowthRate: 25, grossMargin: 73, fcfCurrentYear: 75000, fcfGrowthRate: 25, fcfMultiple: 45, sharesOutstanding: 7430 },
    },
  },
  {
    id: nanoid(),
    ticker: 'NVDA',
    name: 'NVIDIA Corp.',
    industry: 'Technology',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 875,
      currentMarketCap: 2150000,
      currentRevenue: 130000,
      currentNetIncome: 72000,
      currentEPS: 2.94,
      currentPE: 55,
      currentPS: 25,
      currentFCF: 60000,
      valuationMethod: 'pe',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 130000, revenueGrowthRate: 20, netIncomeCurrentYear: 72000, netIncomeGrowthRate: 20, peMultiple: 35, psMultiple: 15, epsCurrentYear: 2.94, epsGrowthRate: 20, grossMargin: 74, fcfCurrentYear: 60000, fcfGrowthRate: 20, fcfMultiple: 35, sharesOutstanding: 24400 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 130000, revenueGrowthRate: 40, netIncomeCurrentYear: 72000, netIncomeGrowthRate: 45, peMultiple: 50, psMultiple: 22, epsCurrentYear: 2.94, epsGrowthRate: 45, grossMargin: 76, fcfCurrentYear: 60000, fcfGrowthRate: 45, fcfMultiple: 50, sharesOutstanding: 24400 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 130000, revenueGrowthRate: 65, netIncomeCurrentYear: 72000, netIncomeGrowthRate: 70, peMultiple: 70, psMultiple: 30, epsCurrentYear: 2.94, epsGrowthRate: 70, grossMargin: 78, fcfCurrentYear: 60000, fcfGrowthRate: 70, fcfMultiple: 70, sharesOutstanding: 24400 },
    },
  },
  {
    id: nanoid(),
    ticker: 'AMZN',
    name: 'Amazon.com Inc.',
    industry: 'Consumer Discretionary',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 220,
      currentMarketCap: 2300000,
      currentRevenue: 620000,
      currentNetIncome: 59000,
      currentEPS: 5.53,
      currentPE: 40,
      currentPS: 3.7,
      currentFCF: 50000,
      valuationMethod: 'pe',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 620000, revenueGrowthRate: 8, netIncomeCurrentYear: 59000, netIncomeGrowthRate: 10, peMultiple: 28, psMultiple: 3, epsCurrentYear: 5.53, epsGrowthRate: 10, grossMargin: 47, fcfCurrentYear: 50000, fcfGrowthRate: 10, fcfMultiple: 28, sharesOutstanding: 10500 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 620000, revenueGrowthRate: 14, netIncomeCurrentYear: 59000, netIncomeGrowthRate: 20, peMultiple: 38, psMultiple: 4, epsCurrentYear: 5.53, epsGrowthRate: 20, grossMargin: 49, fcfCurrentYear: 50000, fcfGrowthRate: 20, fcfMultiple: 38, sharesOutstanding: 10500 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 620000, revenueGrowthRate: 20, netIncomeCurrentYear: 59000, netIncomeGrowthRate: 35, peMultiple: 50, psMultiple: 5.5, epsCurrentYear: 5.53, epsGrowthRate: 35, grossMargin: 52, fcfCurrentYear: 50000, fcfGrowthRate: 35, fcfMultiple: 50, sharesOutstanding: 10500 },
    },
  },
  {
    id: nanoid(),
    ticker: 'GOOGL',
    name: 'Alphabet Inc.',
    industry: 'Communication Services',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 195,
      currentMarketCap: 2400000,
      currentRevenue: 350000,
      currentNetIncome: 94000,
      currentEPS: 7.52,
      currentPE: 26,
      currentPS: 6.9,
      currentFCF: 72000,
      valuationMethod: 'pe',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 350000, revenueGrowthRate: 8, netIncomeCurrentYear: 94000, netIncomeGrowthRate: 8, peMultiple: 20, psMultiple: 5, epsCurrentYear: 7.52, epsGrowthRate: 8, grossMargin: 56, fcfCurrentYear: 72000, fcfGrowthRate: 8, fcfMultiple: 20, sharesOutstanding: 12500 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 350000, revenueGrowthRate: 13, netIncomeCurrentYear: 94000, netIncomeGrowthRate: 15, peMultiple: 26, psMultiple: 7, epsCurrentYear: 7.52, epsGrowthRate: 15, grossMargin: 58, fcfCurrentYear: 72000, fcfGrowthRate: 15, fcfMultiple: 26, sharesOutstanding: 12500 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 350000, revenueGrowthRate: 20, netIncomeCurrentYear: 94000, netIncomeGrowthRate: 25, peMultiple: 35, psMultiple: 9, epsCurrentYear: 7.52, epsGrowthRate: 25, grossMargin: 60, fcfCurrentYear: 72000, fcfGrowthRate: 25, fcfMultiple: 35, sharesOutstanding: 12500 },
    },
  },
  {
    id: nanoid(),
    ticker: 'META',
    name: 'Meta Platforms Inc.',
    industry: 'Communication Services',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 620,
      currentMarketCap: 1570000,
      currentRevenue: 164000,
      currentNetIncome: 62000,
      currentEPS: 23.86,
      currentPE: 26,
      currentPS: 9.6,
      currentFCF: 52000,
      valuationMethod: 'pe',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 164000, revenueGrowthRate: 12, netIncomeCurrentYear: 62000, netIncomeGrowthRate: 12, peMultiple: 20, psMultiple: 7, epsCurrentYear: 23.86, epsGrowthRate: 12, grossMargin: 80, fcfCurrentYear: 52000, fcfGrowthRate: 12, fcfMultiple: 20, sharesOutstanding: 2570 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 164000, revenueGrowthRate: 18, netIncomeCurrentYear: 62000, netIncomeGrowthRate: 22, peMultiple: 28, psMultiple: 10, epsCurrentYear: 23.86, epsGrowthRate: 22, grossMargin: 82, fcfCurrentYear: 52000, fcfGrowthRate: 22, fcfMultiple: 28, sharesOutstanding: 2570 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 164000, revenueGrowthRate: 28, netIncomeCurrentYear: 62000, netIncomeGrowthRate: 35, peMultiple: 38, psMultiple: 14, epsCurrentYear: 23.86, epsGrowthRate: 35, grossMargin: 84, fcfCurrentYear: 52000, fcfGrowthRate: 35, fcfMultiple: 38, sharesOutstanding: 2570 },
    },
  },
  {
    id: nanoid(),
    ticker: 'TSLA',
    name: 'Tesla Inc.',
    industry: 'Consumer Discretionary',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 350,
      currentMarketCap: 1120000,
      currentRevenue: 97000,
      currentNetIncome: 7100,
      currentEPS: 2.26,
      currentPE: 155,
      currentPS: 11.5,
      currentFCF: 3600,
      valuationMethod: 'ps',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 97000, revenueGrowthRate: 8, netIncomeCurrentYear: 7100, netIncomeGrowthRate: 10, peMultiple: 60, psMultiple: 8, epsCurrentYear: 2.26, epsGrowthRate: 10, grossMargin: 18, fcfCurrentYear: 3600, fcfGrowthRate: 10, fcfMultiple: 60, sharesOutstanding: 3200 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 97000, revenueGrowthRate: 20, netIncomeCurrentYear: 7100, netIncomeGrowthRate: 30, peMultiple: 100, psMultiple: 12, epsCurrentYear: 2.26, epsGrowthRate: 30, grossMargin: 22, fcfCurrentYear: 3600, fcfGrowthRate: 30, fcfMultiple: 80, sharesOutstanding: 3200 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 97000, revenueGrowthRate: 40, netIncomeCurrentYear: 7100, netIncomeGrowthRate: 60, peMultiple: 150, psMultiple: 18, epsCurrentYear: 2.26, epsGrowthRate: 60, grossMargin: 28, fcfCurrentYear: 3600, fcfGrowthRate: 60, fcfMultiple: 120, sharesOutstanding: 3200 },
    },
  },
  {
    id: nanoid(),
    ticker: 'JPM',
    name: 'JPMorgan Chase & Co.',
    industry: 'Financials',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 248,
      currentMarketCap: 710000,
      currentRevenue: 162000,
      currentNetIncome: 58000,
      currentEPS: 18.22,
      currentPE: 13.6,
      currentPS: 4.4,
      currentFCF: 45000,
      valuationMethod: 'pe',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 162000, revenueGrowthRate: 3, netIncomeCurrentYear: 58000, netIncomeGrowthRate: 3, peMultiple: 10, psMultiple: 3, epsCurrentYear: 18.22, epsGrowthRate: 3, grossMargin: 60, fcfCurrentYear: 45000, fcfGrowthRate: 3, fcfMultiple: 10, sharesOutstanding: 2900 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 162000, revenueGrowthRate: 7, netIncomeCurrentYear: 58000, netIncomeGrowthRate: 8, peMultiple: 14, psMultiple: 4.5, epsCurrentYear: 18.22, epsGrowthRate: 8, grossMargin: 62, fcfCurrentYear: 45000, fcfGrowthRate: 8, fcfMultiple: 14, sharesOutstanding: 2900 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 162000, revenueGrowthRate: 12, netIncomeCurrentYear: 58000, netIncomeGrowthRate: 15, peMultiple: 18, psMultiple: 6, epsCurrentYear: 18.22, epsGrowthRate: 15, grossMargin: 65, fcfCurrentYear: 45000, fcfGrowthRate: 15, fcfMultiple: 18, sharesOutstanding: 2900 },
    },
  },
  {
    id: nanoid(),
    ticker: 'BRK.B',
    name: 'Berkshire Hathaway',
    industry: 'Financials',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 475,
      currentMarketCap: 1040000,
      currentRevenue: 364000,
      currentNetIncome: 96000,
      currentEPS: 22.00,
      currentPE: 21.6,
      currentPS: 2.9,
      currentFCF: 40000,
      valuationMethod: 'pe',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 364000, revenueGrowthRate: 4, netIncomeCurrentYear: 96000, netIncomeGrowthRate: 5, peMultiple: 16, psMultiple: 2, epsCurrentYear: 22.00, epsGrowthRate: 5, grossMargin: 30, fcfCurrentYear: 40000, fcfGrowthRate: 5, fcfMultiple: 16, sharesOutstanding: 2190 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 364000, revenueGrowthRate: 8, netIncomeCurrentYear: 96000, netIncomeGrowthRate: 10, peMultiple: 22, psMultiple: 3, epsCurrentYear: 22.00, epsGrowthRate: 10, grossMargin: 32, fcfCurrentYear: 40000, fcfGrowthRate: 10, fcfMultiple: 22, sharesOutstanding: 2190 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 364000, revenueGrowthRate: 13, netIncomeCurrentYear: 96000, netIncomeGrowthRate: 16, peMultiple: 28, psMultiple: 4, epsCurrentYear: 22.00, epsGrowthRate: 16, grossMargin: 35, fcfCurrentYear: 40000, fcfGrowthRate: 16, fcfMultiple: 28, sharesOutstanding: 2190 },
    },
  },
  {
    id: nanoid(),
    ticker: 'LLY',
    name: 'Eli Lilly & Co.',
    industry: 'Healthcare',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 830,
      currentMarketCap: 790000,
      currentRevenue: 45000,
      currentNetIncome: 5800,
      currentEPS: 6.10,
      currentPE: 136,
      currentPS: 17.6,
      currentFCF: 4200,
      valuationMethod: 'ps',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 45000, revenueGrowthRate: 20, netIncomeCurrentYear: 5800, netIncomeGrowthRate: 25, peMultiple: 60, psMultiple: 12, epsCurrentYear: 6.10, epsGrowthRate: 25, grossMargin: 78, fcfCurrentYear: 4200, fcfGrowthRate: 25, fcfMultiple: 60, sharesOutstanding: 950 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 45000, revenueGrowthRate: 35, netIncomeCurrentYear: 5800, netIncomeGrowthRate: 45, peMultiple: 90, psMultiple: 18, epsCurrentYear: 6.10, epsGrowthRate: 45, grossMargin: 80, fcfCurrentYear: 4200, fcfGrowthRate: 45, fcfMultiple: 90, sharesOutstanding: 950 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 45000, revenueGrowthRate: 50, netIncomeCurrentYear: 5800, netIncomeGrowthRate: 65, peMultiple: 120, psMultiple: 25, epsCurrentYear: 6.10, epsGrowthRate: 65, grossMargin: 82, fcfCurrentYear: 4200, fcfGrowthRate: 65, fcfMultiple: 120, sharesOutstanding: 950 },
    },
  },
  {
    id: nanoid(),
    ticker: 'UNH',
    name: 'UnitedHealth Group',
    industry: 'Healthcare',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 490,
      currentMarketCap: 450000,
      currentRevenue: 371000,
      currentNetIncome: 22000,
      currentEPS: 23.86,
      currentPE: 20.5,
      currentPS: 1.2,
      currentFCF: 18000,
      valuationMethod: 'pe',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 371000, revenueGrowthRate: 5, netIncomeCurrentYear: 22000, netIncomeGrowthRate: 5, peMultiple: 16, psMultiple: 1, epsCurrentYear: 23.86, epsGrowthRate: 5, grossMargin: 22, fcfCurrentYear: 18000, fcfGrowthRate: 5, fcfMultiple: 16, sharesOutstanding: 920 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 371000, revenueGrowthRate: 10, netIncomeCurrentYear: 22000, netIncomeGrowthRate: 12, peMultiple: 22, psMultiple: 1.4, epsCurrentYear: 23.86, epsGrowthRate: 12, grossMargin: 24, fcfCurrentYear: 18000, fcfGrowthRate: 12, fcfMultiple: 22, sharesOutstanding: 920 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 371000, revenueGrowthRate: 15, netIncomeCurrentYear: 22000, netIncomeGrowthRate: 18, peMultiple: 28, psMultiple: 1.8, epsCurrentYear: 23.86, epsGrowthRate: 18, grossMargin: 26, fcfCurrentYear: 18000, fcfGrowthRate: 18, fcfMultiple: 28, sharesOutstanding: 920 },
    },
  },
  {
    id: nanoid(),
    ticker: 'XOM',
    name: 'Exxon Mobil Corp.',
    industry: 'Energy',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 112,
      currentMarketCap: 450000,
      currentRevenue: 398000,
      currentNetIncome: 36000,
      currentEPS: 8.89,
      currentPE: 12.6,
      currentPS: 1.1,
      currentFCF: 22000,
      valuationMethod: 'pe',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 398000, revenueGrowthRate: -3, netIncomeCurrentYear: 36000, netIncomeGrowthRate: -5, peMultiple: 9, psMultiple: 0.8, epsCurrentYear: 8.89, epsGrowthRate: -5, grossMargin: 28, fcfCurrentYear: 22000, fcfGrowthRate: -5, fcfMultiple: 9, sharesOutstanding: 4000 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 398000, revenueGrowthRate: 3, netIncomeCurrentYear: 36000, netIncomeGrowthRate: 5, peMultiple: 13, psMultiple: 1.2, epsCurrentYear: 8.89, epsGrowthRate: 5, grossMargin: 30, fcfCurrentYear: 22000, fcfGrowthRate: 5, fcfMultiple: 13, sharesOutstanding: 4000 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 398000, revenueGrowthRate: 8, netIncomeCurrentYear: 36000, netIncomeGrowthRate: 12, peMultiple: 16, psMultiple: 1.6, epsCurrentYear: 8.89, epsGrowthRate: 12, grossMargin: 33, fcfCurrentYear: 22000, fcfGrowthRate: 12, fcfMultiple: 16, sharesOutstanding: 4000 },
    },
  },
  {
    id: nanoid(),
    ticker: 'BTC',
    name: 'Bitcoin (via ETF)',
    industry: 'Crypto',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 95000,
      currentMarketCap: 1880000,
      currentRevenue: 0,
      currentNetIncome: 0,
      currentEPS: 0,
      currentPE: 0,
      currentPS: 0,
      currentFCF: 0,
      valuationMethod: 'price',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 0, revenueGrowthRate: 0, netIncomeCurrentYear: 0, netIncomeGrowthRate: 0, peMultiple: 0, psMultiple: 0, epsCurrentYear: 0, epsGrowthRate: 0, grossMargin: 0, fcfCurrentYear: 0, fcfGrowthRate: 0, fcfMultiple: 0, sharesOutstanding: 19700000, targetPriceOverride: 50000 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 0, revenueGrowthRate: 0, netIncomeCurrentYear: 0, netIncomeGrowthRate: 0, peMultiple: 0, psMultiple: 0, epsCurrentYear: 0, epsGrowthRate: 0, grossMargin: 0, fcfCurrentYear: 0, fcfGrowthRate: 0, fcfMultiple: 0, sharesOutstanding: 19700000, targetPriceOverride: 200000 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 0, revenueGrowthRate: 0, netIncomeCurrentYear: 0, netIncomeGrowthRate: 0, peMultiple: 0, psMultiple: 0, epsCurrentYear: 0, epsGrowthRate: 0, grossMargin: 0, fcfCurrentYear: 0, fcfGrowthRate: 0, fcfMultiple: 0, sharesOutstanding: 19700000, targetPriceOverride: 500000 },
    },
  },
  {
    id: nanoid(),
    ticker: 'SPY',
    name: 'SPDR S&P 500 ETF',
    industry: 'ETF',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 580,
      currentMarketCap: 560000,
      currentRevenue: 0,
      currentNetIncome: 0,
      currentEPS: 0,
      currentPE: 22,
      currentPS: 0,
      currentFCF: 0,
      valuationMethod: 'price',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 0, revenueGrowthRate: 0, netIncomeCurrentYear: 0, netIncomeGrowthRate: 0, peMultiple: 0, psMultiple: 0, epsCurrentYear: 0, epsGrowthRate: 0, grossMargin: 0, fcfCurrentYear: 0, fcfGrowthRate: 0, fcfMultiple: 0, sharesOutstanding: 960000, targetPriceOverride: 450 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 0, revenueGrowthRate: 0, netIncomeCurrentYear: 0, netIncomeGrowthRate: 0, peMultiple: 0, psMultiple: 0, epsCurrentYear: 0, epsGrowthRate: 0, grossMargin: 0, fcfCurrentYear: 0, fcfGrowthRate: 0, fcfMultiple: 0, sharesOutstanding: 960000, targetPriceOverride: 700 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 0, revenueGrowthRate: 0, netIncomeCurrentYear: 0, netIncomeGrowthRate: 0, peMultiple: 0, psMultiple: 0, epsCurrentYear: 0, epsGrowthRate: 0, grossMargin: 0, fcfCurrentYear: 0, fcfGrowthRate: 0, fcfMultiple: 0, sharesOutstanding: 960000, targetPriceOverride: 900 },
    },
  },
  {
    id: nanoid(),
    ticker: 'PLTR',
    name: 'Palantir Technologies',
    industry: 'Technology',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 115,
      currentMarketCap: 250000,
      currentRevenue: 2900,
      currentNetIncome: 460,
      currentEPS: 0.20,
      currentPE: 575,
      currentPS: 86,
      currentFCF: 500,
      valuationMethod: 'ps',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 2900, revenueGrowthRate: 20, netIncomeCurrentYear: 460, netIncomeGrowthRate: 25, peMultiple: 80, psMultiple: 30, epsCurrentYear: 0.20, epsGrowthRate: 25, grossMargin: 80, fcfCurrentYear: 500, fcfGrowthRate: 25, fcfMultiple: 80, sharesOutstanding: 2170 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 2900, revenueGrowthRate: 35, netIncomeCurrentYear: 460, netIncomeGrowthRate: 50, peMultiple: 120, psMultiple: 55, epsCurrentYear: 0.20, epsGrowthRate: 50, grossMargin: 82, fcfCurrentYear: 500, fcfGrowthRate: 50, fcfMultiple: 120, sharesOutstanding: 2170 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 2900, revenueGrowthRate: 55, netIncomeCurrentYear: 460, netIncomeGrowthRate: 80, peMultiple: 200, psMultiple: 80, epsCurrentYear: 0.20, epsGrowthRate: 80, grossMargin: 85, fcfCurrentYear: 500, fcfGrowthRate: 80, fcfMultiple: 200, sharesOutstanding: 2170 },
    },
  },
  {
    id: nanoid(),
    ticker: 'SHOP',
    name: 'Shopify Inc.',
    industry: 'Technology',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 120,
      currentMarketCap: 150000,
      currentRevenue: 8900,
      currentNetIncome: 1400,
      currentEPS: 1.10,
      currentPE: 109,
      currentPS: 16.9,
      currentFCF: 1200,
      valuationMethod: 'ps',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 8900, revenueGrowthRate: 18, netIncomeCurrentYear: 1400, netIncomeGrowthRate: 20, peMultiple: 50, psMultiple: 10, epsCurrentYear: 1.10, epsGrowthRate: 20, grossMargin: 51, fcfCurrentYear: 1200, fcfGrowthRate: 20, fcfMultiple: 50, sharesOutstanding: 1260 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 8900, revenueGrowthRate: 28, netIncomeCurrentYear: 1400, netIncomeGrowthRate: 35, peMultiple: 80, psMultiple: 18, epsCurrentYear: 1.10, epsGrowthRate: 35, grossMargin: 53, fcfCurrentYear: 1200, fcfGrowthRate: 35, fcfMultiple: 80, sharesOutstanding: 1260 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 8900, revenueGrowthRate: 40, netIncomeCurrentYear: 1400, netIncomeGrowthRate: 55, peMultiple: 120, psMultiple: 28, epsCurrentYear: 1.10, epsGrowthRate: 55, grossMargin: 56, fcfCurrentYear: 1200, fcfGrowthRate: 55, fcfMultiple: 120, sharesOutstanding: 1260 },
    },
  },
];
