// Portfolio Planner — Sample Stock Data
import { nanoid } from 'nanoid';
import type { Stock } from './types';
import { DEFAULT_PROJECTIONS } from './types';

export { DEFAULT_PROJECTIONS };

export const SAMPLE_STOCKS: Stock[] = [
  {
    id: nanoid(),
    ticker: 'AAPL',
    name: 'Apple Inc.',
    industry: 'Technology',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 227,
      currentMarketCap: 3500000,
      currentRevenue: 391000,
      currentNetIncome: 94000,
      currentEPS: 6.11,
      currentPE: 37,
      currentPS: 9,
      currentFCF: 108000,
      valuationMethod: 'pe',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 391000, revenueGrowthRate: 4, netIncomeCurrentYear: 94000, netIncomeGrowthRate: 4, peMultiple: 25, psMultiple: 7, epsCurrentYear: 6.11, epsGrowthRate: 4, grossMargin: 45, fcfCurrentYear: 108000, fcfGrowthRate: 4, fcfMultiple: 25, sharesOutstanding: 15400 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 391000, revenueGrowthRate: 8, netIncomeCurrentYear: 94000, netIncomeGrowthRate: 10, peMultiple: 32, psMultiple: 9, epsCurrentYear: 6.11, epsGrowthRate: 10, grossMargin: 46, fcfCurrentYear: 108000, fcfGrowthRate: 10, fcfMultiple: 30, sharesOutstanding: 15400 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 391000, revenueGrowthRate: 14, netIncomeCurrentYear: 94000, netIncomeGrowthRate: 18, peMultiple: 40, psMultiple: 12, epsCurrentYear: 6.11, epsGrowthRate: 18, grossMargin: 48, fcfCurrentYear: 108000, fcfGrowthRate: 18, fcfMultiple: 40, sharesOutstanding: 15400 },
    },
  },
  {
    id: nanoid(),
    ticker: 'MSFT',
    name: 'Microsoft Corp.',
    industry: 'Technology',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 415,
      currentMarketCap: 3080000,
      currentRevenue: 245000,
      currentNetIncome: 88000,
      currentEPS: 11.80,
      currentPE: 35,
      currentPS: 12.5,
      currentFCF: 75000,
      valuationMethod: 'pe',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 245000, revenueGrowthRate: 10, netIncomeCurrentYear: 88000, netIncomeGrowthRate: 10, peMultiple: 28, psMultiple: 10, epsCurrentYear: 11.80, epsGrowthRate: 10, grossMargin: 69, fcfCurrentYear: 75000, fcfGrowthRate: 10, fcfMultiple: 28, sharesOutstanding: 7430 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 245000, revenueGrowthRate: 16, netIncomeCurrentYear: 88000, netIncomeGrowthRate: 18, peMultiple: 35, psMultiple: 13, epsCurrentYear: 11.80, epsGrowthRate: 18, grossMargin: 71, fcfCurrentYear: 75000, fcfGrowthRate: 18, fcfMultiple: 35, sharesOutstanding: 7430 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 245000, revenueGrowthRate: 22, netIncomeCurrentYear: 88000, netIncomeGrowthRate: 25, peMultiple: 45, psMultiple: 16, epsCurrentYear: 11.80, epsGrowthRate: 25, grossMargin: 73, fcfCurrentYear: 75000, fcfGrowthRate: 25, fcfMultiple: 45, sharesOutstanding: 7430 },
    },
  },
  {
    id: nanoid(),
    ticker: 'NVDA',
    name: 'NVIDIA Corp.',
    industry: 'Technology',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 875,
      currentMarketCap: 2150000,
      currentRevenue: 130000,
      currentNetIncome: 72000,
      currentEPS: 2.94,
      currentPE: 55,
      currentPS: 25,
      currentFCF: 60000,
      valuationMethod: 'pe',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 130000, revenueGrowthRate: 20, netIncomeCurrentYear: 72000, netIncomeGrowthRate: 20, peMultiple: 35, psMultiple: 15, epsCurrentYear: 2.94, epsGrowthRate: 20, grossMargin: 74, fcfCurrentYear: 60000, fcfGrowthRate: 20, fcfMultiple: 35, sharesOutstanding: 24400 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 130000, revenueGrowthRate: 40, netIncomeCurrentYear: 72000, netIncomeGrowthRate: 45, peMultiple: 50, psMultiple: 22, epsCurrentYear: 2.94, epsGrowthRate: 45, grossMargin: 76, fcfCurrentYear: 60000, fcfGrowthRate: 45, fcfMultiple: 50, sharesOutstanding: 24400 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 130000, revenueGrowthRate: 65, netIncomeCurrentYear: 72000, netIncomeGrowthRate: 70, peMultiple: 70, psMultiple: 30, epsCurrentYear: 2.94, epsGrowthRate: 70, grossMargin: 78, fcfCurrentYear: 60000, fcfGrowthRate: 70, fcfMultiple: 70, sharesOutstanding: 24400 },
    },
  },
  {
    id: nanoid(),
    ticker: 'AMZN',
    name: 'Amazon.com Inc.',
    industry: 'Consumer Discretionary',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 220,
      currentMarketCap: 2300000,
      currentRevenue: 620000,
      currentNetIncome: 59000,
      currentEPS: 5.53,
      currentPE: 40,
      currentPS: 3.7,
      currentFCF: 50000,
      valuationMethod: 'pe',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 620000, revenueGrowthRate: 8, netIncomeCurrentYear: 59000, netIncomeGrowthRate: 10, peMultiple: 28, psMultiple: 3, epsCurrentYear: 5.53, epsGrowthRate: 10, grossMargin: 47, fcfCurrentYear: 50000, fcfGrowthRate: 10, fcfMultiple: 28, sharesOutstanding: 10500 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 620000, revenueGrowthRate: 14, netIncomeCurrentYear: 59000, netIncomeGrowthRate: 20, peMultiple: 38, psMultiple: 4, epsCurrentYear: 5.53, epsGrowthRate: 20, grossMargin: 49, fcfCurrentYear: 50000, fcfGrowthRate: 20, fcfMultiple: 38, sharesOutstanding: 10500 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 620000, revenueGrowthRate: 20, netIncomeCurrentYear: 59000, netIncomeGrowthRate: 35, peMultiple: 50, psMultiple: 5.5, epsCurrentYear: 5.53, epsGrowthRate: 35, grossMargin: 52, fcfCurrentYear: 50000, fcfGrowthRate: 35, fcfMultiple: 50, sharesOutstanding: 10500 },
    },
  },
  {
    id: nanoid(),
    ticker: 'GOOGL',
    name: 'Alphabet Inc.',
    industry: 'Communication Services',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 195,
      currentMarketCap: 2400000,
      currentRevenue: 350000,
      currentNetIncome: 94000,
      currentEPS: 7.52,
      currentPE: 26,
      currentPS: 6.9,
      currentFCF: 72000,
      valuationMethod: 'pe',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 350000, revenueGrowthRate: 8, netIncomeCurrentYear: 94000, netIncomeGrowthRate: 8, peMultiple: 20, psMultiple: 5, epsCurrentYear: 7.52, epsGrowthRate: 8, grossMargin: 56, fcfCurrentYear: 72000, fcfGrowthRate: 8, fcfMultiple: 20, sharesOutstanding: 12500 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 350000, revenueGrowthRate: 13, netIncomeCurrentYear: 94000, netIncomeGrowthRate: 15, peMultiple: 26, psMultiple: 7, epsCurrentYear: 7.52, epsGrowthRate: 15, grossMargin: 58, fcfCurrentYear: 72000, fcfGrowthRate: 15, fcfMultiple: 26, sharesOutstanding: 12500 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 350000, revenueGrowthRate: 20, netIncomeCurrentYear: 94000, netIncomeGrowthRate: 25, peMultiple: 35, psMultiple: 9, epsCurrentYear: 7.52, epsGrowthRate: 25, grossMargin: 60, fcfCurrentYear: 72000, fcfGrowthRate: 25, fcfMultiple: 35, sharesOutstanding: 12500 },
    },
  },
  {
    id: nanoid(),
    ticker: 'META',
    name: 'Meta Platforms Inc.',
    industry: 'Communication Services',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 620,
      currentMarketCap: 1570000,
      currentRevenue: 164000,
      currentNetIncome: 62000,
      currentEPS: 23.86,
      currentPE: 26,
      currentPS: 9.6,
      currentFCF: 52000,
      valuationMethod: 'pe',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 164000, revenueGrowthRate: 12, netIncomeCurrentYear: 62000, netIncomeGrowthRate: 12, peMultiple: 20, psMultiple: 7, epsCurrentYear: 23.86, epsGrowthRate: 12, grossMargin: 80, fcfCurrentYear: 52000, fcfGrowthRate: 12, fcfMultiple: 20, sharesOutstanding: 2570 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 164000, revenueGrowthRate: 18, netIncomeCurrentYear: 62000, netIncomeGrowthRate: 22, peMultiple: 28, psMultiple: 10, epsCurrentYear: 23.86, epsGrowthRate: 22, grossMargin: 82, fcfCurrentYear: 52000, fcfGrowthRate: 22, fcfMultiple: 28, sharesOutstanding: 2570 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 164000, revenueGrowthRate: 28, netIncomeCurrentYear: 62000, netIncomeGrowthRate: 35, peMultiple: 38, psMultiple: 14, epsCurrentYear: 23.86, epsGrowthRate: 35, grossMargin: 84, fcfCurrentYear: 52000, fcfGrowthRate: 35, fcfMultiple: 38, sharesOutstanding: 2570 },
    },
  },
  {
    id: nanoid(),
    ticker: 'TSLA',
    name: 'Tesla Inc.',
    industry: 'Consumer Discretionary',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 350,
      currentMarketCap: 1120000,
      currentRevenue: 97000,
      currentNetIncome: 7100,
      currentEPS: 2.26,
      currentPE: 155,
      currentPS: 11.5,
      currentFCF: 3600,
      valuationMethod: 'ps',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 97000, revenueGrowthRate: 8, netIncomeCurrentYear: 7100, netIncomeGrowthRate: 10, peMultiple: 60, psMultiple: 8, epsCurrentYear: 2.26, epsGrowthRate: 10, grossMargin: 18, fcfCurrentYear: 3600, fcfGrowthRate: 10, fcfMultiple: 60, sharesOutstanding: 3200 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 97000, revenueGrowthRate: 20, netIncomeCurrentYear: 7100, netIncomeGrowthRate: 30, peMultiple: 100, psMultiple: 12, epsCurrentYear: 2.26, epsGrowthRate: 30, grossMargin: 22, fcfCurrentYear: 3600, fcfGrowthRate: 30, fcfMultiple: 80, sharesOutstanding: 3200 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 97000, revenueGrowthRate: 40, netIncomeCurrentYear: 7100, netIncomeGrowthRate: 60, peMultiple: 150, psMultiple: 18, epsCurrentYear: 2.26, epsGrowthRate: 60, grossMargin: 28, fcfCurrentYear: 3600, fcfGrowthRate: 60, fcfMultiple: 120, sharesOutstanding: 3200 },
    },
  },
  {
    id: nanoid(),
    ticker: 'JPM',
    name: 'JPMorgan Chase & Co.',
    industry: 'Financials',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 248,
      currentMarketCap: 710000,
      currentRevenue: 162000,
      currentNetIncome: 58000,
      currentEPS: 18.22,
      currentPE: 13.6,
      currentPS: 4.4,
      currentFCF: 45000,
      valuationMethod: 'pe',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 162000, revenueGrowthRate: 3, netIncomeCurrentYear: 58000, netIncomeGrowthRate: 3, peMultiple: 10, psMultiple: 3, epsCurrentYear: 18.22, epsGrowthRate: 3, grossMargin: 60, fcfCurrentYear: 45000, fcfGrowthRate: 3, fcfMultiple: 10, sharesOutstanding: 2900 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 162000, revenueGrowthRate: 7, netIncomeCurrentYear: 58000, netIncomeGrowthRate: 8, peMultiple: 14, psMultiple: 4.5, epsCurrentYear: 18.22, epsGrowthRate: 8, grossMargin: 62, fcfCurrentYear: 45000, fcfGrowthRate: 8, fcfMultiple: 14, sharesOutstanding: 2900 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 162000, revenueGrowthRate: 12, netIncomeCurrentYear: 58000, netIncomeGrowthRate: 15, peMultiple: 18, psMultiple: 6, epsCurrentYear: 18.22, epsGrowthRate: 15, grossMargin: 65, fcfCurrentYear: 45000, fcfGrowthRate: 15, fcfMultiple: 18, sharesOutstanding: 2900 },
    },
  },
  {
    id: nanoid(),
    ticker: 'BRK.B',
    name: 'Berkshire Hathaway',
    industry: 'Financials',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 475,
      currentMarketCap: 1040000,
      currentRevenue: 364000,
      currentNetIncome: 96000,
      currentEPS: 22.00,
      currentPE: 21.6,
      currentPS: 2.9,
      currentFCF: 40000,
      valuationMethod: 'pe',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 364000, revenueGrowthRate: 4, netIncomeCurrentYear: 96000, netIncomeGrowthRate: 5, peMultiple: 16, psMultiple: 2, epsCurrentYear: 22.00, epsGrowthRate: 5, grossMargin: 30, fcfCurrentYear: 40000, fcfGrowthRate: 5, fcfMultiple: 16, sharesOutstanding: 2190 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 364000, revenueGrowthRate: 8, netIncomeCurrentYear: 96000, netIncomeGrowthRate: 10, peMultiple: 22, psMultiple: 3, epsCurrentYear: 22.00, epsGrowthRate: 10, grossMargin: 32, fcfCurrentYear: 40000, fcfGrowthRate: 10, fcfMultiple: 22, sharesOutstanding: 2190 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 364000, revenueGrowthRate: 13, netIncomeCurrentYear: 96000, netIncomeGrowthRate: 16, peMultiple: 28, psMultiple: 4, epsCurrentYear: 22.00, epsGrowthRate: 16, grossMargin: 35, fcfCurrentYear: 40000, fcfGrowthRate: 16, fcfMultiple: 28, sharesOutstanding: 2190 },
    },
  },
  {
    id: nanoid(),
    ticker: 'LLY',
    name: 'Eli Lilly & Co.',
    industry: 'Healthcare',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 830,
      currentMarketCap: 790000,
      currentRevenue: 45000,
      currentNetIncome: 5800,
      currentEPS: 6.10,
      currentPE: 136,
      currentPS: 17.6,
      currentFCF: 4200,
      valuationMethod: 'ps',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 45000, revenueGrowthRate: 20, netIncomeCurrentYear: 5800, netIncomeGrowthRate: 25, peMultiple: 60, psMultiple: 12, epsCurrentYear: 6.10, epsGrowthRate: 25, grossMargin: 78, fcfCurrentYear: 4200, fcfGrowthRate: 25, fcfMultiple: 60, sharesOutstanding: 950 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 45000, revenueGrowthRate: 35, netIncomeCurrentYear: 5800, netIncomeGrowthRate: 45, peMultiple: 90, psMultiple: 18, epsCurrentYear: 6.10, epsGrowthRate: 45, grossMargin: 80, fcfCurrentYear: 4200, fcfGrowthRate: 45, fcfMultiple: 90, sharesOutstanding: 950 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 45000, revenueGrowthRate: 50, netIncomeCurrentYear: 5800, netIncomeGrowthRate: 65, peMultiple: 120, psMultiple: 25, epsCurrentYear: 6.10, epsGrowthRate: 65, grossMargin: 82, fcfCurrentYear: 4200, fcfGrowthRate: 65, fcfMultiple: 120, sharesOutstanding: 950 },
    },
  },
  {
    id: nanoid(),
    ticker: 'UNH',
    name: 'UnitedHealth Group',
    industry: 'Healthcare',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 490,
      currentMarketCap: 450000,
      currentRevenue: 371000,
      currentNetIncome: 22000,
      currentEPS: 23.86,
      currentPE: 20.5,
      currentPS: 1.2,
      currentFCF: 18000,
      valuationMethod: 'pe',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 371000, revenueGrowthRate: 5, netIncomeCurrentYear: 22000, netIncomeGrowthRate: 5, peMultiple: 16, psMultiple: 1, epsCurrentYear: 23.86, epsGrowthRate: 5, grossMargin: 22, fcfCurrentYear: 18000, fcfGrowthRate: 5, fcfMultiple: 16, sharesOutstanding: 920 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 371000, revenueGrowthRate: 10, netIncomeCurrentYear: 22000, netIncomeGrowthRate: 12, peMultiple: 22, psMultiple: 1.4, epsCurrentYear: 23.86, epsGrowthRate: 12, grossMargin: 24, fcfCurrentYear: 18000, fcfGrowthRate: 12, fcfMultiple: 22, sharesOutstanding: 920 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 371000, revenueGrowthRate: 15, netIncomeCurrentYear: 22000, netIncomeGrowthRate: 18, peMultiple: 28, psMultiple: 1.8, epsCurrentYear: 23.86, epsGrowthRate: 18, grossMargin: 26, fcfCurrentYear: 18000, fcfGrowthRate: 18, fcfMultiple: 28, sharesOutstanding: 920 },
    },
  },
  {
    id: nanoid(),
    ticker: 'XOM',
    name: 'Exxon Mobil Corp.',
    industry: 'Energy',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 112,
      currentMarketCap: 450000,
      currentRevenue: 398000,
      currentNetIncome: 36000,
      currentEPS: 8.89,
      currentPE: 12.6,
      currentPS: 1.1,
      currentFCF: 22000,
      valuationMethod: 'pe',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 398000, revenueGrowthRate: -3, netIncomeCurrentYear: 36000, netIncomeGrowthRate: -5, peMultiple: 9, psMultiple: 0.8, epsCurrentYear: 8.89, epsGrowthRate: -5, grossMargin: 28, fcfCurrentYear: 22000, fcfGrowthRate: -5, fcfMultiple: 9, sharesOutstanding: 4000 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 398000, revenueGrowthRate: 3, netIncomeCurrentYear: 36000, netIncomeGrowthRate: 5, peMultiple: 13, psMultiple: 1.2, epsCurrentYear: 8.89, epsGrowthRate: 5, grossMargin: 30, fcfCurrentYear: 22000, fcfGrowthRate: 5, fcfMultiple: 13, sharesOutstanding: 4000 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 398000, revenueGrowthRate: 8, netIncomeCurrentYear: 36000, netIncomeGrowthRate: 12, peMultiple: 16, psMultiple: 1.6, epsCurrentYear: 8.89, epsGrowthRate: 12, grossMargin: 33, fcfCurrentYear: 22000, fcfGrowthRate: 12, fcfMultiple: 16, sharesOutstanding: 4000 },
    },
  },
  {
    id: nanoid(),
    ticker: 'BTC',
    name: 'Bitcoin (via ETF)',
    industry: 'Crypto',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 95000,
      currentMarketCap: 1880000,
      currentRevenue: 0,
      currentNetIncome: 0,
      currentEPS: 0,
      currentPE: 0,
      currentPS: 0,
      currentFCF: 0,
      valuationMethod: 'price',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 0, revenueGrowthRate: 0, netIncomeCurrentYear: 0, netIncomeGrowthRate: 0, peMultiple: 0, psMultiple: 0, epsCurrentYear: 0, epsGrowthRate: 0, grossMargin: 0, fcfCurrentYear: 0, fcfGrowthRate: 0, fcfMultiple: 0, sharesOutstanding: 19700000, targetPriceOverride: 50000 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 0, revenueGrowthRate: 0, netIncomeCurrentYear: 0, netIncomeGrowthRate: 0, peMultiple: 0, psMultiple: 0, epsCurrentYear: 0, epsGrowthRate: 0, grossMargin: 0, fcfCurrentYear: 0, fcfGrowthRate: 0, fcfMultiple: 0, sharesOutstanding: 19700000, targetPriceOverride: 200000 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 0, revenueGrowthRate: 0, netIncomeCurrentYear: 0, netIncomeGrowthRate: 0, peMultiple: 0, psMultiple: 0, epsCurrentYear: 0, epsGrowthRate: 0, grossMargin: 0, fcfCurrentYear: 0, fcfGrowthRate: 0, fcfMultiple: 0, sharesOutstanding: 19700000, targetPriceOverride: 500000 },
    },
  },
  {
    id: nanoid(),
    ticker: 'SPY',
    name: 'SPDR S&P 500 ETF',
    industry: 'ETF',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 580,
      currentMarketCap: 560000,
      currentRevenue: 0,
      currentNetIncome: 0,
      currentEPS: 0,
      currentPE: 22,
      currentPS: 0,
      currentFCF: 0,
      valuationMethod: 'price',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 0, revenueGrowthRate: 0, netIncomeCurrentYear: 0, netIncomeGrowthRate: 0, peMultiple: 0, psMultiple: 0, epsCurrentYear: 0, epsGrowthRate: 0, grossMargin: 0, fcfCurrentYear: 0, fcfGrowthRate: 0, fcfMultiple: 0, sharesOutstanding: 960000, targetPriceOverride: 450 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 0, revenueGrowthRate: 0, netIncomeCurrentYear: 0, netIncomeGrowthRate: 0, peMultiple: 0, psMultiple: 0, epsCurrentYear: 0, epsGrowthRate: 0, grossMargin: 0, fcfCurrentYear: 0, fcfGrowthRate: 0, fcfMultiple: 0, sharesOutstanding: 960000, targetPriceOverride: 700 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 0, revenueGrowthRate: 0, netIncomeCurrentYear: 0, netIncomeGrowthRate: 0, peMultiple: 0, psMultiple: 0, epsCurrentYear: 0, epsGrowthRate: 0, grossMargin: 0, fcfCurrentYear: 0, fcfGrowthRate: 0, fcfMultiple: 0, sharesOutstanding: 960000, targetPriceOverride: 900 },
    },
  },
  {
    id: nanoid(),
    ticker: 'PLTR',
    name: 'Palantir Technologies',
    industry: 'Technology',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 115,
      currentMarketCap: 250000,
      currentRevenue: 2900,
      currentNetIncome: 460,
      currentEPS: 0.20,
      currentPE: 575,
      currentPS: 86,
      currentFCF: 500,
      valuationMethod: 'ps',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 2900, revenueGrowthRate: 20, netIncomeCurrentYear: 460, netIncomeGrowthRate: 25, peMultiple: 80, psMultiple: 30, epsCurrentYear: 0.20, epsGrowthRate: 25, grossMargin: 80, fcfCurrentYear: 500, fcfGrowthRate: 25, fcfMultiple: 80, sharesOutstanding: 2170 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 2900, revenueGrowthRate: 35, netIncomeCurrentYear: 460, netIncomeGrowthRate: 50, peMultiple: 120, psMultiple: 55, epsCurrentYear: 0.20, epsGrowthRate: 50, grossMargin: 82, fcfCurrentYear: 500, fcfGrowthRate: 50, fcfMultiple: 120, sharesOutstanding: 2170 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 2900, revenueGrowthRate: 55, netIncomeCurrentYear: 460, netIncomeGrowthRate: 80, peMultiple: 200, psMultiple: 80, epsCurrentYear: 0.20, epsGrowthRate: 80, grossMargin: 85, fcfCurrentYear: 500, fcfGrowthRate: 80, fcfMultiple: 200, sharesOutstanding: 2170 },
    },
  },
  {
    id: nanoid(),
    ticker: 'SHOP',
    name: 'Shopify Inc.',
    industry: 'Technology',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 120,
      currentMarketCap: 150000,
      currentRevenue: 8900,
      currentNetIncome: 1400,
      currentEPS: 1.10,
      currentPE: 109,
      currentPS: 16.9,
      currentFCF: 1200,
      valuationMethod: 'ps',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 8900, revenueGrowthRate: 18, netIncomeCurrentYear: 1400, netIncomeGrowthRate: 20, peMultiple: 50, psMultiple: 10, epsCurrentYear: 1.10, epsGrowthRate: 20, grossMargin: 51, fcfCurrentYear: 1200, fcfGrowthRate: 20, fcfMultiple: 50, sharesOutstanding: 1260 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 8900, revenueGrowthRate: 28, netIncomeCurrentYear: 1400, netIncomeGrowthRate: 35, peMultiple: 80, psMultiple: 18, epsCurrentYear: 1.10, epsGrowthRate: 35, grossMargin: 53, fcfCurrentYear: 1200, fcfGrowthRate: 35, fcfMultiple: 80, sharesOutstanding: 1260 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 8900, revenueGrowthRate: 40, netIncomeCurrentYear: 1400, netIncomeGrowthRate: 55, peMultiple: 120, psMultiple: 28, epsCurrentYear: 1.10, epsGrowthRate: 55, grossMargin: 56, fcfCurrentYear: 1200, fcfGrowthRate: 55, fcfMultiple: 120, sharesOutstanding: 1260 },
    },
  },
  // ── Additional Stocks ────────────────────────────────────────────────────
  {
    id: nanoid(),
    ticker: 'AMD',
    name: 'Advanced Micro Devices',
    industry: 'Technology',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 130,
      currentMarketCap: 210000,
      currentRevenue: 22700,
      currentNetIncome: 1600,
      currentEPS: 0.99,
      currentPE: 131,
      currentPS: 9.3,
      currentFCF: 1900,
      valuationMethod: 'ps',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 22700, revenueGrowthRate: 12, netIncomeCurrentYear: 1600, netIncomeGrowthRate: 20, peMultiple: 40, psMultiple: 6, epsCurrentYear: 0.99, epsGrowthRate: 20, grossMargin: 50, fcfCurrentYear: 1900, fcfGrowthRate: 20, fcfMultiple: 40, sharesOutstanding: 1620 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 22700, revenueGrowthRate: 28, netIncomeCurrentYear: 1600, netIncomeGrowthRate: 50, peMultiple: 70, psMultiple: 12, epsCurrentYear: 0.99, epsGrowthRate: 50, grossMargin: 53, fcfCurrentYear: 1900, fcfGrowthRate: 50, fcfMultiple: 70, sharesOutstanding: 1620 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 22700, revenueGrowthRate: 45, netIncomeCurrentYear: 1600, netIncomeGrowthRate: 80, peMultiple: 110, psMultiple: 20, epsCurrentYear: 0.99, epsGrowthRate: 80, grossMargin: 57, fcfCurrentYear: 1900, fcfGrowthRate: 80, fcfMultiple: 110, sharesOutstanding: 1620 },
    },
  },
  {
    id: nanoid(),
    ticker: 'INTC',
    name: 'Intel Corporation',
    industry: 'Technology',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 22,
      currentMarketCap: 95000,
      currentRevenue: 53100,
      currentNetIncome: -1600,
      currentEPS: -0.38,
      currentPE: 0,
      currentPS: 1.8,
      currentFCF: -15000,
      valuationMethod: 'ps',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 53100, revenueGrowthRate: -5, netIncomeCurrentYear: -1600, netIncomeGrowthRate: 0, peMultiple: 15, psMultiple: 1.2, epsCurrentYear: -0.38, epsGrowthRate: 0, grossMargin: 40, fcfCurrentYear: -15000, fcfGrowthRate: 0, fcfMultiple: 15, sharesOutstanding: 4340 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 53100, revenueGrowthRate: 5, netIncomeCurrentYear: -1600, netIncomeGrowthRate: 100, peMultiple: 20, psMultiple: 2.5, epsCurrentYear: -0.38, epsGrowthRate: 100, grossMargin: 45, fcfCurrentYear: -15000, fcfGrowthRate: 100, fcfMultiple: 20, sharesOutstanding: 4340 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 53100, revenueGrowthRate: 15, netIncomeCurrentYear: -1600, netIncomeGrowthRate: 200, peMultiple: 28, psMultiple: 4, epsCurrentYear: -0.38, epsGrowthRate: 200, grossMargin: 52, fcfCurrentYear: -15000, fcfGrowthRate: 200, fcfMultiple: 28, sharesOutstanding: 4340 },
    },
  },
  {
    id: nanoid(),
    ticker: 'QCOM',
    name: 'Qualcomm Inc.',
    industry: 'Technology',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 155,
      currentMarketCap: 172000,
      currentRevenue: 38960,
      currentNetIncome: 10140,
      currentEPS: 9.17,
      currentPE: 16.9,
      currentPS: 4.4,
      currentFCF: 9800,
      valuationMethod: 'pe',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 38960, revenueGrowthRate: 5, netIncomeCurrentYear: 10140, netIncomeGrowthRate: 5, peMultiple: 13, psMultiple: 3, epsCurrentYear: 9.17, epsGrowthRate: 5, grossMargin: 55, fcfCurrentYear: 9800, fcfGrowthRate: 5, fcfMultiple: 13, sharesOutstanding: 1110 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 38960, revenueGrowthRate: 12, netIncomeCurrentYear: 10140, netIncomeGrowthRate: 14, peMultiple: 18, psMultiple: 5, epsCurrentYear: 9.17, epsGrowthRate: 14, grossMargin: 57, fcfCurrentYear: 9800, fcfGrowthRate: 14, fcfMultiple: 18, sharesOutstanding: 1110 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 38960, revenueGrowthRate: 22, netIncomeCurrentYear: 10140, netIncomeGrowthRate: 25, peMultiple: 25, psMultiple: 7, epsCurrentYear: 9.17, epsGrowthRate: 25, grossMargin: 60, fcfCurrentYear: 9800, fcfGrowthRate: 25, fcfMultiple: 25, sharesOutstanding: 1110 },
    },
  },
  {
    id: nanoid(),
    ticker: 'CRM',
    name: 'Salesforce Inc.',
    industry: 'Technology',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 310,
      currentMarketCap: 298000,
      currentRevenue: 34900,
      currentNetIncome: 4800,
      currentEPS: 4.92,
      currentPE: 63,
      currentPS: 8.5,
      currentFCF: 10000,
      valuationMethod: 'ps',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 34900, revenueGrowthRate: 8, netIncomeCurrentYear: 4800, netIncomeGrowthRate: 10, peMultiple: 30, psMultiple: 6, epsCurrentYear: 4.92, epsGrowthRate: 10, grossMargin: 76, fcfCurrentYear: 10000, fcfGrowthRate: 10, fcfMultiple: 30, sharesOutstanding: 960 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 34900, revenueGrowthRate: 14, netIncomeCurrentYear: 4800, netIncomeGrowthRate: 20, peMultiple: 45, psMultiple: 9, epsCurrentYear: 4.92, epsGrowthRate: 20, grossMargin: 78, fcfCurrentYear: 10000, fcfGrowthRate: 20, fcfMultiple: 45, sharesOutstanding: 960 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 34900, revenueGrowthRate: 22, netIncomeCurrentYear: 4800, netIncomeGrowthRate: 35, peMultiple: 65, psMultiple: 13, epsCurrentYear: 4.92, epsGrowthRate: 35, grossMargin: 80, fcfCurrentYear: 10000, fcfGrowthRate: 35, fcfMultiple: 65, sharesOutstanding: 960 },
    },
  },
  {
    id: nanoid(),
    ticker: 'ADBE',
    name: 'Adobe Inc.',
    industry: 'Technology',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 430,
      currentMarketCap: 190000,
      currentRevenue: 21500,
      currentNetIncome: 5560,
      currentEPS: 12.56,
      currentPE: 34,
      currentPS: 8.8,
      currentFCF: 7400,
      valuationMethod: 'pe',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 21500, revenueGrowthRate: 8, netIncomeCurrentYear: 5560, netIncomeGrowthRate: 8, peMultiple: 25, psMultiple: 6, epsCurrentYear: 12.56, epsGrowthRate: 8, grossMargin: 87, fcfCurrentYear: 7400, fcfGrowthRate: 8, fcfMultiple: 25, sharesOutstanding: 443 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 21500, revenueGrowthRate: 14, netIncomeCurrentYear: 5560, netIncomeGrowthRate: 16, peMultiple: 35, psMultiple: 9, epsCurrentYear: 12.56, epsGrowthRate: 16, grossMargin: 88, fcfCurrentYear: 7400, fcfGrowthRate: 16, fcfMultiple: 35, sharesOutstanding: 443 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 21500, revenueGrowthRate: 22, netIncomeCurrentYear: 5560, netIncomeGrowthRate: 28, peMultiple: 48, psMultiple: 13, epsCurrentYear: 12.56, epsGrowthRate: 28, grossMargin: 89, fcfCurrentYear: 7400, fcfGrowthRate: 28, fcfMultiple: 48, sharesOutstanding: 443 },
    },
  },
  {
    id: nanoid(),
    ticker: 'NFLX',
    name: 'Netflix Inc.',
    industry: 'Communication Services',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 1000,
      currentMarketCap: 430000,
      currentRevenue: 38900,
      currentNetIncome: 8700,
      currentEPS: 19.83,
      currentPE: 50,
      currentPS: 11,
      currentFCF: 6900,
      valuationMethod: 'pe',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 38900, revenueGrowthRate: 10, netIncomeCurrentYear: 8700, netIncomeGrowthRate: 12, peMultiple: 30, psMultiple: 7, epsCurrentYear: 19.83, epsGrowthRate: 12, grossMargin: 43, fcfCurrentYear: 6900, fcfGrowthRate: 12, fcfMultiple: 30, sharesOutstanding: 438 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 38900, revenueGrowthRate: 16, netIncomeCurrentYear: 8700, netIncomeGrowthRate: 22, peMultiple: 45, psMultiple: 11, epsCurrentYear: 19.83, epsGrowthRate: 22, grossMargin: 46, fcfCurrentYear: 6900, fcfGrowthRate: 22, fcfMultiple: 45, sharesOutstanding: 438 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 38900, revenueGrowthRate: 24, netIncomeCurrentYear: 8700, netIncomeGrowthRate: 35, peMultiple: 60, psMultiple: 15, epsCurrentYear: 19.83, epsGrowthRate: 35, grossMargin: 50, fcfCurrentYear: 6900, fcfGrowthRate: 35, fcfMultiple: 60, sharesOutstanding: 438 },
    },
  },
  {
    id: nanoid(),
    ticker: 'DIS',
    name: 'Walt Disney Co.',
    industry: 'Communication Services',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 110,
      currentMarketCap: 200000,
      currentRevenue: 91400,
      currentNetIncome: 4970,
      currentEPS: 2.72,
      currentPE: 40,
      currentPS: 2.2,
      currentFCF: 4500,
      valuationMethod: 'pe',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 91400, revenueGrowthRate: 3, netIncomeCurrentYear: 4970, netIncomeGrowthRate: 5, peMultiple: 20, psMultiple: 1.5, epsCurrentYear: 2.72, epsGrowthRate: 5, grossMargin: 35, fcfCurrentYear: 4500, fcfGrowthRate: 5, fcfMultiple: 20, sharesOutstanding: 1830 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 91400, revenueGrowthRate: 7, netIncomeCurrentYear: 4970, netIncomeGrowthRate: 15, peMultiple: 30, psMultiple: 2.5, epsCurrentYear: 2.72, epsGrowthRate: 15, grossMargin: 37, fcfCurrentYear: 4500, fcfGrowthRate: 15, fcfMultiple: 30, sharesOutstanding: 1830 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 91400, revenueGrowthRate: 12, netIncomeCurrentYear: 4970, netIncomeGrowthRate: 28, peMultiple: 42, psMultiple: 3.5, epsCurrentYear: 2.72, epsGrowthRate: 28, grossMargin: 40, fcfCurrentYear: 4500, fcfGrowthRate: 28, fcfMultiple: 42, sharesOutstanding: 1830 },
    },
  },
  {
    id: nanoid(),
    ticker: 'V',
    name: 'Visa Inc.',
    industry: 'Financials',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 350,
      currentMarketCap: 710000,
      currentRevenue: 35900,
      currentNetIncome: 19700,
      currentEPS: 9.73,
      currentPE: 36,
      currentPS: 19.8,
      currentFCF: 20000,
      valuationMethod: 'pe',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 35900, revenueGrowthRate: 8, netIncomeCurrentYear: 19700, netIncomeGrowthRate: 8, peMultiple: 28, psMultiple: 14, epsCurrentYear: 9.73, epsGrowthRate: 8, grossMargin: 80, fcfCurrentYear: 20000, fcfGrowthRate: 8, fcfMultiple: 28, sharesOutstanding: 2030 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 35900, revenueGrowthRate: 12, netIncomeCurrentYear: 19700, netIncomeGrowthRate: 14, peMultiple: 36, psMultiple: 20, epsCurrentYear: 9.73, epsGrowthRate: 14, grossMargin: 81, fcfCurrentYear: 20000, fcfGrowthRate: 14, fcfMultiple: 36, sharesOutstanding: 2030 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 35900, revenueGrowthRate: 18, netIncomeCurrentYear: 19700, netIncomeGrowthRate: 22, peMultiple: 46, psMultiple: 26, epsCurrentYear: 9.73, epsGrowthRate: 22, grossMargin: 82, fcfCurrentYear: 20000, fcfGrowthRate: 22, fcfMultiple: 46, sharesOutstanding: 2030 },
    },
  },
  {
    id: nanoid(),
    ticker: 'MA',
    name: 'Mastercard Inc.',
    industry: 'Financials',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 560,
      currentMarketCap: 520000,
      currentRevenue: 27400,
      currentNetIncome: 12900,
      currentEPS: 13.89,
      currentPE: 40,
      currentPS: 19,
      currentFCF: 13500,
      valuationMethod: 'pe',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 27400, revenueGrowthRate: 8, netIncomeCurrentYear: 12900, netIncomeGrowthRate: 8, peMultiple: 30, psMultiple: 14, epsCurrentYear: 13.89, epsGrowthRate: 8, grossMargin: 79, fcfCurrentYear: 13500, fcfGrowthRate: 8, fcfMultiple: 30, sharesOutstanding: 930 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 27400, revenueGrowthRate: 14, netIncomeCurrentYear: 12900, netIncomeGrowthRate: 16, peMultiple: 40, psMultiple: 20, epsCurrentYear: 13.89, epsGrowthRate: 16, grossMargin: 80, fcfCurrentYear: 13500, fcfGrowthRate: 16, fcfMultiple: 40, sharesOutstanding: 930 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 27400, revenueGrowthRate: 20, netIncomeCurrentYear: 12900, netIncomeGrowthRate: 25, peMultiple: 52, psMultiple: 26, epsCurrentYear: 13.89, epsGrowthRate: 25, grossMargin: 81, fcfCurrentYear: 13500, fcfGrowthRate: 25, fcfMultiple: 52, sharesOutstanding: 930 },
    },
  },
  {
    id: nanoid(),
    ticker: 'COIN',
    name: 'Coinbase Global',
    industry: 'Financials',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 280,
      currentMarketCap: 68000,
      currentRevenue: 6600,
      currentNetIncome: 2600,
      currentEPS: 10.56,
      currentPE: 26,
      currentPS: 10.3,
      currentFCF: 2800,
      valuationMethod: 'ps',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 6600, revenueGrowthRate: 5, netIncomeCurrentYear: 2600, netIncomeGrowthRate: 5, peMultiple: 15, psMultiple: 5, epsCurrentYear: 10.56, epsGrowthRate: 5, grossMargin: 85, fcfCurrentYear: 2800, fcfGrowthRate: 5, fcfMultiple: 15, sharesOutstanding: 242 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 6600, revenueGrowthRate: 25, netIncomeCurrentYear: 2600, netIncomeGrowthRate: 35, peMultiple: 30, psMultiple: 12, epsCurrentYear: 10.56, epsGrowthRate: 35, grossMargin: 87, fcfCurrentYear: 2800, fcfGrowthRate: 35, fcfMultiple: 30, sharesOutstanding: 242 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 6600, revenueGrowthRate: 55, netIncomeCurrentYear: 2600, netIncomeGrowthRate: 70, peMultiple: 55, psMultiple: 22, epsCurrentYear: 10.56, epsGrowthRate: 70, grossMargin: 89, fcfCurrentYear: 2800, fcfGrowthRate: 70, fcfMultiple: 55, sharesOutstanding: 242 },
    },
  },
  {
    id: nanoid(),
    ticker: 'ETH',
    name: 'Ethereum (via ETF)',
    industry: 'Crypto',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 2800,
      currentMarketCap: 338000,
      currentRevenue: 0,
      currentNetIncome: 0,
      currentEPS: 0,
      currentPE: 0,
      currentPS: 0,
      currentFCF: 0,
      valuationMethod: 'price',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 0, revenueGrowthRate: 0, netIncomeCurrentYear: 0, netIncomeGrowthRate: 0, peMultiple: 0, psMultiple: 0, epsCurrentYear: 0, epsGrowthRate: 0, grossMargin: 0, fcfCurrentYear: 0, fcfGrowthRate: 0, fcfMultiple: 0, sharesOutstanding: 120000000, targetPriceOverride: 1500 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 0, revenueGrowthRate: 0, netIncomeCurrentYear: 0, netIncomeGrowthRate: 0, peMultiple: 0, psMultiple: 0, epsCurrentYear: 0, epsGrowthRate: 0, grossMargin: 0, fcfCurrentYear: 0, fcfGrowthRate: 0, fcfMultiple: 0, sharesOutstanding: 120000000, targetPriceOverride: 8000 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 0, revenueGrowthRate: 0, netIncomeCurrentYear: 0, netIncomeGrowthRate: 0, peMultiple: 0, psMultiple: 0, epsCurrentYear: 0, epsGrowthRate: 0, grossMargin: 0, fcfCurrentYear: 0, fcfGrowthRate: 0, fcfMultiple: 0, sharesOutstanding: 120000000, targetPriceOverride: 20000 },
    },
  },
  {
    id: nanoid(),
    ticker: 'MSTR',
    name: 'MicroStrategy Inc.',
    industry: 'Crypto',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 320,
      currentMarketCap: 38000,
      currentRevenue: 480,
      currentNetIncome: -1200,
      currentEPS: -5.50,
      currentPE: 0,
      currentPS: 79,
      currentFCF: -800,
      valuationMethod: 'price',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 480, revenueGrowthRate: 5, netIncomeCurrentYear: -1200, netIncomeGrowthRate: 0, peMultiple: 0, psMultiple: 0, epsCurrentYear: -5.50, epsGrowthRate: 0, grossMargin: 70, fcfCurrentYear: -800, fcfGrowthRate: 0, fcfMultiple: 0, sharesOutstanding: 119000, targetPriceOverride: 100 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 480, revenueGrowthRate: 10, netIncomeCurrentYear: -1200, netIncomeGrowthRate: 0, peMultiple: 0, psMultiple: 0, epsCurrentYear: -5.50, epsGrowthRate: 0, grossMargin: 72, fcfCurrentYear: -800, fcfGrowthRate: 0, fcfMultiple: 0, sharesOutstanding: 119000, targetPriceOverride: 600 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 480, revenueGrowthRate: 15, netIncomeCurrentYear: -1200, netIncomeGrowthRate: 0, peMultiple: 0, psMultiple: 0, epsCurrentYear: -5.50, epsGrowthRate: 0, grossMargin: 74, fcfCurrentYear: -800, fcfGrowthRate: 0, fcfMultiple: 0, sharesOutstanding: 119000, targetPriceOverride: 2000 },
    },
  },
  {
    id: nanoid(),
    ticker: 'QQQ',
    name: 'Invesco QQQ Trust ETF',
    industry: 'ETF',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 500,
      currentMarketCap: 290000,
      currentRevenue: 0,
      currentNetIncome: 0,
      currentEPS: 0,
      currentPE: 0,
      currentPS: 0,
      currentFCF: 0,
      valuationMethod: 'price',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 0, revenueGrowthRate: 0, netIncomeCurrentYear: 0, netIncomeGrowthRate: 0, peMultiple: 0, psMultiple: 0, epsCurrentYear: 0, epsGrowthRate: 0, grossMargin: 0, fcfCurrentYear: 0, fcfGrowthRate: 0, fcfMultiple: 0, sharesOutstanding: 580000, targetPriceOverride: 380 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 0, revenueGrowthRate: 0, netIncomeCurrentYear: 0, netIncomeGrowthRate: 0, peMultiple: 0, psMultiple: 0, epsCurrentYear: 0, epsGrowthRate: 0, grossMargin: 0, fcfCurrentYear: 0, fcfGrowthRate: 0, fcfMultiple: 0, sharesOutstanding: 580000, targetPriceOverride: 620 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 0, revenueGrowthRate: 0, netIncomeCurrentYear: 0, netIncomeGrowthRate: 0, peMultiple: 0, psMultiple: 0, epsCurrentYear: 0, epsGrowthRate: 0, grossMargin: 0, fcfCurrentYear: 0, fcfGrowthRate: 0, fcfMultiple: 0, sharesOutstanding: 580000, targetPriceOverride: 850 },
    },
  },
  {
    id: nanoid(),
    ticker: 'ASML',
    name: 'ASML Holding N.V.',
    industry: 'Technology',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 680,
      currentMarketCap: 270000,
      currentRevenue: 27600,
      currentNetIncome: 7800,
      currentEPS: 19.75,
      currentPE: 34,
      currentPS: 9.8,
      currentFCF: 6500,
      valuationMethod: 'pe',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 27600, revenueGrowthRate: 8, netIncomeCurrentYear: 7800, netIncomeGrowthRate: 8, peMultiple: 25, psMultiple: 7, epsCurrentYear: 19.75, epsGrowthRate: 8, grossMargin: 51, fcfCurrentYear: 6500, fcfGrowthRate: 8, fcfMultiple: 25, sharesOutstanding: 395 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 27600, revenueGrowthRate: 18, netIncomeCurrentYear: 7800, netIncomeGrowthRate: 22, peMultiple: 35, psMultiple: 11, epsCurrentYear: 19.75, epsGrowthRate: 22, grossMargin: 53, fcfCurrentYear: 6500, fcfGrowthRate: 22, fcfMultiple: 35, sharesOutstanding: 395 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 27600, revenueGrowthRate: 28, netIncomeCurrentYear: 7800, netIncomeGrowthRate: 35, peMultiple: 48, psMultiple: 16, epsCurrentYear: 19.75, epsGrowthRate: 35, grossMargin: 56, fcfCurrentYear: 6500, fcfGrowthRate: 35, fcfMultiple: 48, sharesOutstanding: 395 },
    },
  },
  {
    id: nanoid(),
    ticker: 'TSM',
    name: 'Taiwan Semiconductor',
    industry: 'Technology',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 185,
      currentMarketCap: 960000,
      currentRevenue: 87000,
      currentNetIncome: 34000,
      currentEPS: 6.56,
      currentPE: 28,
      currentPS: 11,
      currentFCF: 18000,
      valuationMethod: 'pe',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 87000, revenueGrowthRate: 12, netIncomeCurrentYear: 34000, netIncomeGrowthRate: 12, peMultiple: 20, psMultiple: 7, epsCurrentYear: 6.56, epsGrowthRate: 12, grossMargin: 53, fcfCurrentYear: 18000, fcfGrowthRate: 12, fcfMultiple: 20, sharesOutstanding: 5180 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 87000, revenueGrowthRate: 22, netIncomeCurrentYear: 34000, netIncomeGrowthRate: 25, peMultiple: 28, psMultiple: 11, epsCurrentYear: 6.56, epsGrowthRate: 25, grossMargin: 55, fcfCurrentYear: 18000, fcfGrowthRate: 25, fcfMultiple: 28, sharesOutstanding: 5180 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 87000, revenueGrowthRate: 35, netIncomeCurrentYear: 34000, netIncomeGrowthRate: 40, peMultiple: 38, psMultiple: 16, epsCurrentYear: 6.56, epsGrowthRate: 40, grossMargin: 58, fcfCurrentYear: 18000, fcfGrowthRate: 40, fcfMultiple: 38, sharesOutstanding: 5180 },
    },
  },
  {
    id: nanoid(),
    ticker: 'ARM',
    name: 'Arm Holdings plc',
    industry: 'Technology',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 130,
      currentMarketCap: 135000,
      currentRevenue: 3960,
      currentNetIncome: 1070,
      currentEPS: 1.02,
      currentPE: 127,
      currentPS: 34,
      currentFCF: 1200,
      valuationMethod: 'ps',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 3960, revenueGrowthRate: 18, netIncomeCurrentYear: 1070, netIncomeGrowthRate: 22, peMultiple: 50, psMultiple: 18, epsCurrentYear: 1.02, epsGrowthRate: 22, grossMargin: 96, fcfCurrentYear: 1200, fcfGrowthRate: 22, fcfMultiple: 50, sharesOutstanding: 1050 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 3960, revenueGrowthRate: 32, netIncomeCurrentYear: 1070, netIncomeGrowthRate: 45, peMultiple: 90, psMultiple: 35, epsCurrentYear: 1.02, epsGrowthRate: 45, grossMargin: 97, fcfCurrentYear: 1200, fcfGrowthRate: 45, fcfMultiple: 90, sharesOutstanding: 1050 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 3960, revenueGrowthRate: 50, netIncomeCurrentYear: 1070, netIncomeGrowthRate: 70, peMultiple: 140, psMultiple: 55, epsCurrentYear: 1.02, epsGrowthRate: 70, grossMargin: 97, fcfCurrentYear: 1200, fcfGrowthRate: 70, fcfMultiple: 140, sharesOutstanding: 1050 },
    },
  },
];

// ── Popular growth & speculative stocks (added v3) ────────────────────────────
SAMPLE_STOCKS.push(
  {
    id: 'hims',
    ticker: 'HIMS',
    name: 'Hims & Hers Health',
    industry: 'Healthcare',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 22,
      currentMarketCap: 5200,
      currentRevenue: 870,
      currentNetIncome: -50,
      currentEPS: -0.21,
      currentPE: 0,
      currentPS: 6,
      currentFCF: 30,
      valuationMethod: 'ps',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 870, revenueGrowthRate: 20, netIncomeCurrentYear: -50, netIncomeGrowthRate: 50, peMultiple: 0, psMultiple: 3, epsCurrentYear: -0.21, epsGrowthRate: 50, grossMargin: 78, fcfCurrentYear: 30, fcfGrowthRate: 30, fcfMultiple: 20, sharesOutstanding: 240 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 870, revenueGrowthRate: 40, netIncomeCurrentYear: -50, netIncomeGrowthRate: 80, peMultiple: 0, psMultiple: 6, epsCurrentYear: -0.21, epsGrowthRate: 80, grossMargin: 80, fcfCurrentYear: 30, fcfGrowthRate: 60, fcfMultiple: 40, sharesOutstanding: 240 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 870, revenueGrowthRate: 65, netIncomeCurrentYear: -50, netIncomeGrowthRate: 120, peMultiple: 0, psMultiple: 12, epsCurrentYear: -0.21, epsGrowthRate: 120, grossMargin: 82, fcfCurrentYear: 30, fcfGrowthRate: 100, fcfMultiple: 70, sharesOutstanding: 240 },
    },
  },
  {
    id: 'ionq',
    ticker: 'IONQ',
    name: 'IonQ Inc.',
    industry: 'Technology',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 28,
      currentMarketCap: 6500,
      currentRevenue: 43,
      currentNetIncome: -300,
      currentEPS: -1.30,
      currentPE: 0,
      currentPS: 150,
      currentFCF: -280,
      valuationMethod: 'ps',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 43, revenueGrowthRate: 50, netIncomeCurrentYear: -300, netIncomeGrowthRate: 30, peMultiple: 0, psMultiple: 30, epsCurrentYear: -1.30, epsGrowthRate: 30, grossMargin: 55, fcfCurrentYear: -280, fcfGrowthRate: 30, fcfMultiple: 0, sharesOutstanding: 235 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 43, revenueGrowthRate: 90, netIncomeCurrentYear: -300, netIncomeGrowthRate: 60, peMultiple: 0, psMultiple: 80, epsCurrentYear: -1.30, epsGrowthRate: 60, grossMargin: 65, fcfCurrentYear: -280, fcfGrowthRate: 60, fcfMultiple: 0, sharesOutstanding: 235 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 43, revenueGrowthRate: 150, netIncomeCurrentYear: -300, netIncomeGrowthRate: 100, peMultiple: 0, psMultiple: 200, epsCurrentYear: -1.30, epsGrowthRate: 100, grossMargin: 75, fcfCurrentYear: -280, fcfGrowthRate: 100, fcfMultiple: 0, sharesOutstanding: 235 },
    },
  },
  {
    id: 'leu',
    ticker: 'LEU',
    name: 'Centrus Energy Corp.',
    industry: 'Energy',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 65,
      currentMarketCap: 1100,
      currentRevenue: 340,
      currentNetIncome: 55,
      currentEPS: 3.20,
      currentPE: 20,
      currentPS: 3.2,
      currentFCF: 45,
      valuationMethod: 'pe',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 340, revenueGrowthRate: 5, netIncomeCurrentYear: 55, netIncomeGrowthRate: 5, peMultiple: 12, psMultiple: 2, epsCurrentYear: 3.20, epsGrowthRate: 5, grossMargin: 30, fcfCurrentYear: 45, fcfGrowthRate: 5, fcfMultiple: 10, sharesOutstanding: 17 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 340, revenueGrowthRate: 20, netIncomeCurrentYear: 55, netIncomeGrowthRate: 25, peMultiple: 25, psMultiple: 5, epsCurrentYear: 3.20, epsGrowthRate: 25, grossMargin: 35, fcfCurrentYear: 45, fcfGrowthRate: 25, fcfMultiple: 20, sharesOutstanding: 17 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 340, revenueGrowthRate: 45, netIncomeCurrentYear: 55, netIncomeGrowthRate: 55, peMultiple: 45, psMultiple: 10, epsCurrentYear: 3.20, epsGrowthRate: 55, grossMargin: 40, fcfCurrentYear: 45, fcfGrowthRate: 55, fcfMultiple: 40, sharesOutstanding: 17 },
    },
  },
  {
    id: 'sofi',
    ticker: 'SOFI',
    name: 'SoFi Technologies',
    industry: 'Financials',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 14,
      currentMarketCap: 14500,
      currentRevenue: 2100,
      currentNetIncome: 500,
      currentEPS: 0.48,
      currentPE: 29,
      currentPS: 6.9,
      currentFCF: 400,
      valuationMethod: 'ps',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 2100, revenueGrowthRate: 10, netIncomeCurrentYear: 500, netIncomeGrowthRate: 15, peMultiple: 15, psMultiple: 3, epsCurrentYear: 0.48, epsGrowthRate: 15, grossMargin: 55, fcfCurrentYear: 400, fcfGrowthRate: 10, fcfMultiple: 15, sharesOutstanding: 1040 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 2100, revenueGrowthRate: 25, netIncomeCurrentYear: 500, netIncomeGrowthRate: 40, peMultiple: 30, psMultiple: 7, epsCurrentYear: 0.48, epsGrowthRate: 40, grossMargin: 60, fcfCurrentYear: 400, fcfGrowthRate: 35, fcfMultiple: 25, sharesOutstanding: 1040 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 2100, revenueGrowthRate: 45, netIncomeCurrentYear: 500, netIncomeGrowthRate: 70, peMultiple: 55, psMultiple: 14, epsCurrentYear: 0.48, epsGrowthRate: 70, grossMargin: 65, fcfCurrentYear: 400, fcfGrowthRate: 65, fcfMultiple: 50, sharesOutstanding: 1040 },
    },
  },
  {
    id: 'rklb',
    ticker: 'RKLB',
    name: 'Rocket Lab USA',
    industry: 'Industrials',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 22,
      currentMarketCap: 10500,
      currentRevenue: 436,
      currentNetIncome: -200,
      currentEPS: -0.43,
      currentPE: 0,
      currentPS: 24,
      currentFCF: -150,
      valuationMethod: 'ps',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 436, revenueGrowthRate: 25, netIncomeCurrentYear: -200, netIncomeGrowthRate: 40, peMultiple: 0, psMultiple: 10, epsCurrentYear: -0.43, epsGrowthRate: 40, grossMargin: 28, fcfCurrentYear: -150, fcfGrowthRate: 40, fcfMultiple: 0, sharesOutstanding: 490 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 436, revenueGrowthRate: 50, netIncomeCurrentYear: -200, netIncomeGrowthRate: 70, peMultiple: 0, psMultiple: 20, epsCurrentYear: -0.43, epsGrowthRate: 70, grossMargin: 35, fcfCurrentYear: -150, fcfGrowthRate: 70, fcfMultiple: 0, sharesOutstanding: 490 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 436, revenueGrowthRate: 80, netIncomeCurrentYear: -200, netIncomeGrowthRate: 100, peMultiple: 0, psMultiple: 40, epsCurrentYear: -0.43, epsGrowthRate: 100, grossMargin: 42, fcfCurrentYear: -150, fcfGrowthRate: 100, fcfMultiple: 0, sharesOutstanding: 490 },
    },
  },
  {
    id: 'asts',
    ticker: 'ASTS',
    name: 'AST SpaceMobile',
    industry: 'Communication Services',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 25,
      currentMarketCap: 8200,
      currentRevenue: 30,
      currentNetIncome: -350,
      currentEPS: -1.10,
      currentPE: 0,
      currentPS: 270,
      currentFCF: -320,
      valuationMethod: 'ps',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 30, revenueGrowthRate: 100, netIncomeCurrentYear: -350, netIncomeGrowthRate: 40, peMultiple: 0, psMultiple: 20, epsCurrentYear: -1.10, epsGrowthRate: 40, grossMargin: 50, fcfCurrentYear: -320, fcfGrowthRate: 40, fcfMultiple: 0, sharesOutstanding: 330 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 30, revenueGrowthRate: 200, netIncomeCurrentYear: -350, netIncomeGrowthRate: 70, peMultiple: 0, psMultiple: 50, epsCurrentYear: -1.10, epsGrowthRate: 70, grossMargin: 60, fcfCurrentYear: -320, fcfGrowthRate: 70, fcfMultiple: 0, sharesOutstanding: 330 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 30, revenueGrowthRate: 400, netIncomeCurrentYear: -350, netIncomeGrowthRate: 120, peMultiple: 0, psMultiple: 120, epsCurrentYear: -1.10, epsGrowthRate: 120, grossMargin: 70, fcfCurrentYear: -320, fcfGrowthRate: 120, fcfMultiple: 0, sharesOutstanding: 330 },
    },
  },
  {
    id: 'rgti',
    ticker: 'RGTI',
    name: 'Rigetti Computing',
    industry: 'Technology',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 10,
      currentMarketCap: 2100,
      currentRevenue: 14,
      currentNetIncome: -120,
      currentEPS: -0.60,
      currentPE: 0,
      currentPS: 150,
      currentFCF: -110,
      valuationMethod: 'ps',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 14, revenueGrowthRate: 40, netIncomeCurrentYear: -120, netIncomeGrowthRate: 30, peMultiple: 0, psMultiple: 30, epsCurrentYear: -0.60, epsGrowthRate: 30, grossMargin: 40, fcfCurrentYear: -110, fcfGrowthRate: 30, fcfMultiple: 0, sharesOutstanding: 210 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 14, revenueGrowthRate: 80, netIncomeCurrentYear: -120, netIncomeGrowthRate: 60, peMultiple: 0, psMultiple: 80, epsCurrentYear: -0.60, epsGrowthRate: 60, grossMargin: 55, fcfCurrentYear: -110, fcfGrowthRate: 60, fcfMultiple: 0, sharesOutstanding: 210 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 14, revenueGrowthRate: 150, netIncomeCurrentYear: -120, netIncomeGrowthRate: 100, peMultiple: 0, psMultiple: 180, epsCurrentYear: -0.60, epsGrowthRate: 100, grossMargin: 65, fcfCurrentYear: -110, fcfGrowthRate: 100, fcfMultiple: 0, sharesOutstanding: 210 },
    },
  },
  {
    id: 'soun',
    ticker: 'SOUN',
    name: 'SoundHound AI',
    industry: 'Technology',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 9,
      currentMarketCap: 3200,
      currentRevenue: 84,
      currentNetIncome: -200,
      currentEPS: -0.60,
      currentPE: 0,
      currentPS: 38,
      currentFCF: -180,
      valuationMethod: 'ps',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 84, revenueGrowthRate: 40, netIncomeCurrentYear: -200, netIncomeGrowthRate: 40, peMultiple: 0, psMultiple: 10, epsCurrentYear: -0.60, epsGrowthRate: 40, grossMargin: 55, fcfCurrentYear: -180, fcfGrowthRate: 40, fcfMultiple: 0, sharesOutstanding: 360 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 84, revenueGrowthRate: 75, netIncomeCurrentYear: -200, netIncomeGrowthRate: 65, peMultiple: 0, psMultiple: 25, epsCurrentYear: -0.60, epsGrowthRate: 65, grossMargin: 65, fcfCurrentYear: -180, fcfGrowthRate: 65, fcfMultiple: 0, sharesOutstanding: 360 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 84, revenueGrowthRate: 130, netIncomeCurrentYear: -200, netIncomeGrowthRate: 100, peMultiple: 0, psMultiple: 60, epsCurrentYear: -0.60, epsGrowthRate: 100, grossMargin: 72, fcfCurrentYear: -180, fcfGrowthRate: 100, fcfMultiple: 0, sharesOutstanding: 360 },
    },
  },
  {
    id: 'dkng',
    ticker: 'DKNG',
    name: 'DraftKings Inc.',
    industry: 'Consumer Discretionary',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 35,
      currentMarketCap: 16000,
      currentRevenue: 4770,
      currentNetIncome: -400,
      currentEPS: -0.87,
      currentPE: 0,
      currentPS: 3.4,
      currentFCF: 200,
      valuationMethod: 'ps',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 4770, revenueGrowthRate: 12, netIncomeCurrentYear: -400, netIncomeGrowthRate: 50, peMultiple: 0, psMultiple: 2, epsCurrentYear: -0.87, epsGrowthRate: 50, grossMargin: 40, fcfCurrentYear: 200, fcfGrowthRate: 20, fcfMultiple: 20, sharesOutstanding: 460 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 4770, revenueGrowthRate: 25, netIncomeCurrentYear: -400, netIncomeGrowthRate: 80, peMultiple: 0, psMultiple: 5, epsCurrentYear: -0.87, epsGrowthRate: 80, grossMargin: 45, fcfCurrentYear: 200, fcfGrowthRate: 50, fcfMultiple: 40, sharesOutstanding: 460 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 4770, revenueGrowthRate: 40, netIncomeCurrentYear: -400, netIncomeGrowthRate: 120, peMultiple: 0, psMultiple: 9, epsCurrentYear: -0.87, epsGrowthRate: 120, grossMargin: 50, fcfCurrentYear: 200, fcfGrowthRate: 90, fcfMultiple: 70, sharesOutstanding: 460 },
    },
  },
  {
    id: 'hood',
    ticker: 'HOOD',
    name: 'Robinhood Markets',
    industry: 'Financials',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 38,
      currentMarketCap: 33000,
      currentRevenue: 1870,
      currentNetIncome: 1400,
      currentEPS: 1.60,
      currentPE: 24,
      currentPS: 17.6,
      currentFCF: 1200,
      valuationMethod: 'ps',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 1870, revenueGrowthRate: 10, netIncomeCurrentYear: 1400, netIncomeGrowthRate: 10, peMultiple: 15, psMultiple: 8, epsCurrentYear: 1.60, epsGrowthRate: 10, grossMargin: 85, fcfCurrentYear: 1200, fcfGrowthRate: 10, fcfMultiple: 15, sharesOutstanding: 870 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 1870, revenueGrowthRate: 30, netIncomeCurrentYear: 1400, netIncomeGrowthRate: 40, peMultiple: 30, psMultiple: 20, epsCurrentYear: 1.60, epsGrowthRate: 40, grossMargin: 87, fcfCurrentYear: 1200, fcfGrowthRate: 35, fcfMultiple: 28, sharesOutstanding: 870 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 1870, revenueGrowthRate: 55, netIncomeCurrentYear: 1400, netIncomeGrowthRate: 75, peMultiple: 55, psMultiple: 40, epsCurrentYear: 1.60, epsGrowthRate: 75, grossMargin: 89, fcfCurrentYear: 1200, fcfGrowthRate: 70, fcfMultiple: 55, sharesOutstanding: 870 },
    },
  },
  {
    id: 'upst',
    ticker: 'UPST',
    name: 'Upstart Holdings',
    industry: 'Financials',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 65,
      currentMarketCap: 5500,
      currentRevenue: 600,
      currentNetIncome: -100,
      currentEPS: -1.20,
      currentPE: 0,
      currentPS: 9.2,
      currentFCF: -80,
      valuationMethod: 'ps',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 600, revenueGrowthRate: 10, netIncomeCurrentYear: -100, netIncomeGrowthRate: 40, peMultiple: 0, psMultiple: 4, epsCurrentYear: -1.20, epsGrowthRate: 40, grossMargin: 75, fcfCurrentYear: -80, fcfGrowthRate: 40, fcfMultiple: 0, sharesOutstanding: 85 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 600, revenueGrowthRate: 35, netIncomeCurrentYear: -100, netIncomeGrowthRate: 70, peMultiple: 0, psMultiple: 12, epsCurrentYear: -1.20, epsGrowthRate: 70, grossMargin: 78, fcfCurrentYear: -80, fcfGrowthRate: 70, fcfMultiple: 0, sharesOutstanding: 85 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 600, revenueGrowthRate: 65, netIncomeCurrentYear: -100, netIncomeGrowthRate: 110, peMultiple: 0, psMultiple: 25, epsCurrentYear: -1.20, epsGrowthRate: 110, grossMargin: 82, fcfCurrentYear: -80, fcfGrowthRate: 110, fcfMultiple: 0, sharesOutstanding: 85 },
    },
  },
  {
    id: 'afrm',
    ticker: 'AFRM',
    name: 'Affirm Holdings',
    industry: 'Financials',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 50,
      currentMarketCap: 16000,
      currentRevenue: 2320,
      currentNetIncome: -200,
      currentEPS: -0.63,
      currentPE: 0,
      currentPS: 6.9,
      currentFCF: 100,
      valuationMethod: 'ps',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 2320, revenueGrowthRate: 15, netIncomeCurrentYear: -200, netIncomeGrowthRate: 50, peMultiple: 0, psMultiple: 3, epsCurrentYear: -0.63, epsGrowthRate: 50, grossMargin: 55, fcfCurrentYear: 100, fcfGrowthRate: 20, fcfMultiple: 20, sharesOutstanding: 320 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 2320, revenueGrowthRate: 35, netIncomeCurrentYear: -200, netIncomeGrowthRate: 80, peMultiple: 0, psMultiple: 8, epsCurrentYear: -0.63, epsGrowthRate: 80, grossMargin: 60, fcfCurrentYear: 100, fcfGrowthRate: 50, fcfMultiple: 40, sharesOutstanding: 320 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 2320, revenueGrowthRate: 60, netIncomeCurrentYear: -200, netIncomeGrowthRate: 120, peMultiple: 0, psMultiple: 16, epsCurrentYear: -0.63, epsGrowthRate: 120, grossMargin: 65, fcfCurrentYear: 100, fcfGrowthRate: 100, fcfMultiple: 80, sharesOutstanding: 320 },
    },
  },
  {
    id: 'nu',
    ticker: 'NU',
    name: 'Nu Holdings',
    industry: 'Financials',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 12,
      currentMarketCap: 57000,
      currentRevenue: 11500,
      currentNetIncome: 1700,
      currentEPS: 0.36,
      currentPE: 33,
      currentPS: 5.0,
      currentFCF: 1500,
      valuationMethod: 'ps',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 11500, revenueGrowthRate: 15, netIncomeCurrentYear: 1700, netIncomeGrowthRate: 20, peMultiple: 18, psMultiple: 3, epsCurrentYear: 0.36, epsGrowthRate: 20, grossMargin: 40, fcfCurrentYear: 1500, fcfGrowthRate: 15, fcfMultiple: 15, sharesOutstanding: 4800 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 11500, revenueGrowthRate: 30, netIncomeCurrentYear: 1700, netIncomeGrowthRate: 45, peMultiple: 35, psMultiple: 6, epsCurrentYear: 0.36, epsGrowthRate: 45, grossMargin: 45, fcfCurrentYear: 1500, fcfGrowthRate: 40, fcfMultiple: 28, sharesOutstanding: 4800 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 11500, revenueGrowthRate: 50, netIncomeCurrentYear: 1700, netIncomeGrowthRate: 75, peMultiple: 60, psMultiple: 12, epsCurrentYear: 0.36, epsGrowthRate: 75, grossMargin: 50, fcfCurrentYear: 1500, fcfGrowthRate: 70, fcfMultiple: 55, sharesOutstanding: 4800 },
    },
  },
  {
    id: 'crwd',
    ticker: 'CRWD',
    name: 'CrowdStrike Holdings',
    industry: 'Technology',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 380,
      currentMarketCap: 93000,
      currentRevenue: 3950,
      currentNetIncome: 90,
      currentEPS: 0.37,
      currentPE: 1027,
      currentPS: 23.5,
      currentFCF: 1000,
      valuationMethod: 'ps',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 3950, revenueGrowthRate: 18, netIncomeCurrentYear: 90, netIncomeGrowthRate: 30, peMultiple: 80, psMultiple: 12, epsCurrentYear: 0.37, epsGrowthRate: 30, grossMargin: 75, fcfCurrentYear: 1000, fcfGrowthRate: 18, fcfMultiple: 40, sharesOutstanding: 245 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 3950, revenueGrowthRate: 28, netIncomeCurrentYear: 90, netIncomeGrowthRate: 60, peMultiple: 150, psMultiple: 22, epsCurrentYear: 0.37, epsGrowthRate: 60, grossMargin: 77, fcfCurrentYear: 1000, fcfGrowthRate: 28, fcfMultiple: 70, sharesOutstanding: 245 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 3950, revenueGrowthRate: 40, netIncomeCurrentYear: 90, netIncomeGrowthRate: 100, peMultiple: 250, psMultiple: 35, epsCurrentYear: 0.37, epsGrowthRate: 100, grossMargin: 79, fcfCurrentYear: 1000, fcfGrowthRate: 40, fcfMultiple: 110, sharesOutstanding: 245 },
    },
  },
  {
    id: 'snow',
    ticker: 'SNOW',
    name: 'Snowflake Inc.',
    industry: 'Technology',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 160,
      currentMarketCap: 53000,
      currentRevenue: 3630,
      currentNetIncome: -900,
      currentEPS: -2.73,
      currentPE: 0,
      currentPS: 14.6,
      currentFCF: 800,
      valuationMethod: 'ps',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 3630, revenueGrowthRate: 18, netIncomeCurrentYear: -900, netIncomeGrowthRate: 40, peMultiple: 0, psMultiple: 8, epsCurrentYear: -2.73, epsGrowthRate: 40, grossMargin: 68, fcfCurrentYear: 800, fcfGrowthRate: 18, fcfMultiple: 30, sharesOutstanding: 330 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 3630, revenueGrowthRate: 28, netIncomeCurrentYear: -900, netIncomeGrowthRate: 70, peMultiple: 0, psMultiple: 15, epsCurrentYear: -2.73, epsGrowthRate: 70, grossMargin: 71, fcfCurrentYear: 800, fcfGrowthRate: 28, fcfMultiple: 55, sharesOutstanding: 330 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 3630, revenueGrowthRate: 40, netIncomeCurrentYear: -900, netIncomeGrowthRate: 110, peMultiple: 0, psMultiple: 25, epsCurrentYear: -2.73, epsGrowthRate: 110, grossMargin: 74, fcfCurrentYear: 800, fcfGrowthRate: 40, fcfMultiple: 90, sharesOutstanding: 330 },
    },
  },
  {
    id: 'uber',
    ticker: 'UBER',
    name: 'Uber Technologies',
    industry: 'Consumer Discretionary',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 72,
      currentMarketCap: 152000,
      currentRevenue: 43000,
      currentNetIncome: 9900,
      currentEPS: 4.73,
      currentPE: 15,
      currentPS: 3.5,
      currentFCF: 6900,
      valuationMethod: 'pe',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 43000, revenueGrowthRate: 12, netIncomeCurrentYear: 9900, netIncomeGrowthRate: 15, peMultiple: 12, psMultiple: 2.5, epsCurrentYear: 4.73, epsGrowthRate: 15, grossMargin: 38, fcfCurrentYear: 6900, fcfGrowthRate: 12, fcfMultiple: 15, sharesOutstanding: 2100 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 43000, revenueGrowthRate: 20, netIncomeCurrentYear: 9900, netIncomeGrowthRate: 30, peMultiple: 22, psMultiple: 4, epsCurrentYear: 4.73, epsGrowthRate: 30, grossMargin: 42, fcfCurrentYear: 6900, fcfGrowthRate: 20, fcfMultiple: 25, sharesOutstanding: 2100 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 43000, revenueGrowthRate: 30, netIncomeCurrentYear: 9900, netIncomeGrowthRate: 50, peMultiple: 35, psMultiple: 6, epsCurrentYear: 4.73, epsGrowthRate: 50, grossMargin: 46, fcfCurrentYear: 6900, fcfGrowthRate: 30, fcfMultiple: 40, sharesOutstanding: 2100 },
    },
  },
  {
    id: 'celh',
    ticker: 'CELH',
    name: 'Celsius Holdings',
    industry: 'Consumer Staples',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 28,
      currentMarketCap: 6500,
      currentRevenue: 1360,
      currentNetIncome: 200,
      currentEPS: 0.87,
      currentPE: 32,
      currentPS: 4.8,
      currentFCF: 180,
      valuationMethod: 'ps',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 1360, revenueGrowthRate: 5, netIncomeCurrentYear: 200, netIncomeGrowthRate: 5, peMultiple: 18, psMultiple: 2.5, epsCurrentYear: 0.87, epsGrowthRate: 5, grossMargin: 48, fcfCurrentYear: 180, fcfGrowthRate: 5, fcfMultiple: 15, sharesOutstanding: 235 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 1360, revenueGrowthRate: 20, netIncomeCurrentYear: 200, netIncomeGrowthRate: 30, peMultiple: 35, psMultiple: 5, epsCurrentYear: 0.87, epsGrowthRate: 30, grossMargin: 52, fcfCurrentYear: 180, fcfGrowthRate: 25, fcfMultiple: 28, sharesOutstanding: 235 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 1360, revenueGrowthRate: 40, netIncomeCurrentYear: 200, netIncomeGrowthRate: 60, peMultiple: 55, psMultiple: 9, epsCurrentYear: 0.87, epsGrowthRate: 60, grossMargin: 56, fcfCurrentYear: 180, fcfGrowthRate: 50, fcfMultiple: 50, sharesOutstanding: 235 },
    },
  },
  {
    id: 'cava',
    ticker: 'CAVA',
    name: 'CAVA Group',
    industry: 'Consumer Discretionary',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 90,
      currentMarketCap: 11000,
      currentRevenue: 950,
      currentNetIncome: 60,
      currentEPS: 0.49,
      currentPE: 184,
      currentPS: 11.6,
      currentFCF: 50,
      valuationMethod: 'ps',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 950, revenueGrowthRate: 15, netIncomeCurrentYear: 60, netIncomeGrowthRate: 20, peMultiple: 60, psMultiple: 5, epsCurrentYear: 0.49, epsGrowthRate: 20, grossMargin: 25, fcfCurrentYear: 50, fcfGrowthRate: 15, fcfMultiple: 30, sharesOutstanding: 122 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 950, revenueGrowthRate: 28, netIncomeCurrentYear: 60, netIncomeGrowthRate: 45, peMultiple: 120, psMultiple: 10, epsCurrentYear: 0.49, epsGrowthRate: 45, grossMargin: 28, fcfCurrentYear: 50, fcfGrowthRate: 30, fcfMultiple: 60, sharesOutstanding: 122 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 950, revenueGrowthRate: 45, netIncomeCurrentYear: 60, netIncomeGrowthRate: 80, peMultiple: 200, psMultiple: 18, epsCurrentYear: 0.49, epsGrowthRate: 80, grossMargin: 32, fcfCurrentYear: 50, fcfGrowthRate: 55, fcfMultiple: 100, sharesOutstanding: 122 },
    },
  },
  {
    id: 'smci',
    ticker: 'SMCI',
    name: 'Super Micro Computer',
    industry: 'Technology',
    projections: {
      ...DEFAULT_PROJECTIONS,
      currentPrice: 42,
      currentMarketCap: 24000,
      currentRevenue: 14900,
      currentNetIncome: 600,
      currentEPS: 1.04,
      currentPE: 40,
      currentPS: 1.6,
      currentFCF: -500,
      valuationMethod: 'ps',
      bear: { ...DEFAULT_PROJECTIONS.bear, revenueCurrentYear: 14900, revenueGrowthRate: 10, netIncomeCurrentYear: 600, netIncomeGrowthRate: 10, peMultiple: 15, psMultiple: 0.8, epsCurrentYear: 1.04, epsGrowthRate: 10, grossMargin: 13, fcfCurrentYear: -500, fcfGrowthRate: 10, fcfMultiple: 0, sharesOutstanding: 580 },
      base: { ...DEFAULT_PROJECTIONS.base, revenueCurrentYear: 14900, revenueGrowthRate: 25, netIncomeCurrentYear: 600, netIncomeGrowthRate: 35, peMultiple: 30, psMultiple: 1.8, epsCurrentYear: 1.04, epsGrowthRate: 35, grossMargin: 15, fcfCurrentYear: -500, fcfGrowthRate: 30, fcfMultiple: 20, sharesOutstanding: 580 },
      bull: { ...DEFAULT_PROJECTIONS.bull, revenueCurrentYear: 14900, revenueGrowthRate: 45, netIncomeCurrentYear: 600, netIncomeGrowthRate: 65, peMultiple: 55, psMultiple: 3, epsCurrentYear: 1.04, epsGrowthRate: 65, grossMargin: 17, fcfCurrentYear: -500, fcfGrowthRate: 60, fcfMultiple: 40, sharesOutstanding: 580 },
    },
  },
);
