// Full S&P 500 stock list with tickers, names, and GICS sector classifications
// Industry mapped to our Industry type

import type { Industry } from './types';

export interface SP500Stock {
  ticker: string;
  name: string;
  industry: Industry;
}

export const SP500_STOCKS: SP500Stock[] = [
  // Technology
  { ticker: 'AAPL', name: 'Apple Inc.', industry: 'Technology' },
  { ticker: 'MSFT', name: 'Microsoft Corp.', industry: 'Technology' },
  { ticker: 'NVDA', name: 'NVIDIA Corp.', industry: 'Technology' },
  { ticker: 'AMD', name: 'Advanced Micro Devices', industry: 'Technology' },
  { ticker: 'INTC', name: 'Intel Corporation', industry: 'Technology' },
  { ticker: 'QCOM', name: 'Qualcomm Inc.', industry: 'Technology' },
  { ticker: 'CRM', name: 'Salesforce Inc.', industry: 'Technology' },
  { ticker: 'ADBE', name: 'Adobe Inc.', industry: 'Technology' },
  { ticker: 'ORCL', name: 'Oracle Corporation', industry: 'Technology' },
  { ticker: 'AVGO', name: 'Broadcom Inc.', industry: 'Technology' },
  { ticker: 'TXN', name: 'Texas Instruments', industry: 'Technology' },
  { ticker: 'NOW', name: 'ServiceNow Inc.', industry: 'Technology' },
  { ticker: 'AMAT', name: 'Applied Materials', industry: 'Technology' },
  { ticker: 'LRCX', name: 'Lam Research Corp.', industry: 'Technology' },
  { ticker: 'KLAC', name: 'KLA Corporation', industry: 'Technology' },
  { ticker: 'MRVL', name: 'Marvell Technology', industry: 'Technology' },
  { ticker: 'PANW', name: 'Palo Alto Networks', industry: 'Technology' },
  { ticker: 'CRWD', name: 'CrowdStrike Holdings', industry: 'Technology' },
  { ticker: 'FTNT', name: 'Fortinet Inc.', industry: 'Technology' },
  { ticker: 'CDNS', name: 'Cadence Design Systems', industry: 'Technology' },
  { ticker: 'SNPS', name: 'Synopsys Inc.', industry: 'Technology' },
  { ticker: 'ANSS', name: 'ANSYS Inc.', industry: 'Technology' },
  { ticker: 'KEYS', name: 'Keysight Technologies', industry: 'Technology' },
  { ticker: 'ZBRA', name: 'Zebra Technologies', industry: 'Technology' },
  { ticker: 'EPAM', name: 'EPAM Systems', industry: 'Technology' },
  { ticker: 'CTSH', name: 'Cognizant Technology', industry: 'Technology' },
  { ticker: 'ACN', name: 'Accenture plc', industry: 'Technology' },
  { ticker: 'IBM', name: 'IBM Corp.', industry: 'Technology' },
  { ticker: 'HPQ', name: 'HP Inc.', industry: 'Technology' },
  { ticker: 'HPE', name: 'Hewlett Packard Enterprise', industry: 'Technology' },
  { ticker: 'DELL', name: 'Dell Technologies', industry: 'Technology' },
  { ticker: 'STX', name: 'Seagate Technology', industry: 'Technology' },
  { ticker: 'WDC', name: 'Western Digital Corp.', industry: 'Technology' },
  { ticker: 'NTAP', name: 'NetApp Inc.', industry: 'Technology' },
  { ticker: 'JNPR', name: 'Juniper Networks', industry: 'Technology' },
  { ticker: 'GLW', name: 'Corning Inc.', industry: 'Technology' },
  { ticker: 'FFIV', name: 'F5 Inc.', industry: 'Technology' },
  { ticker: 'GDDY', name: 'GoDaddy Inc.', industry: 'Technology' },
  { ticker: 'GEN', name: 'Gen Digital Inc.', industry: 'Technology' },
  { ticker: 'AKAM', name: 'Akamai Technologies', industry: 'Technology' },
  { ticker: 'PLTR', name: 'Palantir Technologies', industry: 'Technology' },
  { ticker: 'SHOP', name: 'Shopify Inc.', industry: 'Technology' },
  { ticker: 'ASML', name: 'ASML Holding N.V.', industry: 'Technology' },
  { ticker: 'TSM', name: 'Taiwan Semiconductor', industry: 'Technology' },
  { ticker: 'ARM', name: 'Arm Holdings plc', industry: 'Technology' },
  { ticker: 'MU', name: 'Micron Technology', industry: 'Technology' },
  { ticker: 'ON', name: 'ON Semiconductor', industry: 'Technology' },
  { ticker: 'MPWR', name: 'Monolithic Power Systems', industry: 'Technology' },
  { ticker: 'ENPH', name: 'Enphase Energy', industry: 'Technology' },
  { ticker: 'FSLR', name: 'First Solar Inc.', industry: 'Technology' },
  { ticker: 'ROP', name: 'Roper Technologies', industry: 'Technology' },
  { ticker: 'TDY', name: 'Teledyne Technologies', industry: 'Technology' },
  { ticker: 'TRMB', name: 'Trimble Inc.', industry: 'Technology' },
  { ticker: 'PAYC', name: 'Paycom Software', industry: 'Technology' },
  { ticker: 'PAYX', name: 'Paychex Inc.', industry: 'Technology' },
  { ticker: 'ADP', name: 'Automatic Data Processing', industry: 'Technology' },
  { ticker: 'INTU', name: 'Intuit Inc.', industry: 'Technology' },
  { ticker: 'ADSK', name: 'Autodesk Inc.', industry: 'Technology' },
  { ticker: 'WDAY', name: 'Workday Inc.', industry: 'Technology' },
  { ticker: 'VEEV', name: 'Veeva Systems', industry: 'Technology' },
  { ticker: 'DDOG', name: 'Datadog Inc.', industry: 'Technology' },
  { ticker: 'ZS', name: 'Zscaler Inc.', industry: 'Technology' },
  { ticker: 'OKTA', name: 'Okta Inc.', industry: 'Technology' },
  { ticker: 'TWLO', name: 'Twilio Inc.', industry: 'Technology' },
  { ticker: 'DOCN', name: 'DigitalOcean Holdings', industry: 'Technology' },
  { ticker: 'NET', name: 'Cloudflare Inc.', industry: 'Technology' },
  { ticker: 'SNOW', name: 'Snowflake Inc.', industry: 'Technology' },
  { ticker: 'MDB', name: 'MongoDB Inc.', industry: 'Technology' },
  { ticker: 'HUBS', name: 'HubSpot Inc.', industry: 'Technology' },
  { ticker: 'TEAM', name: 'Atlassian Corp.', industry: 'Technology' },
  { ticker: 'ZM', name: 'Zoom Video Communications', industry: 'Technology' },
  { ticker: 'DOCU', name: 'DocuSign Inc.', industry: 'Technology' },
  { ticker: 'BILL', name: 'Bill.com Holdings', industry: 'Technology' },
  { ticker: 'SMAR', name: 'Smartsheet Inc.', industry: 'Technology' },
  { ticker: 'COUP', name: 'Coupa Software', industry: 'Technology' },
  { ticker: 'APPN', name: 'Appian Corporation', industry: 'Technology' },

  // Communication Services
  { ticker: 'GOOGL', name: 'Alphabet Inc. (Class A)', industry: 'Communication Services' },
  { ticker: 'GOOG', name: 'Alphabet Inc. (Class C)', industry: 'Communication Services' },
  { ticker: 'META', name: 'Meta Platforms Inc.', industry: 'Communication Services' },
  { ticker: 'NFLX', name: 'Netflix Inc.', industry: 'Communication Services' },
  { ticker: 'DIS', name: 'Walt Disney Co.', industry: 'Communication Services' },
  { ticker: 'CMCSA', name: 'Comcast Corporation', industry: 'Communication Services' },
  { ticker: 'T', name: 'AT&T Inc.', industry: 'Communication Services' },
  { ticker: 'VZ', name: 'Verizon Communications', industry: 'Communication Services' },
  { ticker: 'TMUS', name: 'T-Mobile US Inc.', industry: 'Communication Services' },
  { ticker: 'CHTR', name: 'Charter Communications', industry: 'Communication Services' },
  { ticker: 'PARA', name: 'Paramount Global', industry: 'Communication Services' },
  { ticker: 'WBD', name: 'Warner Bros. Discovery', industry: 'Communication Services' },
  { ticker: 'FOX', name: 'Fox Corporation', industry: 'Communication Services' },
  { ticker: 'FOXA', name: 'Fox Corporation (Class A)', industry: 'Communication Services' },
  { ticker: 'NWSA', name: 'News Corp (Class A)', industry: 'Communication Services' },
  { ticker: 'OMC', name: 'Omnicom Group', industry: 'Communication Services' },
  { ticker: 'IPG', name: 'Interpublic Group', industry: 'Communication Services' },
  { ticker: 'TTWO', name: 'Take-Two Interactive', industry: 'Communication Services' },
  { ticker: 'EA', name: 'Electronic Arts', industry: 'Communication Services' },
  { ticker: 'MTCH', name: 'Match Group Inc.', industry: 'Communication Services' },
  { ticker: 'PINS', name: 'Pinterest Inc.', industry: 'Communication Services' },
  { ticker: 'SNAP', name: 'Snap Inc.', industry: 'Communication Services' },
  { ticker: 'LYFT', name: 'Lyft Inc.', industry: 'Communication Services' },
  { ticker: 'UBER', name: 'Uber Technologies', industry: 'Communication Services' },
  { ticker: 'DASH', name: 'DoorDash Inc.', industry: 'Communication Services' },
  { ticker: 'ABNB', name: 'Airbnb Inc.', industry: 'Communication Services' },
  { ticker: 'BKNG', name: 'Booking Holdings', industry: 'Communication Services' },
  { ticker: 'EXPE', name: 'Expedia Group', industry: 'Communication Services' },
  { ticker: 'IAC', name: 'IAC Inc.', industry: 'Communication Services' },
  { ticker: 'ZG', name: 'Zillow Group', industry: 'Communication Services' },

  // Consumer Discretionary
  { ticker: 'AMZN', name: 'Amazon.com Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'TSLA', name: 'Tesla Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'HD', name: 'Home Depot Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'MCD', name: "McDonald's Corp.", industry: 'Consumer Discretionary' },
  { ticker: 'NKE', name: 'Nike Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'SBUX', name: 'Starbucks Corp.', industry: 'Consumer Discretionary' },
  { ticker: 'LOW', name: "Lowe's Companies", industry: 'Consumer Discretionary' },
  { ticker: 'TJX', name: 'TJX Companies', industry: 'Consumer Discretionary' },
  { ticker: 'BKNG', name: 'Booking Holdings', industry: 'Consumer Discretionary' },
  { ticker: 'CMG', name: 'Chipotle Mexican Grill', industry: 'Consumer Discretionary' },
  { ticker: 'F', name: 'Ford Motor Company', industry: 'Consumer Discretionary' },
  { ticker: 'GM', name: 'General Motors Co.', industry: 'Consumer Discretionary' },
  { ticker: 'TGT', name: 'Target Corporation', industry: 'Consumer Discretionary' },
  { ticker: 'ROST', name: 'Ross Stores Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'ORLY', name: "O'Reilly Automotive", industry: 'Consumer Discretionary' },
  { ticker: 'AZO', name: 'AutoZone Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'BBY', name: 'Best Buy Co.', industry: 'Consumer Discretionary' },
  { ticker: 'DRI', name: 'Darden Restaurants', industry: 'Consumer Discretionary' },
  { ticker: 'YUM', name: 'Yum! Brands Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'QSR', name: 'Restaurant Brands Intl', industry: 'Consumer Discretionary' },
  { ticker: 'DPZ', name: "Domino's Pizza", industry: 'Consumer Discretionary' },
  { ticker: 'HLT', name: 'Hilton Worldwide', industry: 'Consumer Discretionary' },
  { ticker: 'MAR', name: 'Marriott International', industry: 'Consumer Discretionary' },
  { ticker: 'H', name: 'Hyatt Hotels Corp.', industry: 'Consumer Discretionary' },
  { ticker: 'WYNN', name: 'Wynn Resorts', industry: 'Consumer Discretionary' },
  { ticker: 'LVS', name: 'Las Vegas Sands', industry: 'Consumer Discretionary' },
  { ticker: 'MGM', name: 'MGM Resorts International', industry: 'Consumer Discretionary' },
  { ticker: 'CCL', name: 'Carnival Corporation', industry: 'Consumer Discretionary' },
  { ticker: 'RCL', name: 'Royal Caribbean Group', industry: 'Consumer Discretionary' },
  { ticker: 'NCLH', name: 'Norwegian Cruise Line', industry: 'Consumer Discretionary' },
  { ticker: 'EBAY', name: 'eBay Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'ETSY', name: 'Etsy Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'W', name: 'Wayfair Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'CVNA', name: 'Carvana Co.', industry: 'Consumer Discretionary' },
  { ticker: 'AN', name: 'AutoNation Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'KMX', name: 'CarMax Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'APTV', name: 'Aptiv plc', industry: 'Consumer Discretionary' },
  { ticker: 'BWA', name: 'BorgWarner Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'LEA', name: 'Lear Corporation', industry: 'Consumer Discretionary' },
  { ticker: 'RL', name: 'Ralph Lauren Corp.', industry: 'Consumer Discretionary' },
  { ticker: 'PVH', name: 'PVH Corp.', industry: 'Consumer Discretionary' },
  { ticker: 'TPR', name: 'Tapestry Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'HBI', name: 'Hanesbrands Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'VFC', name: 'VF Corporation', industry: 'Consumer Discretionary' },
  { ticker: 'LULU', name: 'Lululemon Athletica', industry: 'Consumer Discretionary' },
  { ticker: 'UAA', name: 'Under Armour Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'DECK', name: 'Deckers Outdoor Corp.', industry: 'Consumer Discretionary' },
  { ticker: 'ONON', name: 'On Holding AG', industry: 'Consumer Discretionary' },

  // Consumer Staples
  { ticker: 'WMT', name: 'Walmart Inc.', industry: 'Consumer Staples' },
  { ticker: 'PG', name: 'Procter & Gamble Co.', industry: 'Consumer Staples' },
  { ticker: 'KO', name: 'Coca-Cola Co.', industry: 'Consumer Staples' },
  { ticker: 'PEP', name: 'PepsiCo Inc.', industry: 'Consumer Staples' },
  { ticker: 'COST', name: 'Costco Wholesale Corp.', industry: 'Consumer Staples' },
  { ticker: 'PM', name: 'Philip Morris International', industry: 'Consumer Staples' },
  { ticker: 'MO', name: 'Altria Group Inc.', industry: 'Consumer Staples' },
  { ticker: 'MDLZ', name: 'Mondelez International', industry: 'Consumer Staples' },
  { ticker: 'CL', name: 'Colgate-Palmolive Co.', industry: 'Consumer Staples' },
  { ticker: 'KMB', name: 'Kimberly-Clark Corp.', industry: 'Consumer Staples' },
  { ticker: 'GIS', name: 'General Mills Inc.', industry: 'Consumer Staples' },
  { ticker: 'K', name: "Kellogg's (WK Kellogg)", industry: 'Consumer Staples' },
  { ticker: 'CPB', name: "Campbell Soup Co.", industry: 'Consumer Staples' },
  { ticker: 'HRL', name: 'Hormel Foods Corp.', industry: 'Consumer Staples' },
  { ticker: 'SJM', name: 'J.M. Smucker Co.', industry: 'Consumer Staples' },
  { ticker: 'MKC', name: 'McCormick & Company', industry: 'Consumer Staples' },
  { ticker: 'HSY', name: 'Hershey Company', industry: 'Consumer Staples' },
  { ticker: 'TSN', name: 'Tyson Foods Inc.', industry: 'Consumer Staples' },
  { ticker: 'CAG', name: 'Conagra Brands Inc.', industry: 'Consumer Staples' },
  { ticker: 'KR', name: 'Kroger Co.', industry: 'Consumer Staples' },
  { ticker: 'SYY', name: 'Sysco Corporation', industry: 'Consumer Staples' },
  { ticker: 'ADM', name: 'Archer-Daniels-Midland', industry: 'Consumer Staples' },
  { ticker: 'BG', name: 'Bunge Global SA', industry: 'Consumer Staples' },
  { ticker: 'CLX', name: 'Clorox Company', industry: 'Consumer Staples' },
  { ticker: 'CHD', name: 'Church & Dwight Co.', industry: 'Consumer Staples' },
  { ticker: 'COTY', name: 'Coty Inc.', industry: 'Consumer Staples' },
  { ticker: 'EL', name: 'Estee Lauder Companies', industry: 'Consumer Staples' },
  { ticker: 'KVUE', name: 'Kenvue Inc.', industry: 'Consumer Staples' },
  { ticker: 'REYN', name: 'Reynolds Consumer Products', industry: 'Consumer Staples' },
  { ticker: 'CELH', name: 'Celsius Holdings Inc.', industry: 'Consumer Staples' },

  // Financials
  { ticker: 'JPM', name: 'JPMorgan Chase & Co.', industry: 'Financials' },
  { ticker: 'BAC', name: 'Bank of America Corp.', industry: 'Financials' },
  { ticker: 'WFC', name: 'Wells Fargo & Co.', industry: 'Financials' },
  { ticker: 'GS', name: 'Goldman Sachs Group', industry: 'Financials' },
  { ticker: 'MS', name: 'Morgan Stanley', industry: 'Financials' },
  { ticker: 'C', name: 'Citigroup Inc.', industry: 'Financials' },
  { ticker: 'USB', name: 'U.S. Bancorp', industry: 'Financials' },
  { ticker: 'PNC', name: 'PNC Financial Services', industry: 'Financials' },
  { ticker: 'TFC', name: 'Truist Financial Corp.', industry: 'Financials' },
  { ticker: 'COF', name: 'Capital One Financial', industry: 'Financials' },
  { ticker: 'AXP', name: 'American Express Co.', industry: 'Financials' },
  { ticker: 'V', name: 'Visa Inc.', industry: 'Financials' },
  { ticker: 'MA', name: 'Mastercard Inc.', industry: 'Financials' },
  { ticker: 'PYPL', name: 'PayPal Holdings', industry: 'Financials' },
  { ticker: 'SQ', name: 'Block Inc.', industry: 'Financials' },
  { ticker: 'COIN', name: 'Coinbase Global', industry: 'Financials' },
  { ticker: 'BRK.B', name: 'Berkshire Hathaway', industry: 'Financials' },
  { ticker: 'BLK', name: 'BlackRock Inc.', industry: 'Financials' },
  { ticker: 'SCHW', name: 'Charles Schwab Corp.', industry: 'Financials' },
  { ticker: 'IBKR', name: 'Interactive Brokers', industry: 'Financials' },
  { ticker: 'RJF', name: 'Raymond James Financial', industry: 'Financials' },
  { ticker: 'LPLA', name: 'LPL Financial Holdings', industry: 'Financials' },
  { ticker: 'STT', name: 'State Street Corp.', industry: 'Financials' },
  { ticker: 'BK', name: 'Bank of New York Mellon', industry: 'Financials' },
  { ticker: 'NTRS', name: 'Northern Trust Corp.', industry: 'Financials' },
  { ticker: 'FDS', name: 'FactSet Research Systems', industry: 'Financials' },
  { ticker: 'MSCI', name: 'MSCI Inc.', industry: 'Financials' },
  { ticker: 'SPGI', name: 'S&P Global Inc.', industry: 'Financials' },
  { ticker: 'MCO', name: "Moody's Corporation", industry: 'Financials' },
  { ticker: 'ICE', name: 'Intercontinental Exchange', industry: 'Financials' },
  { ticker: 'CME', name: 'CME Group Inc.', industry: 'Financials' },
  { ticker: 'CBOE', name: 'Cboe Global Markets', industry: 'Financials' },
  { ticker: 'NDAQ', name: 'Nasdaq Inc.', industry: 'Financials' },
  { ticker: 'FIS', name: 'Fidelity National Info', industry: 'Financials' },
  { ticker: 'FISV', name: 'Fiserv Inc.', industry: 'Financials' },
  { ticker: 'GPN', name: 'Global Payments Inc.', industry: 'Financials' },
  { ticker: 'WEX', name: 'WEX Inc.', industry: 'Financials' },
  { ticker: 'ALLY', name: 'Ally Financial Inc.', industry: 'Financials' },
  { ticker: 'SYF', name: 'Synchrony Financial', industry: 'Financials' },
  { ticker: 'DFS', name: 'Discover Financial Services', industry: 'Financials' },
  { ticker: 'AIG', name: 'American International Group', industry: 'Financials' },
  { ticker: 'MET', name: 'MetLife Inc.', industry: 'Financials' },
  { ticker: 'PRU', name: 'Prudential Financial', industry: 'Financials' },
  { ticker: 'AFL', name: 'Aflac Inc.', industry: 'Financials' },
  { ticker: 'ALL', name: 'Allstate Corporation', industry: 'Financials' },
  { ticker: 'PGR', name: 'Progressive Corporation', industry: 'Financials' },
  { ticker: 'TRV', name: 'Travelers Companies', industry: 'Financials' },
  { ticker: 'CB', name: 'Chubb Limited', industry: 'Financials' },
  { ticker: 'AON', name: 'Aon plc', industry: 'Financials' },
  { ticker: 'MMC', name: 'Marsh & McLennan', industry: 'Financials' },
  { ticker: 'WTW', name: 'Willis Towers Watson', industry: 'Financials' },
  { ticker: 'RE', name: 'Everest Group', industry: 'Financials' },
  { ticker: 'HIG', name: 'Hartford Financial Services', industry: 'Financials' },
  { ticker: 'GL', name: 'Globe Life Inc.', industry: 'Financials' },
  { ticker: 'LNC', name: 'Lincoln National Corp.', industry: 'Financials' },
  { ticker: 'UNM', name: 'Unum Group', industry: 'Financials' },
  { ticker: 'CINF', name: 'Cincinnati Financial', industry: 'Financials' },
  { ticker: 'EG', name: 'Everest Group Ltd.', industry: 'Financials' },
  { ticker: 'RNR', name: 'RenaissanceRe Holdings', industry: 'Financials' },
  { ticker: 'ACGL', name: 'Arch Capital Group', industry: 'Financials' },

  // Healthcare
  { ticker: 'LLY', name: 'Eli Lilly & Co.', industry: 'Healthcare' },
  { ticker: 'UNH', name: 'UnitedHealth Group', industry: 'Healthcare' },
  { ticker: 'JNJ', name: 'Johnson & Johnson', industry: 'Healthcare' },
  { ticker: 'MRK', name: 'Merck & Co.', industry: 'Healthcare' },
  { ticker: 'ABBV', name: 'AbbVie Inc.', industry: 'Healthcare' },
  { ticker: 'PFE', name: 'Pfizer Inc.', industry: 'Healthcare' },
  { ticker: 'BMY', name: 'Bristol-Myers Squibb', industry: 'Healthcare' },
  { ticker: 'AMGN', name: 'Amgen Inc.', industry: 'Healthcare' },
  { ticker: 'GILD', name: 'Gilead Sciences', industry: 'Healthcare' },
  { ticker: 'BIIB', name: 'Biogen Inc.', industry: 'Healthcare' },
  { ticker: 'REGN', name: 'Regeneron Pharmaceuticals', industry: 'Healthcare' },
  { ticker: 'VRTX', name: 'Vertex Pharmaceuticals', industry: 'Healthcare' },
  { ticker: 'MRNA', name: 'Moderna Inc.', industry: 'Healthcare' },
  { ticker: 'BNTX', name: 'BioNTech SE', industry: 'Healthcare' },
  { ticker: 'ISRG', name: 'Intuitive Surgical', industry: 'Healthcare' },
  { ticker: 'ABT', name: 'Abbott Laboratories', industry: 'Healthcare' },
  { ticker: 'MDT', name: 'Medtronic plc', industry: 'Healthcare' },
  { ticker: 'BSX', name: 'Boston Scientific Corp.', industry: 'Healthcare' },
  { ticker: 'EW', name: 'Edwards Lifesciences', industry: 'Healthcare' },
  { ticker: 'SYK', name: 'Stryker Corporation', industry: 'Healthcare' },
  { ticker: 'ZBH', name: 'Zimmer Biomet Holdings', industry: 'Healthcare' },
  { ticker: 'BAX', name: 'Baxter International', industry: 'Healthcare' },
  { ticker: 'BDX', name: 'Becton Dickinson & Co.', industry: 'Healthcare' },
  { ticker: 'DHR', name: 'Danaher Corporation', industry: 'Healthcare' },
  { ticker: 'TMO', name: 'Thermo Fisher Scientific', industry: 'Healthcare' },
  { ticker: 'A', name: 'Agilent Technologies', industry: 'Healthcare' },
  { ticker: 'IDXX', name: 'IDEXX Laboratories', industry: 'Healthcare' },
  { ticker: 'IQV', name: 'IQVIA Holdings', industry: 'Healthcare' },
  { ticker: 'CRL', name: 'Charles River Laboratories', industry: 'Healthcare' },
  { ticker: 'TECH', name: 'Bio-Techne Corp.', industry: 'Healthcare' },
  { ticker: 'CVS', name: 'CVS Health Corp.', industry: 'Healthcare' },
  { ticker: 'CI', name: 'Cigna Group', industry: 'Healthcare' },
  { ticker: 'ELV', name: 'Elevance Health', industry: 'Healthcare' },
  { ticker: 'HUM', name: 'Humana Inc.', industry: 'Healthcare' },
  { ticker: 'CNC', name: 'Centene Corporation', industry: 'Healthcare' },
  { ticker: 'MOH', name: 'Molina Healthcare', industry: 'Healthcare' },
  { ticker: 'MCK', name: 'McKesson Corporation', industry: 'Healthcare' },
  { ticker: 'CAH', name: 'Cardinal Health Inc.', industry: 'Healthcare' },
  { ticker: 'ABC', name: 'AmerisourceBergen Corp.', industry: 'Healthcare' },
  { ticker: 'HSIC', name: 'Henry Schein Inc.', industry: 'Healthcare' },
  { ticker: 'HOLX', name: 'Hologic Inc.', industry: 'Healthcare' },
  { ticker: 'ALGN', name: 'Align Technology', industry: 'Healthcare' },
  { ticker: 'DXCM', name: 'DexCom Inc.', industry: 'Healthcare' },
  { ticker: 'PODD', name: 'Insulet Corporation', industry: 'Healthcare' },
  { ticker: 'NTRA', name: 'Natera Inc.', industry: 'Healthcare' },
  { ticker: 'EXAS', name: 'Exact Sciences Corp.', industry: 'Healthcare' },
  { ticker: 'ILMN', name: 'Illumina Inc.', industry: 'Healthcare' },
  { ticker: 'PACB', name: 'Pacific Biosciences', industry: 'Healthcare' },
  { ticker: 'NVAX', name: 'Novavax Inc.', industry: 'Healthcare' },
  { ticker: 'RXRX', name: 'Recursion Pharmaceuticals', industry: 'Healthcare' },

  // Energy
  { ticker: 'XOM', name: 'Exxon Mobil Corp.', industry: 'Energy' },
  { ticker: 'CVX', name: 'Chevron Corporation', industry: 'Energy' },
  { ticker: 'COP', name: 'ConocoPhillips', industry: 'Energy' },
  { ticker: 'EOG', name: 'EOG Resources', industry: 'Energy' },
  { ticker: 'SLB', name: 'Schlumberger Ltd.', industry: 'Energy' },
  { ticker: 'MPC', name: 'Marathon Petroleum Corp.', industry: 'Energy' },
  { ticker: 'PSX', name: 'Phillips 66', industry: 'Energy' },
  { ticker: 'VLO', name: 'Valero Energy Corp.', industry: 'Energy' },
  { ticker: 'OXY', name: 'Occidental Petroleum', industry: 'Energy' },
  { ticker: 'DVN', name: 'Devon Energy Corp.', industry: 'Energy' },
  { ticker: 'FANG', name: 'Diamondback Energy', industry: 'Energy' },
  { ticker: 'PXD', name: 'Pioneer Natural Resources', industry: 'Energy' },
  { ticker: 'HAL', name: 'Halliburton Company', industry: 'Energy' },
  { ticker: 'BKR', name: 'Baker Hughes Company', industry: 'Energy' },
  { ticker: 'KMI', name: 'Kinder Morgan Inc.', industry: 'Energy' },
  { ticker: 'WMB', name: 'Williams Companies', industry: 'Energy' },
  { ticker: 'OKE', name: 'ONEOK Inc.', industry: 'Energy' },
  { ticker: 'LNG', name: 'Cheniere Energy Inc.', industry: 'Energy' },
  { ticker: 'CTRA', name: 'Coterra Energy Inc.', industry: 'Energy' },
  { ticker: 'APA', name: 'APA Corporation', industry: 'Energy' },
  { ticker: 'MRO', name: 'Marathon Oil Corp.', industry: 'Energy' },
  { ticker: 'HES', name: 'Hess Corporation', industry: 'Energy' },
  { ticker: 'TRGP', name: 'Targa Resources Corp.', industry: 'Energy' },
  { ticker: 'AM', name: 'Antero Midstream Corp.', industry: 'Energy' },
  { ticker: 'AR', name: 'Antero Resources Corp.', industry: 'Energy' },
  { ticker: 'RRC', name: 'Range Resources Corp.', industry: 'Energy' },
  { ticker: 'EQT', name: 'EQT Corporation', industry: 'Energy' },
  { ticker: 'CNX', name: 'CNX Resources Corp.', industry: 'Energy' },
  { ticker: 'NOV', name: 'NOV Inc.', industry: 'Energy' },
  { ticker: 'PTEN', name: 'Patterson-UTI Energy', industry: 'Energy' },

  // Industrials
  { ticker: 'CAT', name: 'Caterpillar Inc.', industry: 'Industrials' },
  { ticker: 'DE', name: 'Deere & Company', industry: 'Industrials' },
  { ticker: 'BA', name: 'Boeing Company', industry: 'Industrials' },
  { ticker: 'RTX', name: 'RTX Corporation', industry: 'Industrials' },
  { ticker: 'LMT', name: 'Lockheed Martin Corp.', industry: 'Industrials' },
  { ticker: 'NOC', name: 'Northrop Grumman Corp.', industry: 'Industrials' },
  { ticker: 'GD', name: 'General Dynamics Corp.', industry: 'Industrials' },
  { ticker: 'HII', name: 'Huntington Ingalls Industries', industry: 'Industrials' },
  { ticker: 'LHX', name: 'L3Harris Technologies', industry: 'Industrials' },
  { ticker: 'TDG', name: 'TransDigm Group', industry: 'Industrials' },
  { ticker: 'HWM', name: 'Howmet Aerospace', industry: 'Industrials' },
  { ticker: 'SPR', name: 'Spirit AeroSystems', industry: 'Industrials' },
  { ticker: 'GE', name: 'GE Aerospace', industry: 'Industrials' },
  { ticker: 'GEV', name: 'GE Vernova Inc.', industry: 'Industrials' },
  { ticker: 'HON', name: 'Honeywell International', industry: 'Industrials' },
  { ticker: 'MMM', name: '3M Company', industry: 'Industrials' },
  { ticker: 'EMR', name: 'Emerson Electric Co.', industry: 'Industrials' },
  { ticker: 'ETN', name: 'Eaton Corporation', industry: 'Industrials' },
  { ticker: 'PH', name: 'Parker Hannifin Corp.', industry: 'Industrials' },
  { ticker: 'ITW', name: 'Illinois Tool Works', industry: 'Industrials' },
  { ticker: 'DOV', name: 'Dover Corporation', industry: 'Industrials' },
  { ticker: 'IR', name: 'Ingersoll Rand Inc.', industry: 'Industrials' },
  { ticker: 'AME', name: 'AMETEK Inc.', industry: 'Industrials' },
  { ticker: 'FTV', name: 'Fortive Corporation', industry: 'Industrials' },
  { ticker: 'GNRC', name: 'Generac Holdings', industry: 'Industrials' },
  { ticker: 'XYL', name: 'Xylem Inc.', industry: 'Industrials' },
  { ticker: 'IEX', name: 'IDEX Corporation', industry: 'Industrials' },
  { ticker: 'GWW', name: 'W.W. Grainger Inc.', industry: 'Industrials' },
  { ticker: 'FAST', name: 'Fastenal Company', industry: 'Industrials' },
  { ticker: 'MSC', name: 'MSC Industrial Direct', industry: 'Industrials' },
  { ticker: 'FDX', name: 'FedEx Corporation', industry: 'Industrials' },
  { ticker: 'UPS', name: 'United Parcel Service', industry: 'Industrials' },
  { ticker: 'CSX', name: 'CSX Corporation', industry: 'Industrials' },
  { ticker: 'NSC', name: 'Norfolk Southern Corp.', industry: 'Industrials' },
  { ticker: 'UNP', name: 'Union Pacific Corp.', industry: 'Industrials' },
  { ticker: 'CP', name: 'Canadian Pacific Kansas City', industry: 'Industrials' },
  { ticker: 'CNI', name: 'Canadian National Railway', industry: 'Industrials' },
  { ticker: 'DAL', name: 'Delta Air Lines', industry: 'Industrials' },
  { ticker: 'UAL', name: 'United Airlines Holdings', industry: 'Industrials' },
  { ticker: 'AAL', name: 'American Airlines Group', industry: 'Industrials' },
  { ticker: 'LUV', name: 'Southwest Airlines', industry: 'Industrials' },
  { ticker: 'ALK', name: 'Alaska Air Group', industry: 'Industrials' },
  { ticker: 'JBLU', name: 'JetBlue Airways', industry: 'Industrials' },
  { ticker: 'EXPD', name: 'Expeditors International', industry: 'Industrials' },
  { ticker: 'CHRW', name: 'C.H. Robinson Worldwide', industry: 'Industrials' },
  { ticker: 'ODFL', name: 'Old Dominion Freight Line', industry: 'Industrials' },
  { ticker: 'SAIA', name: 'Saia Inc.', industry: 'Industrials' },
  { ticker: 'JBHT', name: 'J.B. Hunt Transport', industry: 'Industrials' },
  { ticker: 'WERN', name: 'Werner Enterprises', industry: 'Industrials' },
  { ticker: 'WAB', name: 'Westinghouse Air Brake', industry: 'Industrials' },

  // Materials
  { ticker: 'LIN', name: 'Linde plc', industry: 'Materials' },
  { ticker: 'APD', name: 'Air Products & Chemicals', industry: 'Materials' },
  { ticker: 'SHW', name: 'Sherwin-Williams Co.', industry: 'Materials' },
  { ticker: 'ECL', name: 'Ecolab Inc.', industry: 'Materials' },
  { ticker: 'PPG', name: 'PPG Industries', industry: 'Materials' },
  { ticker: 'NEM', name: 'Newmont Corporation', industry: 'Materials' },
  { ticker: 'FCX', name: 'Freeport-McMoRan Inc.', industry: 'Materials' },
  { ticker: 'NUE', name: 'Nucor Corporation', industry: 'Materials' },
  { ticker: 'STLD', name: 'Steel Dynamics Inc.', industry: 'Materials' },
  { ticker: 'X', name: 'U.S. Steel Corporation', industry: 'Materials' },
  { ticker: 'RS', name: 'Reliance Steel & Aluminum', industry: 'Materials' },
  { ticker: 'CF', name: 'CF Industries Holdings', industry: 'Materials' },
  { ticker: 'MOS', name: 'Mosaic Company', industry: 'Materials' },
  { ticker: 'FMC', name: 'FMC Corporation', industry: 'Materials' },
  { ticker: 'CE', name: 'Celanese Corporation', industry: 'Materials' },
  { ticker: 'DD', name: 'DuPont de Nemours', industry: 'Materials' },
  { ticker: 'DOW', name: 'Dow Inc.', industry: 'Materials' },
  { ticker: 'LYB', name: 'LyondellBasell Industries', industry: 'Materials' },
  { ticker: 'EMN', name: 'Eastman Chemical Co.', industry: 'Materials' },
  { ticker: 'AVY', name: 'Avery Dennison Corp.', industry: 'Materials' },
  { ticker: 'PKG', name: 'Packaging Corp. of America', industry: 'Materials' },
  { ticker: 'IP', name: 'International Paper Co.', industry: 'Materials' },
  { ticker: 'WRK', name: 'WestRock Company', industry: 'Materials' },
  { ticker: 'SEE', name: 'Sealed Air Corporation', industry: 'Materials' },
  { ticker: 'BALL', name: 'Ball Corporation', industry: 'Materials' },
  { ticker: 'CCK', name: 'Crown Holdings Inc.', industry: 'Materials' },
  { ticker: 'OLN', name: 'Olin Corporation', industry: 'Materials' },
  { ticker: 'RPM', name: 'RPM International Inc.', industry: 'Materials' },
  { ticker: 'IFF', name: 'Intl Flavors & Fragrances', industry: 'Materials' },
  { ticker: 'ALB', name: 'Albemarle Corporation', industry: 'Materials' },

  // Real Estate
  { ticker: 'PLD', name: 'Prologis Inc.', industry: 'Real Estate' },
  { ticker: 'AMT', name: 'American Tower Corp.', industry: 'Real Estate' },
  { ticker: 'EQIX', name: 'Equinix Inc.', industry: 'Real Estate' },
  { ticker: 'CCI', name: 'Crown Castle Inc.', industry: 'Real Estate' },
  { ticker: 'SBAC', name: 'SBA Communications', industry: 'Real Estate' },
  { ticker: 'SPG', name: 'Simon Property Group', industry: 'Real Estate' },
  { ticker: 'O', name: 'Realty Income Corp.', industry: 'Real Estate' },
  { ticker: 'WPC', name: 'W. P. Carey Inc.', industry: 'Real Estate' },
  { ticker: 'NNN', name: 'NNN REIT Inc.', industry: 'Real Estate' },
  { ticker: 'VICI', name: 'VICI Properties Inc.', industry: 'Real Estate' },
  { ticker: 'GLPI', name: 'Gaming & Leisure Properties', industry: 'Real Estate' },
  { ticker: 'EXR', name: 'Extra Space Storage', industry: 'Real Estate' },
  { ticker: 'PSA', name: 'Public Storage', industry: 'Real Estate' },
  { ticker: 'CUBE', name: 'CubeSmart', industry: 'Real Estate' },
  { ticker: 'EQR', name: 'Equity Residential', industry: 'Real Estate' },
  { ticker: 'AVB', name: 'AvalonBay Communities', industry: 'Real Estate' },
  { ticker: 'ESS', name: 'Essex Property Trust', industry: 'Real Estate' },
  { ticker: 'UDR', name: 'UDR Inc.', industry: 'Real Estate' },
  { ticker: 'CPT', name: 'Camden Property Trust', industry: 'Real Estate' },
  { ticker: 'MAA', name: 'Mid-America Apartment', industry: 'Real Estate' },
  { ticker: 'ARE', name: 'Alexandria Real Estate', industry: 'Real Estate' },
  { ticker: 'BXP', name: 'BXP Inc.', industry: 'Real Estate' },
  { ticker: 'VNO', name: 'Vornado Realty Trust', industry: 'Real Estate' },
  { ticker: 'SLG', name: 'SL Green Realty Corp.', industry: 'Real Estate' },
  { ticker: 'KIM', name: 'Kimco Realty Corp.', industry: 'Real Estate' },
  { ticker: 'REG', name: 'Regency Centers Corp.', industry: 'Real Estate' },
  { ticker: 'FRT', name: 'Federal Realty Investment', industry: 'Real Estate' },
  { ticker: 'WRI', name: 'Weingarten Realty', industry: 'Real Estate' },
  { ticker: 'WELL', name: 'Welltower Inc.', industry: 'Real Estate' },
  { ticker: 'VTR', name: 'Ventas Inc.', industry: 'Real Estate' },
  { ticker: 'PEAK', name: 'Healthpeak Properties', industry: 'Real Estate' },
  { ticker: 'HR', name: 'Healthcare Realty Trust', industry: 'Real Estate' },
  { ticker: 'DOC', name: 'Physicians Realty Trust', industry: 'Real Estate' },
  { ticker: 'DLR', name: 'Digital Realty Trust', industry: 'Real Estate' },
  { ticker: 'QTS', name: 'QTS Realty Trust', industry: 'Real Estate' },
  { ticker: 'CONE', name: 'CyrusOne Inc.', industry: 'Real Estate' },
  { ticker: 'IRM', name: 'Iron Mountain Inc.', industry: 'Real Estate' },
  { ticker: 'COLD', name: 'Americold Realty Trust', industry: 'Real Estate' },
  { ticker: 'STAG', name: 'STAG Industrial Inc.', industry: 'Real Estate' },
  { ticker: 'REXR', name: 'Rexford Industrial Realty', industry: 'Real Estate' },

  // Utilities
  { ticker: 'NEE', name: 'NextEra Energy Inc.', industry: 'Utilities' },
  { ticker: 'DUK', name: 'Duke Energy Corp.', industry: 'Utilities' },
  { ticker: 'SO', name: 'Southern Company', industry: 'Utilities' },
  { ticker: 'D', name: 'Dominion Energy Inc.', industry: 'Utilities' },
  { ticker: 'AEP', name: 'American Electric Power', industry: 'Utilities' },
  { ticker: 'EXC', name: 'Exelon Corporation', industry: 'Utilities' },
  { ticker: 'XEL', name: 'Xcel Energy Inc.', industry: 'Utilities' },
  { ticker: 'PCG', name: 'PG&E Corporation', industry: 'Utilities' },
  { ticker: 'ED', name: 'Consolidated Edison', industry: 'Utilities' },
  { ticker: 'EIX', name: 'Edison International', industry: 'Utilities' },
  { ticker: 'PPL', name: 'PPL Corporation', industry: 'Utilities' },
  { ticker: 'WEC', name: 'WEC Energy Group', industry: 'Utilities' },
  { ticker: 'ES', name: 'Eversource Energy', industry: 'Utilities' },
  { ticker: 'FE', name: 'FirstEnergy Corp.', industry: 'Utilities' },
  { ticker: 'ETR', name: 'Entergy Corporation', industry: 'Utilities' },
  { ticker: 'AES', name: 'AES Corporation', industry: 'Utilities' },
  { ticker: 'CMS', name: 'CMS Energy Corp.', industry: 'Utilities' },
  { ticker: 'LNT', name: 'Alliant Energy Corp.', industry: 'Utilities' },
  { ticker: 'EVRG', name: 'Evergy Inc.', industry: 'Utilities' },
  { ticker: 'NI', name: 'NiSource Inc.', industry: 'Utilities' },
  { ticker: 'AWK', name: 'American Water Works', industry: 'Utilities' },
  { ticker: 'SRE', name: 'Sempra Energy', industry: 'Utilities' },
  { ticker: 'CNP', name: 'CenterPoint Energy', industry: 'Utilities' },
  { ticker: 'NRG', name: 'NRG Energy Inc.', industry: 'Utilities' },
  { ticker: 'VST', name: 'Vistra Corp.', industry: 'Utilities' },
  { ticker: 'CEG', name: 'Constellation Energy', industry: 'Utilities' },
  { ticker: 'NWE', name: 'NorthWestern Energy', industry: 'Utilities' },
  { ticker: 'OTTR', name: 'Otter Tail Corporation', industry: 'Utilities' },
  { ticker: 'IDACORP', name: 'IDACORP Inc.', industry: 'Utilities' },
  { ticker: 'POR', name: 'Portland General Electric', industry: 'Utilities' },

  // Crypto (non-S&P but commonly tracked)
  { ticker: 'BTC', name: 'Bitcoin (via ETF)', industry: 'Crypto' },
  { ticker: 'ETH', name: 'Ethereum (via ETF)', industry: 'Crypto' },
  { ticker: 'MSTR', name: 'MicroStrategy Inc.', industry: 'Crypto' },
  { ticker: 'COIN', name: 'Coinbase Global', industry: 'Financials' },

  // ETFs
  { ticker: 'SPY', name: 'SPDR S&P 500 ETF', industry: 'ETF' },
  { ticker: 'QQQ', name: 'Invesco QQQ Trust ETF', industry: 'ETF' },
  { ticker: 'IWM', name: 'iShares Russell 2000 ETF', industry: 'ETF' },
  { ticker: 'VTI', name: 'Vanguard Total Stock Market', industry: 'ETF' },
  { ticker: 'VOO', name: 'Vanguard S&P 500 ETF', industry: 'ETF' },
  { ticker: 'VGT', name: 'Vanguard IT ETF', industry: 'ETF' },
  { ticker: 'XLK', name: 'Technology Select SPDR', industry: 'ETF' },
  { ticker: 'XLF', name: 'Financial Select SPDR', industry: 'ETF' },
  { ticker: 'XLV', name: 'Health Care Select SPDR', industry: 'ETF' },
  { ticker: 'XLE', name: 'Energy Select SPDR', industry: 'ETF' },
  { ticker: 'ARKK', name: 'ARK Innovation ETF', industry: 'ETF' },
  { ticker: 'ARKG', name: 'ARK Genomic Revolution ETF', industry: 'ETF' },
  { ticker: 'ARKW', name: 'ARK Next Gen Internet ETF', industry: 'ETF' },
  { ticker: 'GLD', name: 'SPDR Gold Shares ETF', industry: 'ETF' },
  { ticker: 'SLV', name: 'iShares Silver Trust ETF', industry: 'ETF' },
  { ticker: 'TLT', name: 'iShares 20+ Year Treasury', industry: 'ETF' },
  { ticker: 'HYG', name: 'iShares High Yield Corp Bond', industry: 'ETF' },
  { ticker: 'SQQQ', name: 'ProShares UltraPro Short QQQ', industry: 'ETF' },
  { ticker: 'TQQQ', name: 'ProShares UltraPro QQQ', industry: 'ETF' },
  { ticker: 'SOXL', name: 'Direxion Semi Bull 3X', industry: 'ETF' },
];
