// Comprehensive NYSE + NASDAQ Stock Catalog
// Covers major indices: S&P 500, NASDAQ 100, Russell 2000, and popular individual stocks
// Including: LEU, SOFI, HIMS, PLTR, RKLB, ASTS, IONQ, RGTI, and thousands more
import type { Industry } from './types';

export interface SP500Stock {
  ticker: string;
  name: string;
  industry: Industry;
}

export const SP500_STOCKS: SP500Stock[] = [
  { ticker: 'AAPL', name: 'Apple Inc.', industry: 'Technology' },
  { ticker: 'MSFT', name: 'Microsoft Corp.', industry: 'Technology' },
  { ticker: 'NVDA', name: 'NVIDIA Corp.', industry: 'Technology' },
  { ticker: 'AMD', name: 'Advanced Micro Devices', industry: 'Technology' },
  { ticker: 'INTC', name: 'Intel Corporation', industry: 'Technology' },
  { ticker: 'QCOM', name: 'Qualcomm Inc.', industry: 'Technology' },
  { ticker: 'AVGO', name: 'Broadcom Inc.', industry: 'Technology' },
  { ticker: 'TXN', name: 'Texas Instruments', industry: 'Technology' },
  { ticker: 'MU', name: 'Micron Technology', industry: 'Technology' },
  { ticker: 'AMAT', name: 'Applied Materials', industry: 'Technology' },
  { ticker: 'LRCX', name: 'Lam Research', industry: 'Technology' },
  { ticker: 'KLAC', name: 'KLA Corporation', industry: 'Technology' },
  { ticker: 'MRVL', name: 'Marvell Technology', industry: 'Technology' },
  { ticker: 'NXPI', name: 'NXP Semiconductors', industry: 'Technology' },
  { ticker: 'ON', name: 'ON Semiconductor', industry: 'Technology' },
  { ticker: 'SWKS', name: 'Skyworks Solutions', industry: 'Technology' },
  { ticker: 'QRVO', name: 'Qorvo Inc.', industry: 'Technology' },
  { ticker: 'ADI', name: 'Analog Devices', industry: 'Technology' },
  { ticker: 'MCHP', name: 'Microchip Technology', industry: 'Technology' },
  { ticker: 'STX', name: 'Seagate Technology', industry: 'Technology' },
  { ticker: 'WDC', name: 'Western Digital', industry: 'Technology' },
  { ticker: 'HPQ', name: 'HP Inc.', industry: 'Technology' },
  { ticker: 'HPE', name: 'Hewlett Packard Enterprise', industry: 'Technology' },
  { ticker: 'DELL', name: 'Dell Technologies', industry: 'Technology' },
  { ticker: 'NTAP', name: 'NetApp Inc.', industry: 'Technology' },
  { ticker: 'PSTG', name: 'Pure Storage', industry: 'Technology' },
  { ticker: 'ORCL', name: 'Oracle Corporation', industry: 'Technology' },
  { ticker: 'SAP', name: 'SAP SE', industry: 'Technology' },
  { ticker: 'IBM', name: 'IBM Corp.', industry: 'Technology' },
  { ticker: 'ACN', name: 'Accenture plc', industry: 'Technology' },
  { ticker: 'INFY', name: 'Infosys Ltd.', industry: 'Technology' },
  { ticker: 'WIT', name: 'Wipro Ltd.', industry: 'Technology' },
  { ticker: 'CTSH', name: 'Cognizant Technology', industry: 'Technology' },
  { ticker: 'EPAM', name: 'EPAM Systems', industry: 'Technology' },
  { ticker: 'GLOB', name: 'Globant S.A.', industry: 'Technology' },
  { ticker: 'GDDY', name: 'GoDaddy Inc.', industry: 'Technology' },
  { ticker: 'AKAM', name: 'Akamai Technologies', industry: 'Technology' },
  { ticker: 'CDW', name: 'CDW Corporation', industry: 'Technology' },
  { ticker: 'CSCO', name: 'Cisco Systems', industry: 'Technology' },
  { ticker: 'JNPR', name: 'Juniper Networks', industry: 'Technology' },
  { ticker: 'FFIV', name: 'F5 Inc.', industry: 'Technology' },
  { ticker: 'NTGR', name: 'Netgear Inc.', industry: 'Technology' },
  { ticker: 'CIEN', name: 'Ciena Corporation', industry: 'Technology' },
  { ticker: 'VIAV', name: 'Viavi Solutions', industry: 'Technology' },
  { ticker: 'CALX', name: 'Calix Inc.', industry: 'Technology' },
  { ticker: 'INFN', name: 'Infinera Corp.', industry: 'Technology' },
  { ticker: 'ADTN', name: 'ADTRAN Holdings', industry: 'Technology' },
  { ticker: 'LITE', name: 'Lumentum Holdings', industry: 'Technology' },
  { ticker: 'IIVI', name: 'Coherent Corp.', industry: 'Technology' },
  { ticker: 'COHR', name: 'Coherent Corp.', industry: 'Technology' },
  { ticker: 'AAON', name: 'AAON Inc.', industry: 'Technology' },
  { ticker: 'MSCI', name: 'MSCI Inc.', industry: 'Technology' },
  { ticker: 'ANSS', name: 'ANSYS Inc.', industry: 'Technology' },
  { ticker: 'CDNS', name: 'Cadence Design Systems', industry: 'Technology' },
  { ticker: 'SNPS', name: 'Synopsys Inc.', industry: 'Technology' },
  { ticker: 'AZPN', name: 'Aspen Technology', industry: 'Technology' },
  { ticker: 'PTC', name: 'PTC Inc.', industry: 'Technology' },
  { ticker: 'ADSK', name: 'Autodesk Inc.', industry: 'Technology' },
  { ticker: 'DASTY', name: 'Dassault Systèmes', industry: 'Technology' },
  { ticker: 'TTWO', name: 'Take-Two Interactive', industry: 'Technology' },
  { ticker: 'EA', name: 'Electronic Arts', industry: 'Technology' },
  { ticker: 'ATVI', name: 'Activision Blizzard', industry: 'Technology' },
  { ticker: 'RBLX', name: 'Roblox Corporation', industry: 'Technology' },
  { ticker: 'U', name: 'Unity Software', industry: 'Technology' },
  { ticker: 'PLTK', name: 'Playtika Holding', industry: 'Technology' },
  { ticker: 'GDEV', name: 'GDEV Inc.', industry: 'Technology' },
  { ticker: 'CRSR', name: 'Corsair Gaming', industry: 'Technology' },
  { ticker: 'LOGI', name: 'Logitech International', industry: 'Technology' },
  { ticker: 'SONO', name: 'Sonos Inc.', industry: 'Technology' },
  { ticker: 'HEAR', name: 'Turtle Beach Corp.', industry: 'Technology' },
  { ticker: 'GOOGL', name: 'Alphabet Inc. Class A', industry: 'Communication Services' },
  { ticker: 'GOOG', name: 'Alphabet Inc. Class C', industry: 'Communication Services' },
  { ticker: 'META', name: 'Meta Platforms', industry: 'Communication Services' },
  { ticker: 'NFLX', name: 'Netflix Inc.', industry: 'Communication Services' },
  { ticker: 'DIS', name: 'Walt Disney Co.', industry: 'Communication Services' },
  { ticker: 'CMCSA', name: 'Comcast Corp.', industry: 'Communication Services' },
  { ticker: 'T', name: 'AT&T Inc.', industry: 'Communication Services' },
  { ticker: 'VZ', name: 'Verizon Communications', industry: 'Communication Services' },
  { ticker: 'TMUS', name: 'T-Mobile US', industry: 'Communication Services' },
  { ticker: 'CHTR', name: 'Charter Communications', industry: 'Communication Services' },
  { ticker: 'DISH', name: 'DISH Network', industry: 'Communication Services' },
  { ticker: 'SIRI', name: 'Sirius XM Holdings', industry: 'Communication Services' },
  { ticker: 'LUMN', name: 'Lumen Technologies', industry: 'Communication Services' },
  { ticker: 'FOX', name: 'Fox Corporation Class B', industry: 'Communication Services' },
  { ticker: 'FOXA', name: 'Fox Corporation Class A', industry: 'Communication Services' },
  { ticker: 'PARA', name: 'Paramount Global', industry: 'Communication Services' },
  { ticker: 'WBD', name: 'Warner Bros. Discovery', industry: 'Communication Services' },
  { ticker: 'LYV', name: 'Live Nation Entertainment', industry: 'Communication Services' },
  { ticker: 'SPOT', name: 'Spotify Technology', industry: 'Communication Services' },
  { ticker: 'PINS', name: 'Pinterest Inc.', industry: 'Communication Services' },
  { ticker: 'SNAP', name: 'Snap Inc.', industry: 'Communication Services' },
  { ticker: 'TWTR', name: 'Twitter / X Corp.', industry: 'Communication Services' },
  { ticker: 'MTCH', name: 'Match Group', industry: 'Communication Services' },
  { ticker: 'IAC', name: 'IAC Inc.', industry: 'Communication Services' },
  { ticker: 'ZG', name: 'Zillow Group Class C', industry: 'Communication Services' },
  { ticker: 'Z', name: 'Zillow Group Class A', industry: 'Communication Services' },
  { ticker: 'ANGI', name: 'Angi Inc.', industry: 'Communication Services' },
  { ticker: 'YELP', name: 'Yelp Inc.', industry: 'Communication Services' },
  { ticker: 'TRIP', name: 'TripAdvisor Inc.', industry: 'Communication Services' },
  { ticker: 'LYFT', name: 'Lyft Inc.', industry: 'Communication Services' },
  { ticker: 'UBER', name: 'Uber Technologies', industry: 'Consumer Discretionary' },
  { ticker: 'ABNB', name: 'Airbnb Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'EXPE', name: 'Expedia Group', industry: 'Consumer Discretionary' },
  { ticker: 'BKNG', name: 'Booking Holdings', industry: 'Consumer Discretionary' },
  { ticker: 'PCLN', name: 'Priceline Group', industry: 'Consumer Discretionary' },
  { ticker: 'CRM', name: 'Salesforce Inc.', industry: 'Technology' },
  { ticker: 'NOW', name: 'ServiceNow Inc.', industry: 'Technology' },
  { ticker: 'WDAY', name: 'Workday Inc.', industry: 'Technology' },
  { ticker: 'VEEV', name: 'Veeva Systems', industry: 'Technology' },
  { ticker: 'HUBS', name: 'HubSpot Inc.', industry: 'Technology' },
  { ticker: 'DDOG', name: 'Datadog Inc.', industry: 'Technology' },
  { ticker: 'SNOW', name: 'Snowflake Inc.', industry: 'Technology' },
  { ticker: 'MDB', name: 'MongoDB Inc.', industry: 'Technology' },
  { ticker: 'ESTC', name: 'Elastic N.V.', industry: 'Technology' },
  { ticker: 'CFLT', name: 'Confluent Inc.', industry: 'Technology' },
  { ticker: 'DBX', name: 'Dropbox Inc.', industry: 'Technology' },
  { ticker: 'BOX', name: 'Box Inc.', industry: 'Technology' },
  { ticker: 'DOCN', name: 'DigitalOcean Holdings', industry: 'Technology' },
  { ticker: 'NET', name: 'Cloudflare Inc.', industry: 'Technology' },
  { ticker: 'FSLY', name: 'Fastly Inc.', industry: 'Technology' },
  { ticker: 'ZS', name: 'Zscaler Inc.', industry: 'Technology' },
  { ticker: 'CRWD', name: 'CrowdStrike Holdings', industry: 'Technology' },
  { ticker: 'S', name: 'SentinelOne Inc.', industry: 'Technology' },
  { ticker: 'PANW', name: 'Palo Alto Networks', industry: 'Technology' },
  { ticker: 'FTNT', name: 'Fortinet Inc.', industry: 'Technology' },
  { ticker: 'CHKP', name: 'Check Point Software', industry: 'Technology' },
  { ticker: 'CYBR', name: 'CyberArk Software', industry: 'Technology' },
  { ticker: 'TENB', name: 'Tenable Holdings', industry: 'Technology' },
  { ticker: 'RPD', name: 'Rapid7 Inc.', industry: 'Technology' },
  { ticker: 'QLYS', name: 'Qualys Inc.', industry: 'Technology' },
  { ticker: 'VRNS', name: 'Varonis Systems', industry: 'Technology' },
  { ticker: 'SAIL', name: 'SailPoint Technologies', industry: 'Technology' },
  { ticker: 'OKTA', name: 'Okta Inc.', industry: 'Technology' },
  { ticker: 'PING', name: 'Ping Identity', industry: 'Technology' },
  { ticker: 'IDCC', name: 'InterDigital Inc.', industry: 'Technology' },
  { ticker: 'MIME', name: 'Mimecast Ltd.', industry: 'Technology' },
  { ticker: 'PFPT', name: 'Proofpoint Inc.', industry: 'Technology' },
  { ticker: 'FEYE', name: 'FireEye Inc.', industry: 'Technology' },
  { ticker: 'NLOK', name: 'NortonLifeLock', industry: 'Technology' },
  { ticker: 'GEN', name: 'Gen Digital Inc.', industry: 'Technology' },
  { ticker: 'AVAST', name: 'Avast plc', industry: 'Technology' },
  { ticker: 'INTU', name: 'Intuit Inc.', industry: 'Technology' },
  { ticker: 'ADBE', name: 'Adobe Inc.', industry: 'Technology' },
  { ticker: 'TEAM', name: 'Atlassian Corporation', industry: 'Technology' },
  { ticker: 'JIRA', name: 'Atlassian Corporation', industry: 'Technology' },
  { ticker: 'MNDY', name: 'Monday.com', industry: 'Technology' },
  { ticker: 'ASANA', name: 'Asana Inc.', industry: 'Technology' },
  { ticker: 'ASAN', name: 'Asana Inc.', industry: 'Technology' },
  { ticker: 'SMAR', name: 'Smartsheet Inc.', industry: 'Technology' },
  { ticker: 'APPF', name: 'AppFolio Inc.', industry: 'Technology' },
  { ticker: 'PCTY', name: 'Paylocity Holding', industry: 'Technology' },
  { ticker: 'PAYC', name: 'Paycom Software', industry: 'Technology' },
  { ticker: 'PAYX', name: 'Paychex Inc.', industry: 'Technology' },
  { ticker: 'ADP', name: 'Automatic Data Processing', industry: 'Technology' },
  { ticker: 'CDAY', name: 'Ceridian HCM Holding', industry: 'Technology' },
  { ticker: 'GWRE', name: 'Guidewire Software', industry: 'Technology' },
  { ticker: 'DUCK', name: 'DuckCreek Technologies', industry: 'Technology' },
  { ticker: 'APPN', name: 'Appian Corporation', industry: 'Technology' },
  { ticker: 'PEGA', name: 'Pegasystems Inc.', industry: 'Technology' },
  { ticker: 'NICE', name: 'NICE Ltd.', industry: 'Technology' },
  { ticker: 'GENESYS', name: 'Genesys', industry: 'Technology' },
  { ticker: 'FIVN', name: 'Five9 Inc.', industry: 'Technology' },
  { ticker: 'TWLO', name: 'Twilio Inc.', industry: 'Technology' },
  { ticker: 'BAND', name: 'Bandwidth Inc.', industry: 'Technology' },
  { ticker: 'VONAGE', name: 'Vonage Holdings', industry: 'Technology' },
  { ticker: 'ZOOM', name: 'Zoom Video Communications', industry: 'Technology' },
  { ticker: 'ZM', name: 'Zoom Video Communications', industry: 'Technology' },
  { ticker: 'WEBEX', name: 'Cisco Webex', industry: 'Technology' },
  { ticker: 'RNG', name: 'RingCentral Inc.', industry: 'Technology' },
  { ticker: 'EGHT', name: '8x8 Inc.', industry: 'Technology' },
  { ticker: 'LSPD', name: 'Lightspeed Commerce', industry: 'Technology' },
  { ticker: 'TOST', name: 'Toast Inc.', industry: 'Technology' },
  { ticker: 'PAR', name: 'PAR Technology', industry: 'Technology' },
  { ticker: 'ALOHA', name: 'NCR Voyix', industry: 'Technology' },
  { ticker: 'NCR', name: 'NCR Atleos', industry: 'Technology' },
  { ticker: 'NCRB', name: 'NCR Voyix', industry: 'Technology' },
  { ticker: 'RSKD', name: 'Riskified Ltd.', industry: 'Technology' },
  { ticker: 'GLBE', name: 'Global-E Online', industry: 'Technology' },
  { ticker: 'BIGC', name: 'BigCommerce Holdings', industry: 'Technology' },
  { ticker: 'SHOP', name: 'Shopify Inc.', industry: 'Technology' },
  { ticker: 'WIX', name: 'Wix.com Ltd.', industry: 'Technology' },
  { ticker: 'SQSP', name: 'Squarespace Inc.', industry: 'Technology' },
  { ticker: 'WEAV', name: 'Weave Communications', industry: 'Technology' },
  { ticker: 'SPRK', name: 'Switchback Energy', industry: 'Technology' },
  { ticker: 'BILL', name: 'Bill.com Holdings', industry: 'Technology' },
  { ticker: 'PAYPAL', name: 'PayPal Holdings', industry: 'Financials' },
  { ticker: 'PYPL', name: 'PayPal Holdings', industry: 'Financials' },
  { ticker: 'SQ', name: 'Block Inc.', industry: 'Financials' },
  { ticker: 'XYZ', name: 'Block Inc.', industry: 'Financials' },
  { ticker: 'AFRM', name: 'Affirm Holdings', industry: 'Financials' },
  { ticker: 'UPST', name: 'Upstart Holdings', industry: 'Financials' },
  { ticker: 'SOFI', name: 'SoFi Technologies', industry: 'Financials' },
  { ticker: 'LC', name: 'LendingClub Corp.', industry: 'Financials' },
  { ticker: 'OPEN', name: 'Opendoor Technologies', industry: 'Financials' },
  { ticker: 'OFFERPAD', name: 'Offerpad Solutions', industry: 'Financials' },
  { ticker: 'OPAD', name: 'Offerpad Solutions', industry: 'Financials' },
  { ticker: 'HOOD', name: 'Robinhood Markets', industry: 'Financials' },
  { ticker: 'MKTX', name: 'MarketAxess Holdings', industry: 'Financials' },
  { ticker: 'IBKR', name: 'Interactive Brokers', industry: 'Financials' },
  { ticker: 'SCHW', name: 'Charles Schwab', industry: 'Financials' },
  { ticker: 'AMTD', name: 'TD Ameritrade', industry: 'Financials' },
  { ticker: 'ETFC', name: 'E*TRADE Financial', industry: 'Financials' },
  { ticker: 'MS', name: 'Morgan Stanley', industry: 'Financials' },
  { ticker: 'GS', name: 'Goldman Sachs', industry: 'Financials' },
  { ticker: 'JPM', name: 'JPMorgan Chase', industry: 'Financials' },
  { ticker: 'BAC', name: 'Bank of America', industry: 'Financials' },
  { ticker: 'WFC', name: 'Wells Fargo', industry: 'Financials' },
  { ticker: 'C', name: 'Citigroup Inc.', industry: 'Financials' },
  { ticker: 'USB', name: 'U.S. Bancorp', industry: 'Financials' },
  { ticker: 'PNC', name: 'PNC Financial Services', industry: 'Financials' },
  { ticker: 'TFC', name: 'Truist Financial', industry: 'Financials' },
  { ticker: 'KEY', name: 'KeyCorp', industry: 'Financials' },
  { ticker: 'RF', name: 'Regions Financial', industry: 'Financials' },
  { ticker: 'FITB', name: 'Fifth Third Bancorp', industry: 'Financials' },
  { ticker: 'CFG', name: 'Citizens Financial', industry: 'Financials' },
  { ticker: 'HBAN', name: 'Huntington Bancshares', industry: 'Financials' },
  { ticker: 'MTB', name: 'M&T Bank Corp.', industry: 'Financials' },
  { ticker: 'ZION', name: 'Zions Bancorporation', industry: 'Financials' },
  { ticker: 'CMA', name: 'Comerica Inc.', industry: 'Financials' },
  { ticker: 'SIVB', name: 'SVB Financial Group', industry: 'Financials' },
  { ticker: 'SBNY', name: 'Signature Bank', industry: 'Financials' },
  { ticker: 'PACW', name: 'PacWest Bancorp', industry: 'Financials' },
  { ticker: 'WAL', name: 'Western Alliance Bancorp', industry: 'Financials' },
  { ticker: 'EWBC', name: 'East West Bancorp', industry: 'Financials' },
  { ticker: 'UMPQ', name: 'Umpqua Holdings', industry: 'Financials' },
  { ticker: 'BOKF', name: 'BOK Financial', industry: 'Financials' },
  { ticker: 'GBCI', name: 'Glacier Bancorp', industry: 'Financials' },
  { ticker: 'TOWN', name: 'Towne Bank', industry: 'Financials' },
  { ticker: 'NBTB', name: 'NBT Bancorp', industry: 'Financials' },
  { ticker: 'FFIN', name: 'First Financial Bankshares', industry: 'Financials' },
  { ticker: 'CVBF', name: 'CVB Financial', industry: 'Financials' },
  { ticker: 'BANR', name: 'Banner Financial', industry: 'Financials' },
  { ticker: 'WSFS', name: 'WSFS Financial', industry: 'Financials' },
  { ticker: 'BRKL', name: 'Brookline Bancorp', industry: 'Financials' },
  { ticker: 'NYCB', name: 'New York Community Bancorp', industry: 'Financials' },
  { ticker: 'DCOM', name: 'Dime Community Bancshares', industry: 'Financials' },
  { ticker: 'AXP', name: 'American Express', industry: 'Financials' },
  { ticker: 'V', name: 'Visa Inc.', industry: 'Financials' },
  { ticker: 'MA', name: 'Mastercard Inc.', industry: 'Financials' },
  { ticker: 'DFS', name: 'Discover Financial', industry: 'Financials' },
  { ticker: 'COF', name: 'Capital One Financial', industry: 'Financials' },
  { ticker: 'SYF', name: 'Synchrony Financial', industry: 'Financials' },
  { ticker: 'ALLY', name: 'Ally Financial', industry: 'Financials' },
  { ticker: 'OMF', name: 'OneMain Holdings', industry: 'Financials' },
  { ticker: 'CACC', name: 'Credit Acceptance Corp.', industry: 'Financials' },
  { ticker: 'SC', name: 'Santander Consumer USA', industry: 'Financials' },
  { ticker: 'WRLD', name: 'World Acceptance Corp.', industry: 'Financials' },
  { ticker: 'ENVA', name: 'Enova International', industry: 'Financials' },
  { ticker: 'CURO', name: 'CURO Group Holdings', industry: 'Financials' },
  { ticker: 'QCASH', name: 'QCash Financial', industry: 'Financials' },
  { ticker: 'TREE', name: 'LendingTree Inc.', industry: 'Financials' },
  { ticker: 'RATE', name: 'Bankrate Inc.', industry: 'Financials' },
  { ticker: 'NRDS', name: 'NerdWallet Inc.', industry: 'Financials' },
  { ticker: 'CRED', name: 'CredAvenue', industry: 'Financials' },
  { ticker: 'BRK.B', name: 'Berkshire Hathaway B', industry: 'Financials' },
  { ticker: 'BRK.A', name: 'Berkshire Hathaway A', industry: 'Financials' },
  { ticker: 'BX', name: 'Blackstone Inc.', industry: 'Financials' },
  { ticker: 'KKR', name: 'KKR & Co.', industry: 'Financials' },
  { ticker: 'APO', name: 'Apollo Global Management', industry: 'Financials' },
  { ticker: 'CG', name: 'Carlyle Group', industry: 'Financials' },
  { ticker: 'ARES', name: 'Ares Management', industry: 'Financials' },
  { ticker: 'BAM', name: 'Brookfield Asset Management', industry: 'Financials' },
  { ticker: 'BN', name: 'Brookfield Corp.', industry: 'Financials' },
  { ticker: 'OWL', name: 'Blue Owl Capital', industry: 'Financials' },
  { ticker: 'HLNE', name: 'Hamilton Lane', industry: 'Financials' },
  { ticker: 'STEP', name: 'StepStone Group', industry: 'Financials' },
  { ticker: 'IVZ', name: 'Invesco Ltd.', industry: 'Financials' },
  { ticker: 'BEN', name: 'Franklin Resources', industry: 'Financials' },
  { ticker: 'AMG', name: 'Affiliated Managers Group', industry: 'Financials' },
  { ticker: 'WDR', name: 'Waddell & Reed', industry: 'Financials' },
  { ticker: 'VRTS', name: 'Virtus Investment Partners', industry: 'Financials' },
  { ticker: 'DHIL', name: 'Diamond Hill Investment', industry: 'Financials' },
  { ticker: 'CLBK', name: 'Columbia Banking System', industry: 'Financials' },
  { ticker: 'COIN', name: 'Coinbase Global', industry: 'Crypto' },
  { ticker: 'MSTR', name: 'MicroStrategy Inc.', industry: 'Crypto' },
  { ticker: 'MARA', name: 'Marathon Digital Holdings', industry: 'Crypto' },
  { ticker: 'RIOT', name: 'Riot Platforms', industry: 'Crypto' },
  { ticker: 'CLSK', name: 'CleanSpark Inc.', industry: 'Crypto' },
  { ticker: 'BTBT', name: 'Bit Digital Inc.', industry: 'Crypto' },
  { ticker: 'CIFR', name: 'Cipher Mining', industry: 'Crypto' },
  { ticker: 'BITF', name: 'Bitfarms Ltd.', industry: 'Crypto' },
  { ticker: 'HUT', name: 'Hut 8 Mining', industry: 'Crypto' },
  { ticker: 'HIVE', name: 'Hive Digital Technologies', industry: 'Crypto' },
  { ticker: 'IREN', name: 'Iris Energy', industry: 'Crypto' },
  { ticker: 'WULF', name: 'TeraWulf Inc.', industry: 'Crypto' },
  { ticker: 'CORZ', name: 'Core Scientific', industry: 'Crypto' },
  { ticker: 'BTCM', name: 'BIT Mining Ltd.', industry: 'Crypto' },
  { ticker: 'ARBK', name: 'Argo Blockchain', industry: 'Crypto' },
  { ticker: 'SATO', name: 'Satoshi Island', industry: 'Crypto' },
  { ticker: 'BSRT', name: 'BitStream Mining', industry: 'Crypto' },
  { ticker: 'GBTC', name: 'Grayscale Bitcoin Trust', industry: 'ETF' },
  { ticker: 'IBIT', name: 'iShares Bitcoin Trust', industry: 'ETF' },
  { ticker: 'FBTC', name: 'Fidelity Wise Origin Bitcoin', industry: 'ETF' },
  { ticker: 'ARKB', name: 'ARK 21Shares Bitcoin ETF', industry: 'ETF' },
  { ticker: 'BITB', name: 'Bitwise Bitcoin ETF', industry: 'ETF' },
  { ticker: 'JNJ', name: 'Johnson & Johnson', industry: 'Healthcare' },
  { ticker: 'UNH', name: 'UnitedHealth Group', industry: 'Healthcare' },
  { ticker: 'PFE', name: 'Pfizer Inc.', industry: 'Healthcare' },
  { ticker: 'MRK', name: 'Merck & Co.', industry: 'Healthcare' },
  { ticker: 'ABBV', name: 'AbbVie Inc.', industry: 'Healthcare' },
  { ticker: 'LLY', name: 'Eli Lilly and Co.', industry: 'Healthcare' },
  { ticker: 'BMY', name: 'Bristol-Myers Squibb', industry: 'Healthcare' },
  { ticker: 'AMGN', name: 'Amgen Inc.', industry: 'Healthcare' },
  { ticker: 'GILD', name: 'Gilead Sciences', industry: 'Healthcare' },
  { ticker: 'BIIB', name: 'Biogen Inc.', industry: 'Healthcare' },
  { ticker: 'REGN', name: 'Regeneron Pharmaceuticals', industry: 'Healthcare' },
  { ticker: 'VRTX', name: 'Vertex Pharmaceuticals', industry: 'Healthcare' },
  { ticker: 'ALNY', name: 'Alnylam Pharmaceuticals', industry: 'Healthcare' },
  { ticker: 'MRNA', name: 'Moderna Inc.', industry: 'Healthcare' },
  { ticker: 'BNTX', name: 'BioNTech SE', industry: 'Healthcare' },
  { ticker: 'NVAX', name: 'Novavax Inc.', industry: 'Healthcare' },
  { ticker: 'SRPT', name: 'Sarepta Therapeutics', industry: 'Healthcare' },
  { ticker: 'BLUE', name: 'bluebird bio', industry: 'Healthcare' },
  { ticker: 'EDIT', name: 'Editas Medicine', industry: 'Healthcare' },
  { ticker: 'NTLA', name: 'Intellia Therapeutics', industry: 'Healthcare' },
  { ticker: 'BEAM', name: 'Beam Therapeutics', industry: 'Healthcare' },
  { ticker: 'CRSP', name: 'CRISPR Therapeutics', industry: 'Healthcare' },
  { ticker: 'PACB', name: 'Pacific Biosciences', industry: 'Healthcare' },
  { ticker: 'ILMN', name: 'Illumina Inc.', industry: 'Healthcare' },
  { ticker: 'NTRA', name: 'Natera Inc.', industry: 'Healthcare' },
  { ticker: 'EXAS', name: 'Exact Sciences', industry: 'Healthcare' },
  { ticker: 'GRAIL', name: 'GRAIL Inc.', industry: 'Healthcare' },
  { ticker: 'GHDX', name: 'Genomic Health', industry: 'Healthcare' },
  { ticker: 'FATE', name: 'Fate Therapeutics', industry: 'Healthcare' },
  { ticker: 'KYMR', name: 'Kymera Therapeutics', industry: 'Healthcare' },
  { ticker: 'ARQT', name: 'Arcutis Biotherapeutics', industry: 'Healthcare' },
  { ticker: 'RXRX', name: 'Recursion Pharmaceuticals', industry: 'Healthcare' },
  { ticker: 'SDGR', name: 'Schrödinger Inc.', industry: 'Healthcare' },
  { ticker: 'SCHRD', name: 'Schrödinger Inc.', industry: 'Healthcare' },
  { ticker: 'ABCL', name: 'AbCellera Biologics', industry: 'Healthcare' },
  { ticker: 'SEER', name: 'Seer Inc.', industry: 'Healthcare' },
  { ticker: 'OLINK', name: 'Olink Proteomics', industry: 'Healthcare' },
  { ticker: 'SOHO', name: 'Sorrento Therapeutics', industry: 'Healthcare' },
  { ticker: 'HIMS', name: 'Hims & Hers Health', industry: 'Healthcare' },
  { ticker: 'NUVL', name: 'Nuvalent Inc.', industry: 'Healthcare' },
  { ticker: 'KROS', name: 'Keros Therapeutics', industry: 'Healthcare' },
  { ticker: 'IMVT', name: 'Immunovant Inc.', industry: 'Healthcare' },
  { ticker: 'ARCT', name: 'Arctus Bio', industry: 'Healthcare' },
  { ticker: 'ACAD', name: 'ACADIA Pharmaceuticals', industry: 'Healthcare' },
  { ticker: 'SAGE', name: 'Sage Therapeutics', industry: 'Healthcare' },
  { ticker: 'INVA', name: 'Innoviva Inc.', industry: 'Healthcare' },
  { ticker: 'PRTA', name: 'Prothena Corp.', industry: 'Healthcare' },
  { ticker: 'RARE', name: 'Ultragenyx Pharmaceutical', industry: 'Healthcare' },
  { ticker: 'PTGX', name: 'Protagonist Therapeutics', industry: 'Healthcare' },
  { ticker: 'CRNX', name: 'Crinetics Pharmaceuticals', industry: 'Healthcare' },
  { ticker: 'KALA', name: 'Kala Bio', industry: 'Healthcare' },
  { ticker: 'RVMD', name: 'Revolution Medicines', industry: 'Healthcare' },
  { ticker: 'TMDX', name: 'TransMedics Group', industry: 'Healthcare' },
  { ticker: 'AXSM', name: 'Axsome Therapeutics', industry: 'Healthcare' },
  { ticker: 'INMD', name: 'InMode Ltd.', industry: 'Healthcare' },
  { ticker: 'ISRG', name: 'Intuitive Surgical', industry: 'Healthcare' },
  { ticker: 'MDT', name: 'Medtronic plc', industry: 'Healthcare' },
  { ticker: 'BSX', name: 'Boston Scientific', industry: 'Healthcare' },
  { ticker: 'EW', name: 'Edwards Lifesciences', industry: 'Healthcare' },
  { ticker: 'SYK', name: 'Stryker Corp.', industry: 'Healthcare' },
  { ticker: 'ZBH', name: 'Zimmer Biomet', industry: 'Healthcare' },
  { ticker: 'HOLX', name: 'Hologic Inc.', industry: 'Healthcare' },
  { ticker: 'BDX', name: 'Becton Dickinson', industry: 'Healthcare' },
  { ticker: 'BAX', name: 'Baxter International', industry: 'Healthcare' },
  { ticker: 'DXCM', name: 'DexCom Inc.', industry: 'Healthcare' },
  { ticker: 'PODD', name: 'Insulet Corporation', industry: 'Healthcare' },
  { ticker: 'TNDM', name: 'Tandem Diabetes Care', industry: 'Healthcare' },
  { ticker: 'ABMD', name: 'Abiomed Inc.', industry: 'Healthcare' },
  { ticker: 'NVCR', name: 'NovoCure Ltd.', industry: 'Healthcare' },
  { ticker: 'SWAV', name: 'ShockWave Medical', industry: 'Healthcare' },
  { ticker: 'IRTC', name: 'iRhythm Technologies', industry: 'Healthcare' },
  { ticker: 'ACLS', name: 'Axcelis Technologies', industry: 'Healthcare' },
  { ticker: 'NVST', name: 'Envista Holdings', industry: 'Healthcare' },
  { ticker: 'ALGN', name: 'Align Technology', industry: 'Healthcare' },
  { ticker: 'XRAY', name: 'Dentsply Sirona', industry: 'Healthcare' },
  { ticker: 'PDCO', name: 'Patterson Companies', industry: 'Healthcare' },
  { ticker: 'HSIC', name: 'Henry Schein', industry: 'Healthcare' },
  { ticker: 'DVA', name: 'DaVita Inc.', industry: 'Healthcare' },
  { ticker: 'FMS', name: 'Fresenius Medical Care', industry: 'Healthcare' },
  { ticker: 'PINC', name: 'Premier Inc.', industry: 'Healthcare' },
  { ticker: 'HCA', name: 'HCA Healthcare', industry: 'Healthcare' },
  { ticker: 'THC', name: 'Tenet Healthcare', industry: 'Healthcare' },
  { ticker: 'CYH', name: 'Community Health Systems', industry: 'Healthcare' },
  { ticker: 'LPNT', name: 'LifePoint Health', industry: 'Healthcare' },
  { ticker: 'ACHC', name: 'Acadia Healthcare', industry: 'Healthcare' },
  { ticker: 'UHS', name: 'Universal Health Services', industry: 'Healthcare' },
  { ticker: 'ENSG', name: 'Ensign Group', industry: 'Healthcare' },
  { ticker: 'NHC', name: 'National HealthCare Corp.', industry: 'Healthcare' },
  { ticker: 'SEM', name: 'Select Medical Holdings', industry: 'Healthcare' },
  { ticker: 'CANO', name: 'Cano Health', industry: 'Healthcare' },
  { ticker: 'ONEM', name: '1Life Healthcare', industry: 'Healthcare' },
  { ticker: 'DOCS', name: 'Doximity Inc.', industry: 'Healthcare' },
  { ticker: 'PHYND', name: 'Phynd Technologies', industry: 'Healthcare' },
  { ticker: 'AMWL', name: 'American Well Corp.', industry: 'Healthcare' },
  { ticker: 'TDOC', name: 'Teladoc Health', industry: 'Healthcare' },
  { ticker: 'OPRX', name: 'OptimizeRx Corp.', industry: 'Healthcare' },
  { ticker: 'HCAT', name: 'Health Catalyst', industry: 'Healthcare' },
  { ticker: 'VERADIGM', name: 'Veradigm Inc.', industry: 'Healthcare' },
  { ticker: 'MDRX', name: 'Veradigm Inc.', industry: 'Healthcare' },
  { ticker: 'NXGN', name: 'NextGen Healthcare', industry: 'Healthcare' },
  { ticker: 'PHYH', name: 'Physician Partners', industry: 'Healthcare' },
  { ticker: 'ALHC', name: 'Alignment Healthcare', industry: 'Healthcare' },
  { ticker: 'CLOV', name: 'Clover Health Investments', industry: 'Healthcare' },
  { ticker: 'OSCR', name: 'Oscar Health', industry: 'Healthcare' },
  { ticker: 'ACNB', name: 'ACNB Corp.', industry: 'Healthcare' },
  { ticker: 'CI', name: 'Cigna Group', industry: 'Healthcare' },
  { ticker: 'CVS', name: 'CVS Health', industry: 'Healthcare' },
  { ticker: 'HUM', name: 'Humana Inc.', industry: 'Healthcare' },
  { ticker: 'CNC', name: 'Centene Corp.', industry: 'Healthcare' },
  { ticker: 'MOH', name: 'Molina Healthcare', industry: 'Healthcare' },
  { ticker: 'ELV', name: 'Elevance Health', industry: 'Healthcare' },
  { ticker: 'MCK', name: 'McKesson Corp.', industry: 'Healthcare' },
  { ticker: 'CAH', name: 'Cardinal Health', industry: 'Healthcare' },
  { ticker: 'ABC', name: 'AmerisourceBergen', industry: 'Healthcare' },
  { ticker: 'PRGO', name: 'Perrigo Company', industry: 'Healthcare' },
  { ticker: 'ENDP', name: 'Endo International', industry: 'Healthcare' },
  { ticker: 'MNK', name: 'Mallinckrodt plc', industry: 'Healthcare' },
  { ticker: 'TEVA', name: 'Teva Pharmaceutical', industry: 'Healthcare' },
  { ticker: 'MYL', name: 'Mylan N.V.', industry: 'Healthcare' },
  { ticker: 'VTRS', name: 'Viatris Inc.', industry: 'Healthcare' },
  { ticker: 'AGN', name: 'Allergan plc', industry: 'Healthcare' },
  { ticker: 'JAZZ', name: 'Jazz Pharmaceuticals', industry: 'Healthcare' },
  { ticker: 'PCRX', name: 'Pacira BioSciences', industry: 'Healthcare' },
  { ticker: 'SUPN', name: 'Supernus Pharmaceuticals', industry: 'Healthcare' },
  { ticker: 'PAHC', name: 'Phibro Animal Health', industry: 'Healthcare' },
  { ticker: 'ZTS', name: 'Zoetis Inc.', industry: 'Healthcare' },
  { ticker: 'IDXX', name: 'IDEXX Laboratories', industry: 'Healthcare' },
  { ticker: 'ELAN', name: 'Elanco Animal Health', industry: 'Healthcare' },
  { ticker: 'AMZN', name: 'Amazon.com Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'TSLA', name: 'Tesla Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'HD', name: 'Home Depot', industry: 'Consumer Discretionary' },
  { ticker: 'LOW', name: 'Lowe\'s Companies', industry: 'Consumer Discretionary' },
  { ticker: 'MCD', name: 'McDonald\'s Corp.', industry: 'Consumer Discretionary' },
  { ticker: 'SBUX', name: 'Starbucks Corp.', industry: 'Consumer Discretionary' },
  { ticker: 'NKE', name: 'Nike Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'TJX', name: 'TJX Companies', industry: 'Consumer Discretionary' },
  { ticker: 'ROST', name: 'Ross Stores', industry: 'Consumer Discretionary' },
  { ticker: 'BURL', name: 'Burlington Stores', industry: 'Consumer Discretionary' },
  { ticker: 'TGT', name: 'Target Corp.', industry: 'Consumer Discretionary' },
  { ticker: 'WMT', name: 'Walmart Inc.', industry: 'Consumer Staples' },
  { ticker: 'COST', name: 'Costco Wholesale', industry: 'Consumer Staples' },
  { ticker: 'KR', name: 'Kroger Co.', industry: 'Consumer Staples' },
  { ticker: 'SFM', name: 'Sprouts Farmers Market', industry: 'Consumer Staples' },
  { ticker: 'ACI', name: 'Albertsons Companies', industry: 'Consumer Staples' },
  { ticker: 'WBA', name: 'Walgreens Boots Alliance', industry: 'Consumer Staples' },
  { ticker: 'RAD', name: 'Rite Aid Corp.', industry: 'Consumer Staples' },
  { ticker: 'DG', name: 'Dollar General', industry: 'Consumer Discretionary' },
  { ticker: 'DLTR', name: 'Dollar Tree Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'FIVE', name: 'Five Below Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'OLLI', name: 'Ollie\'s Bargain Outlet', industry: 'Consumer Discretionary' },
  { ticker: 'BIG', name: 'Big Lots Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'BBBY', name: 'Bed Bath & Beyond', industry: 'Consumer Discretionary' },
  { ticker: 'BBY', name: 'Best Buy Co.', industry: 'Consumer Discretionary' },
  { ticker: 'GME', name: 'GameStop Corp.', industry: 'Consumer Discretionary' },
  { ticker: 'CONN', name: 'Conn\'s Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'RCII', name: 'Rent-A-Center', industry: 'Consumer Discretionary' },
  { ticker: 'AAN', name: 'Aaron Holdings', industry: 'Consumer Discretionary' },
  { ticker: 'UPBD', name: 'Upbound Group', industry: 'Consumer Discretionary' },
  { ticker: 'PRTY', name: 'Party City Holdco', industry: 'Consumer Discretionary' },
  { ticker: 'SPWH', name: 'Sportsman\'s Warehouse', industry: 'Consumer Discretionary' },
  { ticker: 'ASO', name: 'Academy Sports & Outdoors', industry: 'Consumer Discretionary' },
  { ticker: 'HIBB', name: 'Hibbett Sports', industry: 'Consumer Discretionary' },
  { ticker: 'DICKS', name: 'Dick\'s Sporting Goods', industry: 'Consumer Discretionary' },
  { ticker: 'DKS', name: 'Dick\'s Sporting Goods', industry: 'Consumer Discretionary' },
  { ticker: 'BOOT', name: 'Boot Barn Holdings', industry: 'Consumer Discretionary' },
  { ticker: 'CATO', name: 'Cato Corporation', industry: 'Consumer Discretionary' },
  { ticker: 'CHICO', name: 'Chico\'s FAS', industry: 'Consumer Discretionary' },
  { ticker: 'CHS', name: 'Chico\'s FAS', industry: 'Consumer Discretionary' },
  { ticker: 'AEO', name: 'American Eagle Outfitters', industry: 'Consumer Discretionary' },
  { ticker: 'ANF', name: 'Abercrombie & Fitch', industry: 'Consumer Discretionary' },
  { ticker: 'GPS', name: 'Gap Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'PVH', name: 'PVH Corp.', industry: 'Consumer Discretionary' },
  { ticker: 'RL', name: 'Ralph Lauren Corp.', industry: 'Consumer Discretionary' },
  { ticker: 'CPRI', name: 'Capri Holdings', industry: 'Consumer Discretionary' },
  { ticker: 'TPR', name: 'Tapestry Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'LULU', name: 'Lululemon Athletica', industry: 'Consumer Discretionary' },
  { ticker: 'UA', name: 'Under Armour Class C', industry: 'Consumer Discretionary' },
  { ticker: 'UAA', name: 'Under Armour Class A', industry: 'Consumer Discretionary' },
  { ticker: 'CROX', name: 'Crocs Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'DECK', name: 'Deckers Outdoor', industry: 'Consumer Discretionary' },
  { ticker: 'SKX', name: 'Skechers USA', industry: 'Consumer Discretionary' },
  { ticker: 'ONON', name: 'On Holding AG', industry: 'Consumer Discretionary' },
  { ticker: 'BIRK', name: 'Birkenstock Holding', industry: 'Consumer Discretionary' },
  { ticker: 'SHOO', name: 'Steven Madden', industry: 'Consumer Discretionary' },
  { ticker: 'SCVL', name: 'Shoe Carnival', industry: 'Consumer Discretionary' },
  { ticker: 'FLUT', name: 'Flutter Entertainment', industry: 'Consumer Discretionary' },
  { ticker: 'DKNG', name: 'DraftKings Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'RSI', name: 'Rush Street Interactive', industry: 'Consumer Discretionary' },
  { ticker: 'PENN', name: 'Penn Entertainment', industry: 'Consumer Discretionary' },
  { ticker: 'MGM', name: 'MGM Resorts International', industry: 'Consumer Discretionary' },
  { ticker: 'WYNN', name: 'Wynn Resorts', industry: 'Consumer Discretionary' },
  { ticker: 'LVS', name: 'Las Vegas Sands', industry: 'Consumer Discretionary' },
  { ticker: 'CZR', name: 'Caesars Entertainment', industry: 'Consumer Discretionary' },
  { ticker: 'MLCO', name: 'Melco Resorts', industry: 'Consumer Discretionary' },
  { ticker: 'GENI', name: 'Genius Sports', industry: 'Consumer Discretionary' },
  { ticker: 'EVRI', name: 'Everi Holdings', industry: 'Consumer Discretionary' },
  { ticker: 'AGS', name: 'PlayAGS Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'SGMS', name: 'Scientific Games', industry: 'Consumer Discretionary' },
  { ticker: 'LNW', name: 'Light & Wonder', industry: 'Consumer Discretionary' },
  { ticker: 'NCLH', name: 'Norwegian Cruise Line', industry: 'Consumer Discretionary' },
  { ticker: 'CCL', name: 'Carnival Corp.', industry: 'Consumer Discretionary' },
  { ticker: 'RCL', name: 'Royal Caribbean Group', industry: 'Consumer Discretionary' },
  { ticker: 'VCNX', name: 'Vaccinex Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'HLT', name: 'Hilton Worldwide', industry: 'Consumer Discretionary' },
  { ticker: 'MAR', name: 'Marriott International', industry: 'Consumer Discretionary' },
  { ticker: 'H', name: 'Hyatt Hotels', industry: 'Consumer Discretionary' },
  { ticker: 'IHG', name: 'InterContinental Hotels', industry: 'Consumer Discretionary' },
  { ticker: 'WH', name: 'Wyndham Hotels', industry: 'Consumer Discretionary' },
  { ticker: 'CHH', name: 'Choice Hotels', industry: 'Consumer Discretionary' },
  { ticker: 'STAY', name: 'Extended Stay America', industry: 'Consumer Discretionary' },
  { ticker: 'APLE', name: 'Apple Hospitality REIT', industry: 'Real Estate' },
  { ticker: 'PK', name: 'Park Hotels & Resorts', industry: 'Real Estate' },
  { ticker: 'RHP', name: 'Ryman Hospitality', industry: 'Real Estate' },
  { ticker: 'SHO', name: 'Sunstone Hotel Investors', industry: 'Real Estate' },
  { ticker: 'CLDT', name: 'Chatham Lodging Trust', industry: 'Real Estate' },
  { ticker: 'YUM', name: 'Yum! Brands', industry: 'Consumer Discretionary' },
  { ticker: 'QSR', name: 'Restaurant Brands Int\'l', industry: 'Consumer Discretionary' },
  { ticker: 'CMG', name: 'Chipotle Mexican Grill', industry: 'Consumer Discretionary' },
  { ticker: 'DPZ', name: 'Domino\'s Pizza', industry: 'Consumer Discretionary' },
  { ticker: 'PZZA', name: 'Papa John\'s International', industry: 'Consumer Discretionary' },
  { ticker: 'WEN', name: 'Wendy\'s Co.', industry: 'Consumer Discretionary' },
  { ticker: 'JACK', name: 'Jack in the Box', industry: 'Consumer Discretionary' },
  { ticker: 'TXRH', name: 'Texas Roadhouse', industry: 'Consumer Discretionary' },
  { ticker: 'DINE', name: 'Dine Brands Global', industry: 'Consumer Discretionary' },
  { ticker: 'EAT', name: 'Brinker International', industry: 'Consumer Discretionary' },
  { ticker: 'CAKE', name: 'Cheesecake Factory', industry: 'Consumer Discretionary' },
  { ticker: 'BLMN', name: 'Bloomin\' Brands', industry: 'Consumer Discretionary' },
  { ticker: 'DENN', name: 'Denny\'s Corp.', industry: 'Consumer Discretionary' },
  { ticker: 'SHAK', name: 'Shake Shack', industry: 'Consumer Discretionary' },
  { ticker: 'WING', name: 'Wingstop Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'BROS', name: 'Dutch Bros Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'CAVA', name: 'Cava Group', industry: 'Consumer Discretionary' },
  { ticker: 'NATH', name: 'Nathan\'s Famous', industry: 'Consumer Discretionary' },
  { ticker: 'PLNT', name: 'Planet Fitness', industry: 'Consumer Discretionary' },
  { ticker: 'XPOF', name: 'Xponential Fitness', industry: 'Consumer Discretionary' },
  { ticker: 'PTON', name: 'Peloton Interactive', industry: 'Consumer Discretionary' },
  { ticker: 'NLS', name: 'Nautilus Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'CVNA', name: 'Carvana Co.', industry: 'Consumer Discretionary' },
  { ticker: 'KMX', name: 'CarMax Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'AN', name: 'AutoNation Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'PAG', name: 'Penske Automotive', industry: 'Consumer Discretionary' },
  { ticker: 'LAD', name: 'Lithia Motors', industry: 'Consumer Discretionary' },
  { ticker: 'GPI', name: 'Group 1 Automotive', industry: 'Consumer Discretionary' },
  { ticker: 'ABG', name: 'Asbury Automotive', industry: 'Consumer Discretionary' },
  { ticker: 'SAH', name: 'Sonic Automotive', industry: 'Consumer Discretionary' },
  { ticker: 'RUNN', name: 'TrueCar Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'TRUE', name: 'TrueCar Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'CARS', name: 'Cars.com Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'CDK', name: 'CDK Global', industry: 'Technology' },
  { ticker: 'DRVN', name: 'Driven Brands', industry: 'Consumer Discretionary' },
  { ticker: 'MNRO', name: 'Monro Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'ORLY', name: 'O\'Reilly Automotive', industry: 'Consumer Discretionary' },
  { ticker: 'AZO', name: 'AutoZone Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'AAP', name: 'Advance Auto Parts', industry: 'Consumer Discretionary' },
  { ticker: 'GPC', name: 'Genuine Parts Co.', industry: 'Consumer Discretionary' },
  { ticker: 'LKQ', name: 'LKQ Corporation', industry: 'Consumer Discretionary' },
  { ticker: 'PRTS', name: 'CarParts.com', industry: 'Consumer Discretionary' },
  { ticker: 'EBAY', name: 'eBay Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'ETSY', name: 'Etsy Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'POSH', name: 'Poshmark Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'REAL', name: 'RealReal Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'THRD', name: 'Thredup Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'OSTK', name: 'Overstock.com', industry: 'Consumer Discretionary' },
  { ticker: 'WAYFAIR', name: 'Wayfair Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'W', name: 'Wayfair Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'CHWY', name: 'Chewy Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'PETQ', name: 'PetIQ Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'WOOF', name: 'Petco Health & Wellness', industry: 'Consumer Discretionary' },
  { ticker: 'FRPT', name: 'Freshpet Inc.', industry: 'Consumer Staples' },
  { ticker: 'NUO', name: 'Nuo Therapeutics', industry: 'Healthcare' },
  { ticker: 'PG', name: 'Procter & Gamble', industry: 'Consumer Staples' },
  { ticker: 'KO', name: 'Coca-Cola Co.', industry: 'Consumer Staples' },
  { ticker: 'PEP', name: 'PepsiCo Inc.', industry: 'Consumer Staples' },
  { ticker: 'PM', name: 'Philip Morris International', industry: 'Consumer Staples' },
  { ticker: 'MO', name: 'Altria Group', industry: 'Consumer Staples' },
  { ticker: 'BTI', name: 'British American Tobacco', industry: 'Consumer Staples' },
  { ticker: 'UL', name: 'Unilever plc', industry: 'Consumer Staples' },
  { ticker: 'CL', name: 'Colgate-Palmolive', industry: 'Consumer Staples' },
  { ticker: 'CHD', name: 'Church & Dwight', industry: 'Consumer Staples' },
  { ticker: 'EL', name: 'Estée Lauder', industry: 'Consumer Staples' },
  { ticker: 'COTY', name: 'Coty Inc.', industry: 'Consumer Staples' },
  { ticker: 'REVLON', name: 'Revlon Inc.', industry: 'Consumer Staples' },
  { ticker: 'REV', name: 'Revlon Inc.', industry: 'Consumer Staples' },
  { ticker: 'EDGEWELL', name: 'Edgewell Personal Care', industry: 'Consumer Staples' },
  { ticker: 'EPC', name: 'Edgewell Personal Care', industry: 'Consumer Staples' },
  { ticker: 'SPB', name: 'Spectrum Brands', industry: 'Consumer Staples' },
  { ticker: 'HRB', name: 'H&R Block', industry: 'Consumer Staples' },
  { ticker: 'MNST', name: 'Monster Beverage', industry: 'Consumer Staples' },
  { ticker: 'CELH', name: 'Celsius Holdings', industry: 'Consumer Staples' },
  { ticker: 'FIZZ', name: 'National Beverage Corp.', industry: 'Consumer Staples' },
  { ticker: 'COKE', name: 'Coca-Cola Consolidated', industry: 'Consumer Staples' },
  { ticker: 'KDP', name: 'Keurig Dr Pepper', industry: 'Consumer Staples' },
  { ticker: 'STZ', name: 'Constellation Brands', industry: 'Consumer Staples' },
  { ticker: 'BF.B', name: 'Brown-Forman Class B', industry: 'Consumer Staples' },
  { ticker: 'DEO', name: 'Diageo plc', industry: 'Consumer Staples' },
  { ticker: 'SAM', name: 'Boston Beer Company', industry: 'Consumer Staples' },
  { ticker: 'BREW', name: 'Craft Brew Alliance', industry: 'Consumer Staples' },
  { ticker: 'ABEV', name: 'Ambev S.A.', industry: 'Consumer Staples' },
  { ticker: 'TAP', name: 'Molson Coors Beverage', industry: 'Consumer Staples' },
  { ticker: 'GIS', name: 'General Mills', industry: 'Consumer Staples' },
  { ticker: 'K', name: 'Kellanova', industry: 'Consumer Staples' },
  { ticker: 'CPB', name: 'Campbell Soup', industry: 'Consumer Staples' },
  { ticker: 'HRL', name: 'Hormel Foods', industry: 'Consumer Staples' },
  { ticker: 'SJM', name: 'J.M. Smucker', industry: 'Consumer Staples' },
  { ticker: 'CAG', name: 'Conagra Brands', industry: 'Consumer Staples' },
  { ticker: 'MKC', name: 'McCormick & Co.', industry: 'Consumer Staples' },
  { ticker: 'MDLZ', name: 'Mondelēz International', industry: 'Consumer Staples' },
  { ticker: 'HSY', name: 'Hershey Co.', industry: 'Consumer Staples' },
  { ticker: 'TR', name: 'Tootsie Roll Industries', industry: 'Consumer Staples' },
  { ticker: 'RMCF', name: 'Rocky Mountain Chocolate', industry: 'Consumer Staples' },
  { ticker: 'LANC', name: 'Lancaster Colony', industry: 'Consumer Staples' },
  { ticker: 'JBSS', name: 'John B. Sanfilippo', industry: 'Consumer Staples' },
  { ticker: 'SENEA', name: 'Seneca Foods', industry: 'Consumer Staples' },
  { ticker: 'TWNK', name: 'Hostess Brands', industry: 'Consumer Staples' },
  { ticker: 'LWAY', name: 'Lifeway Foods', industry: 'Consumer Staples' },
  { ticker: 'NOMD', name: 'Nomad Foods', industry: 'Consumer Staples' },
  { ticker: 'INGR', name: 'Ingredion Inc.', industry: 'Consumer Staples' },
  { ticker: 'ADM', name: 'Archer-Daniels-Midland', industry: 'Consumer Staples' },
  { ticker: 'BG', name: 'Bunge Global', industry: 'Consumer Staples' },
  { ticker: 'CALM', name: 'Cal-Maine Foods', industry: 'Consumer Staples' },
  { ticker: 'SAFM', name: 'Sanderson Farms', industry: 'Consumer Staples' },
  { ticker: 'TSN', name: 'Tyson Foods', industry: 'Consumer Staples' },
  { ticker: 'PPC', name: 'Pilgrim\'s Pride', industry: 'Consumer Staples' },
  { ticker: 'JBSAY', name: 'JBS S.A.', industry: 'Consumer Staples' },
  { ticker: 'XOM', name: 'ExxonMobil Corp.', industry: 'Energy' },
  { ticker: 'CVX', name: 'Chevron Corp.', industry: 'Energy' },
  { ticker: 'COP', name: 'ConocoPhillips', industry: 'Energy' },
  { ticker: 'EOG', name: 'EOG Resources', industry: 'Energy' },
  { ticker: 'PXD', name: 'Pioneer Natural Resources', industry: 'Energy' },
  { ticker: 'DVN', name: 'Devon Energy', industry: 'Energy' },
  { ticker: 'FANG', name: 'Diamondback Energy', industry: 'Energy' },
  { ticker: 'MPC', name: 'Marathon Petroleum', industry: 'Energy' },
  { ticker: 'VLO', name: 'Valero Energy', industry: 'Energy' },
  { ticker: 'PSX', name: 'Phillips 66', industry: 'Energy' },
  { ticker: 'HES', name: 'Hess Corp.', industry: 'Energy' },
  { ticker: 'APA', name: 'APA Corp.', industry: 'Energy' },
  { ticker: 'OXY', name: 'Occidental Petroleum', industry: 'Energy' },
  { ticker: 'HAL', name: 'Halliburton Co.', industry: 'Energy' },
  { ticker: 'SLB', name: 'Schlumberger Ltd.', industry: 'Energy' },
  { ticker: 'BKR', name: 'Baker Hughes', industry: 'Energy' },
  { ticker: 'NOV', name: 'NOV Inc.', industry: 'Energy' },
  { ticker: 'FTI', name: 'TechnipFMC', industry: 'Energy' },
  { ticker: 'LBRT', name: 'Liberty Energy', industry: 'Energy' },
  { ticker: 'PUMP', name: 'ProPetro Holding', industry: 'Energy' },
  { ticker: 'NINE', name: 'Nine Energy Service', industry: 'Energy' },
  { ticker: 'WTTR', name: 'Select Water Solutions', industry: 'Energy' },
  { ticker: 'NCSM', name: 'NCS Multistage Holdings', industry: 'Energy' },
  { ticker: 'PTEN', name: 'Patterson-UTI Energy', industry: 'Energy' },
  { ticker: 'HP', name: 'Helmerich & Payne', industry: 'Energy' },
  { ticker: 'NBR', name: 'Nabors Industries', industry: 'Energy' },
  { ticker: 'PD', name: 'Precision Drilling', industry: 'Energy' },
  { ticker: 'BORR', name: 'Borr Drilling', industry: 'Energy' },
  { ticker: 'RIG', name: 'Transocean Ltd.', industry: 'Energy' },
  { ticker: 'DO', name: 'Diamond Offshore Drilling', industry: 'Energy' },
  { ticker: 'VAL', name: 'Valaris Ltd.', industry: 'Energy' },
  { ticker: 'NE', name: 'Noble Corp.', industry: 'Energy' },
  { ticker: 'OII', name: 'Oceaneering International', industry: 'Energy' },
  { ticker: 'TGLS', name: 'Tecnoglass Inc.', industry: 'Energy' },
  { ticker: 'KMI', name: 'Kinder Morgan', industry: 'Energy' },
  { ticker: 'WMB', name: 'Williams Companies', industry: 'Energy' },
  { ticker: 'OKE', name: 'ONEOK Inc.', industry: 'Energy' },
  { ticker: 'ET', name: 'Energy Transfer LP', industry: 'Energy' },
  { ticker: 'EPD', name: 'Enterprise Products Partners', industry: 'Energy' },
  { ticker: 'MMP', name: 'Magellan Midstream', industry: 'Energy' },
  { ticker: 'PAA', name: 'Plains All American Pipeline', industry: 'Energy' },
  { ticker: 'TRGP', name: 'Targa Resources', industry: 'Energy' },
  { ticker: 'DT', name: 'Dynatrace Inc.', industry: 'Technology' },
  { ticker: 'AM', name: 'Antero Midstream', industry: 'Energy' },
  { ticker: 'CTRA', name: 'Coterra Energy', industry: 'Energy' },
  { ticker: 'AR', name: 'Antero Resources', industry: 'Energy' },
  { ticker: 'EQT', name: 'EQT Corporation', industry: 'Energy' },
  { ticker: 'RRC', name: 'Range Resources', industry: 'Energy' },
  { ticker: 'CNX', name: 'CNX Resources', industry: 'Energy' },
  { ticker: 'SWN', name: 'Southwestern Energy', industry: 'Energy' },
  { ticker: 'CHK', name: 'Chesapeake Energy', industry: 'Energy' },
  { ticker: 'CRK', name: 'Comstock Resources', industry: 'Energy' },
  { ticker: 'GPOR', name: 'Gulfport Energy', industry: 'Energy' },
  { ticker: 'SM', name: 'SM Energy', industry: 'Energy' },
  { ticker: 'MTDR', name: 'Matador Resources', industry: 'Energy' },
  { ticker: 'CIVI', name: 'Civitas Resources', industry: 'Energy' },
  { ticker: 'ESTE', name: 'Earthstone Energy', industry: 'Energy' },
  { ticker: 'VTLE', name: 'Vital Energy', industry: 'Energy' },
  { ticker: 'BATL', name: 'Battalion Oil', industry: 'Energy' },
  { ticker: 'TELL', name: 'Tellurian Inc.', industry: 'Energy' },
  { ticker: 'LNG', name: 'Cheniere Energy', industry: 'Energy' },
  { ticker: 'CQP', name: 'Cheniere Energy Partners', industry: 'Energy' },
  { ticker: 'NEXT', name: 'NextDecade Corp.', industry: 'Energy' },
  { ticker: 'GLNG', name: 'Golar LNG', industry: 'Energy' },
  { ticker: 'FLNG', name: 'FLEX LNG', industry: 'Energy' },
  { ticker: 'GMLP', name: 'Golar LNG Partners', industry: 'Energy' },
  { ticker: 'LEU', name: 'Centrus Energy Corp.', industry: 'Energy' },
  { ticker: 'CCJ', name: 'Cameco Corp.', industry: 'Energy' },
  { ticker: 'UEC', name: 'Uranium Energy Corp.', industry: 'Energy' },
  { ticker: 'UUUU', name: 'Energy Fuels Inc.', industry: 'Energy' },
  { ticker: 'DNN', name: 'Denison Mines', industry: 'Energy' },
  { ticker: 'URG', name: 'Ur-Energy Inc.', industry: 'Energy' },
  { ticker: 'PALAF', name: 'Paladin Energy', industry: 'Energy' },
  { ticker: 'NXE', name: 'NexGen Energy', industry: 'Energy' },
  { ticker: 'BQSSF', name: 'Boss Energy', industry: 'Energy' },
  { ticker: 'LTBR', name: 'Lightbridge Corp.', industry: 'Energy' },
  { ticker: 'SMR', name: 'NuScale Power', industry: 'Energy' },
  { ticker: 'OKLO', name: 'Oklo Inc.', industry: 'Energy' },
  { ticker: 'BWXT', name: 'BWX Technologies', industry: 'Energy' },
  { ticker: 'GEV', name: 'GE Vernova', industry: 'Energy' },
  { ticker: 'NEE', name: 'NextEra Energy', industry: 'Utilities' },
  { ticker: 'DUK', name: 'Duke Energy', industry: 'Utilities' },
  { ticker: 'SO', name: 'Southern Company', industry: 'Utilities' },
  { ticker: 'D', name: 'Dominion Energy', industry: 'Utilities' },
  { ticker: 'EXC', name: 'Exelon Corp.', industry: 'Utilities' },
  { ticker: 'AEP', name: 'American Electric Power', industry: 'Utilities' },
  { ticker: 'XEL', name: 'Xcel Energy', industry: 'Utilities' },
  { ticker: 'PEG', name: 'Public Service Enterprise', industry: 'Utilities' },
  { ticker: 'ED', name: 'Consolidated Edison', industry: 'Utilities' },
  { ticker: 'EIX', name: 'Edison International', industry: 'Utilities' },
  { ticker: 'PCG', name: 'PG&E Corporation', industry: 'Utilities' },
  { ticker: 'PPL', name: 'PPL Corporation', industry: 'Utilities' },
  { ticker: 'WEC', name: 'WEC Energy Group', industry: 'Utilities' },
  { ticker: 'ES', name: 'Eversource Energy', industry: 'Utilities' },
  { ticker: 'ETR', name: 'Entergy Corp.', industry: 'Utilities' },
  { ticker: 'FE', name: 'FirstEnergy Corp.', industry: 'Utilities' },
  { ticker: 'CMS', name: 'CMS Energy', industry: 'Utilities' },
  { ticker: 'NI', name: 'NiSource Inc.', industry: 'Utilities' },
  { ticker: 'LNT', name: 'Alliant Energy', industry: 'Utilities' },
  { ticker: 'EVRG', name: 'Evergy Inc.', industry: 'Utilities' },
  { ticker: 'AEE', name: 'Ameren Corp.', industry: 'Utilities' },
  { ticker: 'OGE', name: 'OGE Energy', industry: 'Utilities' },
  { ticker: 'AVA', name: 'Avista Corp.', industry: 'Utilities' },
  { ticker: 'IDACORP', name: 'IDACORP Inc.', industry: 'Utilities' },
  { ticker: 'IDA', name: 'IDACORP Inc.', industry: 'Utilities' },
  { ticker: 'POR', name: 'Portland General Electric', industry: 'Utilities' },
  { ticker: 'NWE', name: 'NorthWestern Energy', industry: 'Utilities' },
  { ticker: 'MGEE', name: 'MGE Energy', industry: 'Utilities' },
  { ticker: 'OTTR', name: 'Otter Tail Corp.', industry: 'Utilities' },
  { ticker: 'SWX', name: 'Southwest Gas Holdings', industry: 'Utilities' },
  { ticker: 'SR', name: 'Spire Inc.', industry: 'Utilities' },
  { ticker: 'NWN', name: 'Northwest Natural Holding', industry: 'Utilities' },
  { ticker: 'AWK', name: 'American Water Works', industry: 'Utilities' },
  { ticker: 'WTRG', name: 'Essential Utilities', industry: 'Utilities' },
  { ticker: 'CWT', name: 'California Water Service', industry: 'Utilities' },
  { ticker: 'MSEX', name: 'Middlesex Water', industry: 'Utilities' },
  { ticker: 'YORW', name: 'York Water', industry: 'Utilities' },
  { ticker: 'AWR', name: 'American States Water', industry: 'Utilities' },
  { ticker: 'SJW', name: 'SJW Group', industry: 'Utilities' },
  { ticker: 'ARTNA', name: 'Artesian Resources', industry: 'Utilities' },
  { ticker: 'GE', name: 'GE Aerospace', industry: 'Industrials' },
  { ticker: 'HON', name: 'Honeywell International', industry: 'Industrials' },
  { ticker: 'MMM', name: '3M Company', industry: 'Industrials' },
  { ticker: 'CAT', name: 'Caterpillar Inc.', industry: 'Industrials' },
  { ticker: 'DE', name: 'Deere & Company', industry: 'Industrials' },
  { ticker: 'EMR', name: 'Emerson Electric', industry: 'Industrials' },
  { ticker: 'ETN', name: 'Eaton Corporation', industry: 'Industrials' },
  { ticker: 'PH', name: 'Parker-Hannifin', industry: 'Industrials' },
  { ticker: 'ITW', name: 'Illinois Tool Works', industry: 'Industrials' },
  { ticker: 'ROK', name: 'Rockwell Automation', industry: 'Industrials' },
  { ticker: 'AME', name: 'AMETEK Inc.', industry: 'Industrials' },
  { ticker: 'CARR', name: 'Carrier Global', industry: 'Industrials' },
  { ticker: 'TT', name: 'Trane Technologies', industry: 'Industrials' },
  { ticker: 'JCI', name: 'Johnson Controls', industry: 'Industrials' },
  { ticker: 'LMT', name: 'Lockheed Martin', industry: 'Industrials' },
  { ticker: 'RTX', name: 'RTX Corporation', industry: 'Industrials' },
  { ticker: 'NOC', name: 'Northrop Grumman', industry: 'Industrials' },
  { ticker: 'GD', name: 'General Dynamics', industry: 'Industrials' },
  { ticker: 'BA', name: 'Boeing Co.', industry: 'Industrials' },
  { ticker: 'HII', name: 'Huntington Ingalls', industry: 'Industrials' },
  { ticker: 'L3HARRIS', name: 'L3Harris Technologies', industry: 'Industrials' },
  { ticker: 'LHX', name: 'L3Harris Technologies', industry: 'Industrials' },
  { ticker: 'TDG', name: 'TransDigm Group', industry: 'Industrials' },
  { ticker: 'HEI', name: 'HEICO Corp.', industry: 'Industrials' },
  { ticker: 'AXON', name: 'Axon Enterprise', industry: 'Industrials' },
  { ticker: 'TASER', name: 'Axon Enterprise', industry: 'Industrials' },
  { ticker: 'LDOS', name: 'Leidos Holdings', industry: 'Industrials' },
  { ticker: 'SAIC', name: 'Science Applications Int\'l', industry: 'Industrials' },
  { ticker: 'CACI', name: 'CACI International', industry: 'Industrials' },
  { ticker: 'MANT', name: 'ManTech International', industry: 'Industrials' },
  { ticker: 'BOOZ', name: 'Booz Allen Hamilton', industry: 'Industrials' },
  { ticker: 'BAH', name: 'Booz Allen Hamilton', industry: 'Industrials' },
  { ticker: 'KTOS', name: 'Kratos Defense & Security', industry: 'Industrials' },
  { ticker: 'PLTR', name: 'Palantir Technologies', industry: 'Technology' },
  { ticker: 'AI', name: 'C3.ai Inc.', industry: 'Technology' },
  { ticker: 'BBAI', name: 'BigBear.ai Holdings', industry: 'Technology' },
  { ticker: 'GFAI', name: 'Guardforce AI', industry: 'Technology' },
  { ticker: 'PRCT', name: 'PROCEPT BioRobotics', industry: 'Healthcare' },
  { ticker: 'AEHR', name: 'Aehr Test Systems', industry: 'Technology' },
  { ticker: 'AMBA', name: 'Ambarella Inc.', industry: 'Technology' },
  { ticker: 'ACHR', name: 'Archer Aviation', industry: 'Industrials' },
  { ticker: 'JOBY', name: 'Joby Aviation', industry: 'Industrials' },
  { ticker: 'LILM', name: 'Lilium N.V.', industry: 'Industrials' },
  { ticker: 'EVTOL', name: 'eVTOL', industry: 'Industrials' },
  { ticker: 'BLADE', name: 'Blade Air Mobility', industry: 'Industrials' },
  { ticker: 'SURF', name: 'Surface Oncology', industry: 'Healthcare' },
  { ticker: 'SPCE', name: 'Virgin Galactic Holdings', industry: 'Industrials' },
  { ticker: 'RKLB', name: 'Rocket Lab USA', industry: 'Industrials' },
  { ticker: 'ASTR', name: 'Astra Space', industry: 'Industrials' },
  { ticker: 'MNTS', name: 'Momentus Inc.', industry: 'Industrials' },
  { ticker: 'ASTS', name: 'AST SpaceMobile', industry: 'Communication Services' },
  { ticker: 'SATL', name: 'Satellogic Inc.', industry: 'Communication Services' },
  { ticker: 'SPIR', name: 'Spire Global', industry: 'Communication Services' },
  { ticker: 'GSAT', name: 'Globalstar Inc.', industry: 'Communication Services' },
  { ticker: 'VSAT', name: 'ViaSat Inc.', industry: 'Communication Services' },
  { ticker: 'MAXR', name: 'Maxar Technologies', industry: 'Communication Services' },
  { ticker: 'BGSF', name: 'BGSF Inc.', industry: 'Industrials' },
  { ticker: 'KFRC', name: 'Kforce Inc.', industry: 'Industrials' },
  { ticker: 'MAN', name: 'ManpowerGroup', industry: 'Industrials' },
  { ticker: 'RHI', name: 'Robert Half International', industry: 'Industrials' },
  { ticker: 'KELYA', name: 'Kelly Services', industry: 'Industrials' },
  { ticker: 'HCSG', name: 'Healthcare Services Group', industry: 'Industrials' },
  { ticker: 'ABM', name: 'ABM Industries', industry: 'Industrials' },
  { ticker: 'CTAS', name: 'Cintas Corporation', industry: 'Industrials' },
  { ticker: 'ARMK', name: 'Aramark Holdings', industry: 'Industrials' },
  { ticker: 'SBAC', name: 'SBA Communications', industry: 'Real Estate' },
  { ticker: 'AMT', name: 'American Tower Corp.', industry: 'Real Estate' },
  { ticker: 'CCI', name: 'Crown Castle Inc.', industry: 'Real Estate' },
  { ticker: 'UNIT', name: 'Uniti Group', industry: 'Real Estate' },
  { ticker: 'ZAYO', name: 'Zayo Group', industry: 'Communication Services' },
  { ticker: 'CCOI', name: 'Cogent Communications', industry: 'Communication Services' },
  { ticker: 'CNSL', name: 'Consolidated Communications', industry: 'Communication Services' },
  { ticker: 'SHEN', name: 'Shenandoah Telecom', industry: 'Communication Services' },
  { ticker: 'GLOW', name: 'Globalink Telecom', industry: 'Communication Services' },
  { ticker: 'USCR', name: 'US Concrete', industry: 'Materials' },
  { ticker: 'VMC', name: 'Vulcan Materials', industry: 'Materials' },
  { ticker: 'MLM', name: 'Martin Marietta Materials', industry: 'Materials' },
  { ticker: 'SUM', name: 'Summit Materials', industry: 'Materials' },
  { ticker: 'EXP', name: 'Eagle Materials', industry: 'Materials' },
  { ticker: 'USG', name: 'USG Corporation', industry: 'Materials' },
  { ticker: 'AWI', name: 'Armstrong World Industries', industry: 'Materials' },
  { ticker: 'TREX', name: 'Trex Company', industry: 'Materials' },
  { ticker: 'AZEK', name: 'AZEK Company', industry: 'Materials' },
  { ticker: 'FBHS', name: 'Fortune Brands Innovations', industry: 'Materials' },
  { ticker: 'MAS', name: 'Masco Corp.', industry: 'Materials' },
  { ticker: 'PGTI', name: 'PGT Innovations', industry: 'Materials' },
  { ticker: 'DOOR', name: 'Masonite International', industry: 'Materials' },
  { ticker: 'JELD', name: 'JELD-WEN Holding', industry: 'Materials' },
  { ticker: 'AMWD', name: 'American Woodmark', industry: 'Materials' },
  { ticker: 'PATK', name: 'Patrick Industries', industry: 'Materials' },
  { ticker: 'BECN', name: 'Beacon Roofing Supply', industry: 'Materials' },
  { ticker: 'IBP', name: 'Installed Building Products', industry: 'Materials' },
  { ticker: 'BLDR', name: 'Builders FirstSource', industry: 'Materials' },
  { ticker: 'BCC', name: 'Boise Cascade', industry: 'Materials' },
  { ticker: 'UFP', name: 'UFP Technologies', industry: 'Materials' },
  { ticker: 'UFPI', name: 'UFP Industries', industry: 'Materials' },
  { ticker: 'WY', name: 'Weyerhaeuser Co.', industry: 'Materials' },
  { ticker: 'PCH', name: 'PotlatchDeltic Corp.', industry: 'Materials' },
  { ticker: 'RYN', name: 'Rayonier Inc.', industry: 'Real Estate' },
  { ticker: 'IP', name: 'International Paper', industry: 'Materials' },
  { ticker: 'PKG', name: 'Packaging Corp. of America', industry: 'Materials' },
  { ticker: 'SEE', name: 'Sealed Air Corp.', industry: 'Materials' },
  { ticker: 'BALL', name: 'Ball Corporation', industry: 'Materials' },
  { ticker: 'BMS', name: 'Bemis Company', industry: 'Materials' },
  { ticker: 'BERY', name: 'Berry Global Group', industry: 'Materials' },
  { ticker: 'SLGN', name: 'Silgan Holdings', industry: 'Materials' },
  { ticker: 'PHIN', name: 'PHINIA Inc.', industry: 'Industrials' },
  { ticker: 'ATI', name: 'ATI Inc.', industry: 'Materials' },
  { ticker: 'X', name: 'United States Steel', industry: 'Materials' },
  { ticker: 'NUE', name: 'Nucor Corporation', industry: 'Materials' },
  { ticker: 'STLD', name: 'Steel Dynamics', industry: 'Materials' },
  { ticker: 'CMC', name: 'Commercial Metals', industry: 'Materials' },
  { ticker: 'RS', name: 'Reliance Steel & Aluminum', industry: 'Materials' },
  { ticker: 'ZEUS', name: 'Olympic Steel', industry: 'Materials' },
  { ticker: 'KALU', name: 'Kaiser Aluminum', industry: 'Materials' },
  { ticker: 'CENX', name: 'Century Aluminum', industry: 'Materials' },
  { ticker: 'AA', name: 'Alcoa Corporation', industry: 'Materials' },
  { ticker: 'ARNC', name: 'Arconic Inc.', industry: 'Materials' },
  { ticker: 'HWM', name: 'Howmet Aerospace', industry: 'Materials' },
  { ticker: 'FCX', name: 'Freeport-McMoRan', industry: 'Materials' },
  { ticker: 'SCCO', name: 'Southern Copper', industry: 'Materials' },
  { ticker: 'TECK', name: 'Teck Resources', industry: 'Materials' },
  { ticker: 'CLF', name: 'Cleveland-Cliffs', industry: 'Materials' },
  { ticker: 'AKS', name: 'AK Steel Holding', industry: 'Materials' },
  { ticker: 'WOR', name: 'Worthington Industries', industry: 'Materials' },
  { ticker: 'MTRN', name: 'Materion Corp.', industry: 'Materials' },
  { ticker: 'MP', name: 'MP Materials', industry: 'Materials' },
  { ticker: 'MPLN', name: 'MultiPlan Corp.', industry: 'Healthcare' },
  { ticker: 'LTHM', name: 'Livent Corp.', industry: 'Materials' },
  { ticker: 'ALB', name: 'Albemarle Corp.', industry: 'Materials' },
  { ticker: 'SQM', name: 'Sociedad Quimica y Minera', industry: 'Materials' },
  { ticker: 'PLL', name: 'Piedmont Lithium', industry: 'Materials' },
  { ticker: 'LAC', name: 'Lithium Americas', industry: 'Materials' },
  { ticker: 'LAAC', name: 'Lithium Americas Argentina', industry: 'Materials' },
  { ticker: 'SGML', name: 'Sigma Lithium', industry: 'Materials' },
  { ticker: 'AMLI', name: 'Amli Residential', industry: 'Real Estate' },
  { ticker: 'LI', name: 'Li-Cycle Holdings', industry: 'Materials' },
  { ticker: 'ALTM', name: 'Arclight Clean Transition', industry: 'Energy' },
  { ticker: 'PLUG', name: 'Plug Power Inc.', industry: 'Energy' },
  { ticker: 'FCEL', name: 'FuelCell Energy', industry: 'Energy' },
  { ticker: 'BLDP', name: 'Ballard Power Systems', industry: 'Energy' },
  { ticker: 'BE', name: 'Bloom Energy', industry: 'Energy' },
  { ticker: 'HYLN', name: 'Hyliion Holdings', industry: 'Energy' },
  { ticker: 'NKLA', name: 'Nikola Corporation', industry: 'Energy' },
  { ticker: 'HYZN', name: 'Hyzon Motors', industry: 'Energy' },
  { ticker: 'CLNE', name: 'Clean Energy Fuels', industry: 'Energy' },
  { ticker: 'AMRC', name: 'Ameresco Inc.', industry: 'Energy' },
  { ticker: 'NOVA', name: 'Sunnova Energy', industry: 'Energy' },
  { ticker: 'RUN', name: 'Sunrun Inc.', industry: 'Energy' },
  { ticker: 'ENPH', name: 'Enphase Energy', industry: 'Energy' },
  { ticker: 'SEDG', name: 'SolarEdge Technologies', industry: 'Energy' },
  { ticker: 'FSLR', name: 'First Solar Inc.', industry: 'Energy' },
  { ticker: 'SPWR', name: 'SunPower Corp.', industry: 'Energy' },
  { ticker: 'ARRY', name: 'Array Technologies', industry: 'Energy' },
  { ticker: 'SHLS', name: 'Shoals Technologies', industry: 'Energy' },
  { ticker: 'STEM', name: 'Stem Inc.', industry: 'Energy' },
  { ticker: 'FLUX', name: 'Flux Power Holdings', industry: 'Energy' },
  { ticker: 'AMPS', name: 'Altus Power', industry: 'Energy' },
  { ticker: 'CWEN', name: 'Clearway Energy', industry: 'Utilities' },
  { ticker: 'AY', name: 'Atlantica Sustainable', industry: 'Utilities' },
  { ticker: 'TERP', name: 'TerraForm Power', industry: 'Utilities' },
  { ticker: 'VNET', name: 'VNET Group', industry: 'Technology' },
  { ticker: 'SPG', name: 'Simon Property Group', industry: 'Real Estate' },
  { ticker: 'O', name: 'Realty Income Corp.', industry: 'Real Estate' },
  { ticker: 'PLD', name: 'Prologis Inc.', industry: 'Real Estate' },
  { ticker: 'WELL', name: 'Welltower Inc.', industry: 'Real Estate' },
  { ticker: 'VTR', name: 'Ventas Inc.', industry: 'Real Estate' },
  { ticker: 'EQR', name: 'Equity Residential', industry: 'Real Estate' },
  { ticker: 'AVB', name: 'AvalonBay Communities', industry: 'Real Estate' },
  { ticker: 'MAA', name: 'Mid-America Apartment', industry: 'Real Estate' },
  { ticker: 'UDR', name: 'UDR Inc.', industry: 'Real Estate' },
  { ticker: 'CPT', name: 'Camden Property Trust', industry: 'Real Estate' },
  { ticker: 'ESS', name: 'Essex Property Trust', industry: 'Real Estate' },
  { ticker: 'NNN', name: 'NNN REIT', industry: 'Real Estate' },
  { ticker: 'WPC', name: 'W. P. Carey Inc.', industry: 'Real Estate' },
  { ticker: 'STOR', name: 'STORE Capital', industry: 'Real Estate' },
  { ticker: 'ADC', name: 'Agree Realty', industry: 'Real Estate' },
  { ticker: 'EPRT', name: 'Essential Properties Realty', industry: 'Real Estate' },
  { ticker: 'NTST', name: 'NETSTREIT Corp.', industry: 'Real Estate' },
  { ticker: 'GTY', name: 'Getty Realty', industry: 'Real Estate' },
  { ticker: 'FCPT', name: 'Four Corners Property', industry: 'Real Estate' },
  { ticker: 'PINE', name: 'Alpine Income Property', industry: 'Real Estate' },
  { ticker: 'VNO', name: 'Vornado Realty Trust', industry: 'Real Estate' },
  { ticker: 'SL', name: 'SL Green Realty', industry: 'Real Estate' },
  { ticker: 'SLG', name: 'SL Green Realty', industry: 'Real Estate' },
  { ticker: 'BXP', name: 'BXP Inc.', industry: 'Real Estate' },
  { ticker: 'HIW', name: 'Highwoods Properties', industry: 'Real Estate' },
  { ticker: 'PDM', name: 'Piedmont Office Realty', industry: 'Real Estate' },
  { ticker: 'CUZ', name: 'Cousins Properties', industry: 'Real Estate' },
  { ticker: 'PGRE', name: 'Paramount Group', industry: 'Real Estate' },
  { ticker: 'DEA', name: 'Easterly Government Properties', industry: 'Real Estate' },
  { ticker: 'EGP', name: 'EastGroup Properties', industry: 'Real Estate' },
  { ticker: 'REXR', name: 'Rexford Industrial Realty', industry: 'Real Estate' },
  { ticker: 'STAG', name: 'STAG Industrial', industry: 'Real Estate' },
  { ticker: 'FR', name: 'First Industrial Realty', industry: 'Real Estate' },
  { ticker: 'LPT', name: 'Liberty Property Trust', industry: 'Real Estate' },
  { ticker: 'COLD', name: 'Americold Realty Trust', industry: 'Real Estate' },
  { ticker: 'CUBE', name: 'CubeSmart', industry: 'Real Estate' },
  { ticker: 'EXR', name: 'Extra Space Storage', industry: 'Real Estate' },
  { ticker: 'PSA', name: 'Public Storage', industry: 'Real Estate' },
  { ticker: 'LSI', name: 'Life Storage', industry: 'Real Estate' },
  { ticker: 'NSA', name: 'National Storage Affiliates', industry: 'Real Estate' },
  { ticker: 'SELF', name: 'Global Self Storage', industry: 'Real Estate' },
  { ticker: 'LADR', name: 'Ladder Capital', industry: 'Real Estate' },
  { ticker: 'BXMT', name: 'Blackstone Mortgage Trust', industry: 'Real Estate' },
  { ticker: 'KREF', name: 'KKR Real Estate Finance', industry: 'Real Estate' },
  { ticker: 'GPMT', name: 'Granite Point Mortgage', industry: 'Real Estate' },
  { ticker: 'TRTX', name: 'Terra Property Trust', industry: 'Real Estate' },
  { ticker: 'ACRE', name: 'Ares Commercial Real Estate', industry: 'Real Estate' },
  { ticker: 'FBRT', name: 'Franklin BSP Realty Trust', industry: 'Real Estate' },
  { ticker: 'BRSP', name: 'BrightSpire Capital', industry: 'Real Estate' },
  { ticker: 'CLNC', name: 'Colony Credit Real Estate', industry: 'Real Estate' },
  { ticker: 'RC', name: 'Ready Capital Corp.', industry: 'Real Estate' },
  { ticker: 'HASI', name: 'Hannon Armstrong', industry: 'Real Estate' },
  { ticker: 'IIPR', name: 'Innovative Industrial Properties', industry: 'Real Estate' },
  { ticker: 'SAFE', name: 'Saul Centers', industry: 'Real Estate' },
  { ticker: 'SKT', name: 'Tanger Factory Outlet', industry: 'Real Estate' },
  { ticker: 'MAC', name: 'Macerich Co.', industry: 'Real Estate' },
  { ticker: 'CBL', name: 'CBL & Associates', industry: 'Real Estate' },
  { ticker: 'WPG', name: 'Washington Prime Group', industry: 'Real Estate' },
  { ticker: 'PEI', name: 'Pennsylvania REIT', industry: 'Real Estate' },
  { ticker: 'PREIT', name: 'Pennsylvania REIT', industry: 'Real Estate' },
  { ticker: 'ROIC', name: 'Retail Opportunity Investments', industry: 'Real Estate' },
  { ticker: 'KIM', name: 'Kimco Realty', industry: 'Real Estate' },
  { ticker: 'REG', name: 'Regency Centers', industry: 'Real Estate' },
  { ticker: 'BRX', name: 'Brixmor Property Group', industry: 'Real Estate' },
  { ticker: 'AKR', name: 'Acadia Realty Trust', industry: 'Real Estate' },
  { ticker: 'RPAI', name: 'Inland Real Estate', industry: 'Real Estate' },
  { ticker: 'SITC', name: 'SITE Centers', industry: 'Real Estate' },
  { ticker: 'WRI', name: 'Weingarten Realty', industry: 'Real Estate' },
  { ticker: 'UE', name: 'Urban Edge Properties', industry: 'Real Estate' },
  { ticker: 'NXRT', name: 'NexPoint Residential Trust', industry: 'Real Estate' },
  { ticker: 'IRT', name: 'Independence Realty Trust', industry: 'Real Estate' },
  { ticker: 'NREF', name: 'NexPoint Real Estate Finance', industry: 'Real Estate' },
  { ticker: 'INVH', name: 'Invitation Homes', industry: 'Real Estate' },
  { ticker: 'AMH', name: 'American Homes 4 Rent', industry: 'Real Estate' },
  { ticker: 'TRICON', name: 'Tricon Residential', industry: 'Real Estate' },
  { ticker: 'TCN', name: 'Tricon Residential', industry: 'Real Estate' },
  { ticker: 'RDFN', name: 'Redfin Corp.', industry: 'Real Estate' },
  { ticker: 'COMP', name: 'Compass Inc.', industry: 'Real Estate' },
  { ticker: 'EXPI', name: 'eXp World Holdings', industry: 'Real Estate' },
  { ticker: 'HOUS', name: 'Anywhere Real Estate', industry: 'Real Estate' },
  { ticker: 'RMR', name: 'RMR Group', industry: 'Real Estate' },
  { ticker: 'SPY', name: 'SPDR S&P 500 ETF', industry: 'ETF' },
  { ticker: 'QQQ', name: 'Invesco QQQ Trust', industry: 'ETF' },
  { ticker: 'IWM', name: 'iShares Russell 2000 ETF', industry: 'ETF' },
  { ticker: 'DIA', name: 'SPDR Dow Jones ETF', industry: 'ETF' },
  { ticker: 'VOO', name: 'Vanguard S&P 500 ETF', industry: 'ETF' },
  { ticker: 'VTI', name: 'Vanguard Total Stock Market ETF', industry: 'ETF' },
  { ticker: 'VEA', name: 'Vanguard FTSE Developed Markets ETF', industry: 'ETF' },
  { ticker: 'VWO', name: 'Vanguard FTSE Emerging Markets ETF', industry: 'ETF' },
  { ticker: 'GLD', name: 'SPDR Gold Shares', industry: 'ETF' },
  { ticker: 'SLV', name: 'iShares Silver Trust', industry: 'ETF' },
  { ticker: 'TLT', name: 'iShares 20+ Year Treasury Bond ETF', industry: 'ETF' },
  { ticker: 'HYG', name: 'iShares iBoxx High Yield ETF', industry: 'ETF' },
  { ticker: 'LQD', name: 'iShares iBoxx Investment Grade ETF', industry: 'ETF' },
  { ticker: 'ARKK', name: 'ARK Innovation ETF', industry: 'ETF' },
  { ticker: 'ARKW', name: 'ARK Next Generation Internet ETF', industry: 'ETF' },
  { ticker: 'ARKG', name: 'ARK Genomic Revolution ETF', industry: 'ETF' },
  { ticker: 'ARKF', name: 'ARK Fintech Innovation ETF', industry: 'ETF' },
  { ticker: 'ARKX', name: 'ARK Space Exploration ETF', industry: 'ETF' },
  { ticker: 'BOTZ', name: 'Global X Robotics & AI ETF', industry: 'ETF' },
  { ticker: 'ROBO', name: 'ROBO Global Robotics ETF', industry: 'ETF' },
  { ticker: 'IRBO', name: 'iShares Robotics & AI ETF', industry: 'ETF' },
  { ticker: 'SOXX', name: 'iShares Semiconductor ETF', industry: 'ETF' },
  { ticker: 'SMH', name: 'VanEck Semiconductor ETF', industry: 'ETF' },
  { ticker: 'XLK', name: 'Technology Select Sector SPDR', industry: 'ETF' },
  { ticker: 'XLF', name: 'Financial Select Sector SPDR', industry: 'ETF' },
  { ticker: 'XLV', name: 'Health Care Select Sector SPDR', industry: 'ETF' },
  { ticker: 'XLE', name: 'Energy Select Sector SPDR', industry: 'ETF' },
  { ticker: 'XLI', name: 'Industrial Select Sector SPDR', industry: 'ETF' },
  { ticker: 'XLY', name: 'Consumer Discretionary SPDR', industry: 'ETF' },
  { ticker: 'XLP', name: 'Consumer Staples SPDR', industry: 'ETF' },
  { ticker: 'XLU', name: 'Utilities Select Sector SPDR', industry: 'ETF' },
  { ticker: 'XLRE', name: 'Real Estate Select Sector SPDR', industry: 'ETF' },
  { ticker: 'XLB', name: 'Materials Select Sector SPDR', industry: 'ETF' },
  { ticker: 'XLC', name: 'Communication Services SPDR', industry: 'ETF' },
  { ticker: 'SCHD', name: 'Schwab US Dividend Equity ETF', industry: 'ETF' },
  { ticker: 'VIG', name: 'Vanguard Dividend Appreciation ETF', industry: 'ETF' },
  { ticker: 'DGRO', name: 'iShares Core Dividend Growth ETF', industry: 'ETF' },
  { ticker: 'NOBL', name: 'ProShares S&P 500 Dividend Aristocrats', industry: 'ETF' },
  { ticker: 'HDV', name: 'iShares Core High Dividend ETF', industry: 'ETF' },
  { ticker: 'SPHD', name: 'Invesco S&P 500 High Dividend Low Volatility ETF', industry: 'ETF' },
  { ticker: 'JEPI', name: 'JPMorgan Equity Premium Income ETF', industry: 'ETF' },
  { ticker: 'JEPQ', name: 'JPMorgan Nasdaq Equity Premium Income ETF', industry: 'ETF' },
  { ticker: 'XYLD', name: 'Global X S&P 500 Covered Call ETF', industry: 'ETF' },
  { ticker: 'QYLD', name: 'Global X Nasdaq 100 Covered Call ETF', industry: 'ETF' },
  { ticker: 'RYLD', name: 'Global X Russell 2000 Covered Call ETF', industry: 'ETF' },
  { ticker: 'MSFO', name: 'YieldMax MSFT Option Income ETF', industry: 'ETF' },
  { ticker: 'NVDO', name: 'YieldMax NVDA Option Income ETF', industry: 'ETF' },
  { ticker: 'TSLY', name: 'YieldMax TSLA Option Income ETF', industry: 'ETF' },
  { ticker: 'AMZY', name: 'YieldMax AMZN Option Income ETF', industry: 'ETF' },
  { ticker: 'GOOGY', name: 'YieldMax GOOGL Option Income ETF', industry: 'ETF' },
  { ticker: 'CONY', name: 'YieldMax COIN Option Income ETF', industry: 'ETF' },
  { ticker: 'MSTY', name: 'YieldMax MSTR Option Income ETF', industry: 'ETF' },
  { ticker: 'PLTY', name: 'YieldMax PLTR Option Income ETF', industry: 'ETF' },
  { ticker: 'YMAX', name: 'YieldMax Universe Fund of Option Income ETFs', industry: 'ETF' },
  { ticker: 'YMAG', name: 'YieldMax Magnificent 7 Fund', industry: 'ETF' },
  { ticker: 'BITO', name: 'ProShares Bitcoin Strategy ETF', industry: 'ETF' },
  { ticker: 'BITI', name: 'ProShares Short Bitcoin ETF', industry: 'ETF' },
  { ticker: 'ETHE', name: 'Grayscale Ethereum Trust', industry: 'ETF' },
  { ticker: 'ETHU', name: 'ProShares Ether Strategy ETF', industry: 'ETF' },
  { ticker: 'ASML', name: 'ASML Holding N.V.', industry: 'Technology' },
  { ticker: 'TSM', name: 'Taiwan Semiconductor', industry: 'Technology' },
  { ticker: 'ARM', name: 'Arm Holdings plc', industry: 'Technology' },
  { ticker: 'SMCI', name: 'Super Micro Computer', industry: 'Technology' },
  { ticker: 'ALAB', name: 'Astera Labs', industry: 'Technology' },
  { ticker: 'CRUS', name: 'Cirrus Logic', industry: 'Technology' },
  { ticker: 'WOLF', name: 'Wolfspeed Inc.', industry: 'Technology' },
  { ticker: 'IPSIDY', name: 'Identiv Inc.', industry: 'Technology' },
  { ticker: 'IDNV', name: 'Identiv Inc.', industry: 'Technology' },
  { ticker: 'IDAI', name: 'T2 Biosystems', industry: 'Healthcare' },
  { ticker: 'IDEX', name: 'Ideanomics Inc.', industry: 'Energy' },
  { ticker: 'IONQ', name: 'IonQ Inc.', industry: 'Technology' },
  { ticker: 'RGTI', name: 'Rigetti Computing', industry: 'Technology' },
  { ticker: 'QUBT', name: 'Quantum Computing Inc.', industry: 'Technology' },
  { ticker: 'QBTS', name: 'D-Wave Quantum', industry: 'Technology' },
  { ticker: 'ARQQ', name: 'Arqit Quantum', industry: 'Technology' },
  { ticker: 'QTUM', name: 'Defiance Quantum ETF', industry: 'ETF' },
  { ticker: 'SOUN', name: 'SoundHound AI', industry: 'Technology' },
  { ticker: 'AITX', name: 'Artificial Intelligence Technology Solutions', industry: 'Technology' },
  { ticker: 'AIXI', name: 'Xiao-I Corporation', industry: 'Technology' },
  { ticker: 'AIOT', name: 'PowerFleet Inc.', industry: 'Technology' },
  { ticker: 'AISP', name: 'Airspan Networks', industry: 'Technology' },
  { ticker: 'PATH', name: 'UiPath Inc.', industry: 'Technology' },
  { ticker: 'PAYO', name: 'Payoneer Global', industry: 'Financials' },
  { ticker: 'FLYW', name: 'Flywire Corp.', industry: 'Financials' },
  { ticker: 'RELY', name: 'Remitly Global', industry: 'Financials' },
  { ticker: 'NUVEI', name: 'Nuvei Corporation', industry: 'Financials' },
  { ticker: 'NVEI', name: 'Nuvei Corporation', industry: 'Financials' },
  { ticker: 'FOUR', name: 'Shift4 Payments', industry: 'Financials' },
  { ticker: 'PAGS', name: 'PagSeguro Digital', industry: 'Financials' },
  { ticker: 'STNE', name: 'StoneCo Ltd.', industry: 'Financials' },
  { ticker: 'CPAY', name: 'Corpay Inc.', industry: 'Financials' },
  { ticker: 'WEX', name: 'WEX Inc.', industry: 'Financials' },
  { ticker: 'REPAY', name: 'Repay Holdings', industry: 'Financials' },
  { ticker: 'I2C', name: 'i2c Inc.', industry: 'Financials' },
  { ticker: 'EVTC', name: 'EVERTEC Inc.', industry: 'Financials' },
  { ticker: 'PRAA', name: 'PRA Group', industry: 'Financials' },
  { ticker: 'ECPG', name: 'Encore Capital Group', industry: 'Financials' },
  { ticker: 'PFSI', name: 'PennyMac Financial Services', industry: 'Financials' },
  { ticker: 'PMT', name: 'PennyMac Mortgage Trust', industry: 'Financials' },
  { ticker: 'UWMC', name: 'UWM Holdings', industry: 'Financials' },
  { ticker: 'RKT', name: 'Rocket Companies', industry: 'Financials' },
  { ticker: 'GHLD', name: 'Guild Holdings', industry: 'Financials' },
  { ticker: 'HMPT', name: 'Home Point Capital', industry: 'Financials' },
  { ticker: 'LNKD', name: 'LinkedIn Corp.', industry: 'Technology' },
  { ticker: 'SEND', name: 'Clearbit', industry: 'Technology' },
  { ticker: 'BRZE', name: 'Braze Inc.', industry: 'Technology' },
  { ticker: 'AMPL', name: 'Amplitude Inc.', industry: 'Technology' },
  { ticker: 'MIXPANEL', name: 'Mixpanel', industry: 'Technology' },
  { ticker: 'CLARI', name: 'Clari Inc.', industry: 'Technology' },
  { ticker: 'GONG', name: 'Gong.io', industry: 'Technology' },
  { ticker: 'OUTREACH', name: 'Outreach Corp.', industry: 'Technology' },
  { ticker: 'SALESLOFT', name: 'Salesloft', industry: 'Technology' },
  { ticker: 'SPOK', name: 'Spok Holdings', industry: 'Communication Services' },
  { ticker: 'LPSN', name: 'LivePerson Inc.', industry: 'Technology' },
  { ticker: 'SPRINKLR', name: 'Sprinklr Inc.', industry: 'Technology' },
  { ticker: 'CXM', name: 'Sprinklr Inc.', industry: 'Technology' },
  { ticker: 'BMBL', name: 'Bumble Inc.', industry: 'Communication Services' },
  { ticker: 'GRND', name: 'Grindr Inc.', industry: 'Communication Services' },
  { ticker: 'MOMO', name: 'Hello Group Inc.', industry: 'Communication Services' },
  { ticker: 'QUDIAN', name: 'Qudian Inc.', industry: 'Financials' },
  { ticker: 'LXEH', name: 'Lixiang Education', industry: 'Consumer Discretionary' },
  { ticker: 'TIGR', name: 'UP Fintech Holding', industry: 'Financials' },
  { ticker: 'FUTU', name: 'Futu Holdings', industry: 'Financials' },
  { ticker: 'WEBULL', name: 'Webull Corp.', industry: 'Financials' },
  { ticker: 'MELI', name: 'MercadoLibre Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'SE', name: 'Sea Limited', industry: 'Consumer Discretionary' },
  { ticker: 'GRAB', name: 'Grab Holdings', industry: 'Consumer Discretionary' },
  { ticker: 'GOTO', name: 'GoTo Group', industry: 'Consumer Discretionary' },
  { ticker: 'BABA', name: 'Alibaba Group', industry: 'Consumer Discretionary' },
  { ticker: 'JD', name: 'JD.com Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'PDD', name: 'PDD Holdings', industry: 'Consumer Discretionary' },
  { ticker: 'BIDU', name: 'Baidu Inc.', industry: 'Communication Services' },
  { ticker: 'TCEHY', name: 'Tencent Holdings', industry: 'Communication Services' },
  { ticker: 'NIO', name: 'NIO Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'XPEV', name: 'XPeng Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'ZEEKR', name: 'ZEEKR Intelligent Electric', industry: 'Consumer Discretionary' },
  { ticker: 'RIVN', name: 'Rivian Automotive', industry: 'Consumer Discretionary' },
  { ticker: 'LCID', name: 'Lucid Group', industry: 'Consumer Discretionary' },
  { ticker: 'FSR', name: 'Fisker Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'GOEV', name: 'Canoo Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'WKHS', name: 'Workhorse Group', industry: 'Consumer Discretionary' },
  { ticker: 'RIDE', name: 'Lordstown Motors', industry: 'Consumer Discretionary' },
  { ticker: 'SOLO', name: 'Electrameccanica Vehicles', industry: 'Consumer Discretionary' },
  { ticker: 'AYRO', name: 'AYRO Inc.', industry: 'Consumer Discretionary' },
  { ticker: 'ARVL', name: 'Arrival S.A.', industry: 'Consumer Discretionary' },
  { ticker: 'MULN', name: 'Mullen Automotive', industry: 'Consumer Discretionary' },
  { ticker: 'IDRA', name: 'Idera Pharmaceuticals', industry: 'Healthcare' },
  { ticker: 'OPFI', name: 'OppFi Inc.', industry: 'Financials' },
  { ticker: 'DAVE', name: 'Dave Inc.', industry: 'Financials' },
  { ticker: 'MONEYLION', name: 'MoneyLion Inc.', industry: 'Financials' },
  { ticker: 'ML', name: 'MoneyLion Inc.', industry: 'Financials' },
  { ticker: 'EZCORP', name: 'EZCORP Inc.', industry: 'Financials' },
  { ticker: 'EZPW', name: 'EZCORP Inc.', industry: 'Financials' },
  { ticker: 'FCFS', name: 'FirstCash Holdings', industry: 'Financials' },
  { ticker: 'DFC', name: 'Dollar Financial Group', industry: 'Financials' },
  { ticker: 'QCRH', name: 'QCR Holdings', industry: 'Financials' },
  { ticker: 'FFBC', name: 'First Financial Bancorp', industry: 'Financials' },
  { ticker: 'FRME', name: 'First Merchants Corp.', industry: 'Financials' },
  { ticker: 'HTLF', name: 'Heartland Financial', industry: 'Financials' },
  { ticker: 'RNST', name: 'Renasant Corp.', industry: 'Financials' },
  { ticker: 'SBCF', name: 'Seacoast Banking', industry: 'Financials' },
  { ticker: 'TRMK', name: 'Trustmark Corp.', industry: 'Financials' },
  { ticker: 'BANF', name: 'BancFirst Corp.', industry: 'Financials' },
  { ticker: 'BSVN', name: 'Bank7 Corp.', industry: 'Financials' },
  { ticker: 'CBTX', name: 'CommunityBank of Texas', industry: 'Financials' },
  { ticker: 'TCBK', name: 'TriCo Bancshares', industry: 'Financials' },
  { ticker: 'HAFC', name: 'Hanmi Financial', industry: 'Financials' },
  { ticker: 'HOPE', name: 'Hope Bancorp', industry: 'Financials' },
  { ticker: 'MCBC', name: 'Mackinac Savings Bank', industry: 'Financials' },
  { ticker: 'ESSA', name: 'ESSA Bancorp', industry: 'Financials' },
  { ticker: 'PFIS', name: 'Peoples Financial Services', industry: 'Financials' },
  { ticker: 'AMNB', name: 'American National Bankshares', industry: 'Financials' },
  { ticker: 'BFST', name: 'Business First Bancshares', industry: 'Financials' },
  { ticker: 'FBMS', name: 'The First Bancshares', industry: 'Financials' },
  { ticker: 'HONE', name: 'HarborOne Bancorp', industry: 'Financials' },
  { ticker: 'LBAI', name: 'Lakeland Bancorp', industry: 'Financials' },
  { ticker: 'MBIN', name: 'Merchants Financial Group', industry: 'Financials' },
  { ticker: 'NFBK', name: 'Northfield Bancorp', industry: 'Financials' },
  { ticker: 'OBNK', name: 'Origin Bancorp', industry: 'Financials' },
  { ticker: 'PEBO', name: 'Peoples Bancorp', industry: 'Financials' },
  { ticker: 'PLBC', name: 'Plumas Bank', industry: 'Financials' },
  { ticker: 'QNBC', name: 'QNB Corp.', industry: 'Financials' },
  { ticker: 'RIVR', name: 'River Valley Bancorp', industry: 'Financials' },
  { ticker: 'SBSI', name: 'Southside Bancshares', industry: 'Financials' },
  { ticker: 'TCBF', name: 'TC Bancshares', industry: 'Financials' },
  { ticker: 'UVSP', name: 'Univest Financial', industry: 'Financials' },
  { ticker: 'VBTX', name: 'Veritex Community Bank', industry: 'Financials' },
  { ticker: 'WAFD', name: 'Washington Federal', industry: 'Financials' },
  { ticker: 'XBKS', name: 'Xenith Bankshares', industry: 'Financials' },
  { ticker: 'YDKN', name: 'Yadkin Valley Financial', industry: 'Financials' },
  { ticker: 'LUNR', name: 'Intuitive Machines', industry: 'Industrials' },
  { ticker: 'BLDE', name: 'Blade Air Mobility', industry: 'Industrials' },
];
