// This file is a placeholder - it gets replaced by the build script
// The real handler is generated by: esbuild server/_core/app-prod.ts --format=esm --outfile=api/index.mjs
export default function handler(req, res) {
  res.status(503).json({ error: 'Build in progress' });
}
